// AUTO-GENERATED by Kiro Agent — Backend Wiring & Dev Tools
/**
 * Dev Tools actions (Phase 4) for hackathon QA.
 *
 * Each routine wraps a destructive or diagnostic backend operation behind a
 * safe boundary: failures are caught and rethrown as a clean Error whose
 * message the UI can surface in a single Alert. The synchronous force-offline
 * helpers simply proxy the networkTier override.
 *
 * __DEV__-only by intent — these deliberately bypass the normal app flows
 * (wiping the profile, purging SQLite, forcing Tier-3) and must never be wired
 * into production UI.
 */
import { isForceOffline, setForceOffline } from '@/ai/networkTier';
import { getDB, seedInitialData } from '@/db/database';
import { seedMELCs } from '@/db/ragStore';
import { CREATE_TABLES_SQL } from '@/db/schema';
import { todayISO } from '@/gamification/streakLogic';
import { unlockStreakBadges } from '@/gamification/streakService';
import { refreshOnboardingStatus } from '@/profile/onboardingState';
import { resetProfile } from '@/profile/profileStore';
import { storageDeleteItem } from '@/profile/secureStorage';

/** Secure-store key for the first-run completion flag (mirrors profileStore). */
const FIRST_RUN_DONE_KEY = 'suri.first_run_complete';

/** Normalize any thrown value into a readable message. */
function messageOf(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

/**
 * Clear ONLY the first-run flag (the profile is preserved) and republish the
 * onboarding status so the next gate treats this as a first-run user. The UI is
 * responsible for navigating to the grade-level screen after this resolves.
 */
export async function resetOnboarding(): Promise<string> {
  try {
    await storageDeleteItem(FIRST_RUN_DONE_KEY);
    await refreshOnboardingStatus();
    return 'Onboarding flag cleared';
  } catch (err) {
    throw new Error(`Reset onboarding failed: ${messageOf(err)}`);
  }
}

/**
 * Wipe the stored Learning Profile AND the first-run flag, returning the app to
 * a pristine first-run state, then republish onboarding status.
 */
export async function clearProfileData(): Promise<string> {
  try {
    await resetProfile();
    await refreshOnboardingStatus();
    return 'Profile + first-run wiped';
  } catch (err) {
    throw new Error(`Clear profile failed: ${messageOf(err)}`);
  }
}

/**
 * Drop every user table, recreate the full schema, and reseed baseline + MELC
 * data. Foreign keys are toggled off during the drop so table order is
 * irrelevant. Returns a summary of how many tables were recreated.
 */
export async function purgeDatabase(): Promise<string> {
  try {
    const db = getDB();
    const rows = await db.getAllAsync<{ name: string }>(
      "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'",
    );
    await db.execAsync('PRAGMA foreign_keys = OFF;');
    for (const r of rows) {
      // eslint-disable-next-line no-await-in-loop
      await db.runAsync(`DROP TABLE IF EXISTS "${r.name}"`);
    }
    await db.execAsync('PRAGMA foreign_keys = ON;');
    await db.execAsync('PRAGMA user_version = 0;');
    await db.execAsync(CREATE_TABLES_SQL);
    await seedInitialData(db);
    await seedMELCs();
    return `Recreated ${rows.length} tables + reseeded`;
  } catch (err) {
    throw new Error(`Purge database failed: ${messageOf(err)}`);
  }
}

/**
 * Flip the force-offline (Tier-3 simulation) developer override and return the
 * new state. Synchronous — the override is a process-local flag.
 */
export function toggleForceOffline(): boolean {
  const next = !isForceOffline();
  setForceOffline(next);
  return next;
}

/** Current force-offline override state. */
export function isOfflineForced(): boolean {
  return isForceOffline();
}

/**
 * Inject a 7-day streak into the single streaks row (id = 1) and unlock the
 * streak-milestone badges that become eligible at 7 days.
 */
export async function seedTestStreak(): Promise<string> {
  try {
    const db = getDB();
    const today = todayISO();
    await db.runAsync(
      `UPDATE streaks SET current_streak = 7, longest_streak = MAX(longest_streak, 7), last_study_date = ?, total_study_days = MAX(total_study_days, 7), updated_at = datetime('now') WHERE id = 1`,
      [today],
    );
    await unlockStreakBadges(7);
    return 'Seeded 7-day streak + badges';
  } catch (err) {
    throw new Error(`Seed streak failed: ${messageOf(err)}`);
  }
}
