// AUTO-GENERATED by Kiro Agent — Backend Wiring & Dev Tools
/**
 * Hidden Dev Tools menu (Phase 4) for hackathon QA.
 *
 * Renders nothing in production (the __DEV__ guard is the component's first
 * statement). In development it shows a deliberately subtle, muted app-version
 * label at the bottom of the Profile tab; long-pressing it opens a modal of QA
 * actions. This component OWNS all of its styling via the local StyleSheet
 * below and must never depend on or mutate styles in profile.tsx.
 */
import { Button, Card, ThemedText } from '@/components/ui';
import { colors, radii, spacing } from '@/theme';
import Constants from 'expo-constants';
import { useRouter, type Href } from 'expo-router';
import { useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';

import * as devActions from './devActions';

/** Onboarding entry point reached after a reset/wipe (cast for typed routes). */
const GRADE_LEVEL_ROUTE = '/onboarding/grade-level' as Href;

/** App version surfaced on the discrete trigger + modal header. */
const APP_VERSION = Constants.expoConfig?.version ?? '?';

export function DevTools() {
  if (!__DEV__) {
    return null;
  }

  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [offlineForced, setOfflineForced] = useState<boolean>(() => devActions.isOfflineForced());

  const closeMenu = (): void => setOpen(false);

  /** Surface any failure as a single, uniform Dev Tools alert. */
  const surface = (message: string): void => {
    Alert.alert('Dev Tools', message);
  };

  const handleResetOnboarding = async (): Promise<void> => {
    try {
      await devActions.resetOnboarding();
      closeMenu();
      router.replace(GRADE_LEVEL_ROUTE);
    } catch (err) {
      surface(err instanceof Error ? err.message : String(err));
    }
  };

  const handleClearProfile = (): void => {
    Alert.alert(
      'Clear Profile Data',
      'This wipes the saved Learning Profile and the first-run flag. This cannot be undone. Continue?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Wipe',
          style: 'destructive',
          onPress: async () => {
            try {
              await devActions.clearProfileData();
              closeMenu();
              router.replace(GRADE_LEVEL_ROUTE);
            } catch (err) {
              surface(err instanceof Error ? err.message : String(err));
            }
          },
        },
      ],
    );
  };

  const handlePurgeDatabase = (): void => {
    Alert.alert(
      'Purge Database',
      'This drops and recreates every SQLite table, then reseeds baseline + MELC data. This cannot be undone. Continue?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Purge',
          style: 'destructive',
          onPress: async () => {
            try {
              const message = await devActions.purgeDatabase();
              surface(message);
            } catch (err) {
              surface(err instanceof Error ? err.message : String(err));
            }
          },
        },
      ],
    );
  };

  const handleToggleOffline = (): void => {
    try {
      const next = devActions.toggleForceOffline();
      setOfflineForced(next);
    } catch (err) {
      surface(err instanceof Error ? err.message : String(err));
    }
  };

  const handleSeedStreak = async (): Promise<void> => {
    try {
      const message = await devActions.seedTestStreak();
      surface(message);
    } catch (err) {
      surface(err instanceof Error ? err.message : String(err));
    }
  };

  return (
    <View style={styles.trigger}>
      {/* Discrete trigger: muted version label, long-press to reveal QA tools. */}
      <Pressable
        accessibilityRole="button"
        accessibilityLabel="Dev Tools"
        accessibilityHint="Long press to open hidden developer QA tools"
        onLongPress={() => setOpen(true)}
        delayLongPress={500}
        hitSlop={8}
        style={styles.triggerPressable}
      >
        <ThemedText variant="caption" color={colors.textMuted} center>
          {`Suri v${APP_VERSION}`}
        </ThemedText>
        <ThemedText variant="caption" color={colors.textMuted} center style={styles.triggerHint}>
          Dev Tools · long-press
        </ThemedText>
      </Pressable>

      <Modal
        visible={open}
        transparent
        animationType="slide"
        onRequestClose={closeMenu}
        statusBarTranslucent
      >
        {/* Tapping the dimmed backdrop closes; inner press is swallowed. */}
        <Pressable style={styles.backdrop} onPress={closeMenu}>
          <Pressable style={styles.sheetWrap} onPress={() => undefined}>
            <Card style={styles.sheet}>
              <View style={styles.header}>
                <ThemedText variant="title" style={styles.headerTitle}>
                  Dev Tools
                </ThemedText>
                <ThemedText variant="caption" color={colors.textSecondary}>
                  {`__DEV__ only · Suri v${APP_VERSION}`}
                </ThemedText>
              </View>

              <ScrollView
                contentContainerStyle={styles.actions}
                showsVerticalScrollIndicator={false}
              >
                <Button
                  label="Reset Onboarding"
                  variant="outline"
                  fullWidth
                  icon="refresh"
                  onPress={handleResetOnboarding}
                />
                <Button
                  label="Clear Profile Data"
                  variant="outline"
                  fullWidth
                  icon="trash-outline"
                  onPress={handleClearProfile}
                />
                <Button
                  label="Purge Database"
                  variant="outline"
                  fullWidth
                  icon="server-outline"
                  onPress={handlePurgeDatabase}
                />

                {/* Force Offline Mode: a stateful toggle row (not a one-shot). */}
                <Pressable
                  accessibilityRole="switch"
                  accessibilityState={{ checked: offlineForced }}
                  accessibilityLabel="Force Offline Mode"
                  onPress={handleToggleOffline}
                  style={styles.toggleRow}
                >
                  <View style={styles.toggleText}>
                    <ThemedText variant="label">Force Offline Mode</ThemedText>
                    <ThemedText
                      variant="caption"
                      color={colors.textSecondary}
                      style={styles.toggleDesc}
                    >
                      Simulates Tier-3 (on-device SLM) without turning off Wi-Fi
                    </ThemedText>
                  </View>
                  <View style={[styles.badge, offlineForced ? styles.badgeOn : styles.badgeOff]}>
                    <ThemedText
                      variant="label"
                      color={offlineForced ? colors.textOnAccent : colors.textSecondary}
                    >
                      {offlineForced ? 'ON' : 'OFF'}
                    </ThemedText>
                  </View>
                </Pressable>

                <Button
                  label="Seed Test Streak"
                  variant="outline"
                  fullWidth
                  icon="flame-outline"
                  onPress={handleSeedStreak}
                />
              </ScrollView>

              <Button label="Close" variant="primary" fullWidth onPress={closeMenu} />
            </Card>
          </Pressable>
        </Pressable>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  // Subtle footer slot at the very bottom of the profile scroll content.
  trigger: {
    marginTop: spacing.xl,
    alignItems: 'center',
  },
  triggerPressable: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    opacity: 0.6,
  },
  triggerHint: {
    marginTop: spacing.xs,
  },
  // Modal scaffold.
  backdrop: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
  },
  sheetWrap: {
    width: '100%',
  },
  sheet: {
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingBottom: spacing.xxl,
    gap: spacing.lg,
    maxHeight: '85%',
  },
  header: {
    gap: spacing.xs,
  },
  headerTitle: {
    fontWeight: '700',
  },
  actions: {
    gap: spacing.md,
    paddingBottom: spacing.xs,
  },
  // Force-offline toggle row.
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    minHeight: 56,
  },
  toggleText: {
    flex: 1,
    paddingRight: spacing.md,
  },
  toggleDesc: {
    marginTop: spacing.xs,
  },
  badge: {
    minWidth: 52,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeOn: {
    backgroundColor: colors.accentSecondary,
  },
  badgeOff: {
    backgroundColor: colors.surfaceElevated,
  },
});
