/**
 * Quiz feature types (Pagsusulit).
 *
 * A quiz is a small set of multiple-choice questions generated by the AI and
 * grounded in the student's MELC curriculum. Kept intentionally minimal so the
 * engine, screen, and (future) persistence all share one shape.
 */

/** A single multiple-choice question. Exactly four choices, one correct. */
export interface QuizQuestion {
  /** The question stem. */
  question: string;
  /** Exactly four answer options. */
  choices: string[];
  /** Index (0-3) of the correct option in `choices`. */
  correctIndex: number;
  /** One- to two-sentence rationale shown after the student answers. */
  explanation: string;
}

/** A generated quiz: a topic + its questions. */
export interface Quiz {
  /** Unique-enough id (also a future quiz_attempts PK). */
  id: string;
  /** The topic the questions cover (e.g. "Photosynthesis"). */
  topic: string;
  /** Grade level the quiz was generated for. */
  gradeLevel: number;
  /** The questions, in display order. */
  questions: QuizQuestion[];
}

/** Raised when the AI returns no usable questions (offline / unparseable). */
export class QuizGenerationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'QuizGenerationError';
  }
}
