// AUTO-GENERATED by Kiro Agent — Final Native Wiring & QA
// Status: 100% Completion Target
//
// Jest configuration for the Suri app. Uses the jest-expo preset so React
// Native / Expo modules transform correctly, and maps the "@/..." path alias to
// src/ to mirror tsconfig.json. The integration suites under __tests__/ exercise
// PURE orchestration logic (no native modules), so they run reliably in CI.
/** @type {import('jest').Config} */
module.exports = {
  preset: 'jest-expo',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  testMatch: [
    '**/__tests__/**/*.test.ts',
    '**/__tests__/**/*.test.tsx',
  ],
  // jest-expo already provides a sensible transformIgnorePatterns covering the
  // RN/Expo ecosystem; extend it to also transform the newly added native libs.
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|react-native-reanimated|react-native-worklets|@react-native-ml-kit/.*))',
  ],
};
