// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — onboarding Stack; verify screen order matches spec 7.
import { Stack } from 'expo-router';

import { colors } from '@/theme';

/**
 * Onboarding navigator (spec 7). A headerless stack on the dark canvas that
 * walks a first-run student through five steps, in order:
 *   grade-level → language → learning-profile → accessibility → melc-download
 */
export default function OnboardingLayout() {
  return (
    <Stack
      screenOptions={{
        headerShown: false,
        contentStyle: { backgroundColor: colors.background },
      }}
    >
      <Stack.Screen name="grade-level" />
      <Stack.Screen name="language" />
      <Stack.Screen name="learning-profile" />
      <Stack.Screen name="accessibility" />
      <Stack.Screen name="melc-download" />
    </Stack>
  );
}
