// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — comfort settings bind live to the profile (step 4/5).
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Switch, View } from 'react-native';

import { Button, Screen, ThemedText } from '@/components/ui';
import {
  COLOR_VISION_MODES,
  type AccessibilitySettings,
  type ColorVisionMode,
} from '@/profile/types';
import { useProfile } from '@/profile/useProfile';
import { colors, radii, spacing } from '@/theme';

/** Boolean comfort settings (everything except the colorVision selector). */
type ToggleKey = Exclude<keyof AccessibilitySettings, 'colorVision'>;

interface ToggleRow {
  readonly key: ToggleKey;
  readonly label: string;
  readonly description: string;
}

/** Labeled by EFFECT, never by condition (spec 5.6). */
const TOGGLES: readonly ToggleRow[] = [
  {
    key: 'readerFont',
    label: 'Reader Font (OpenDyslexic)',
    description: 'Switch to a dyslexia-friendly typeface.',
  },
  { key: 'highContrast', label: 'High Contrast', description: 'Boost contrast for easier reading.' },
  { key: 'largeText', label: 'Larger Text', description: 'Scale all text up for comfort.' },
  {
    key: 'focusMode',
    label: 'Focus Mode',
    description: 'Trim distractions to one thing at a time.',
  },
  { key: 'lowMotion', label: 'Reduce Motion', description: 'Calm animations and transitions.' },
];

const COLOR_VISION_LABEL: Record<ColorVisionMode, string> = {
  standard: 'Standard',
  deuteranopia: 'Deuteranopia',
  protanopia: 'Protanopia',
  tritanopia: 'Tritanopia',
};

export default function AccessibilityScreen() {
  const router = useRouter();
  const { profile, updateAccessibility } = useProfile();
  const settings = profile.accessibilitySettings;

  // Boolean keys are all `boolean`-typed, so this stays type-safe per key.
  const setToggle = <K extends ToggleKey>(key: K, value: boolean): void => {
    void updateAccessibility({ [key]: value } as Pick<AccessibilitySettings, K>);
  };

  const cycleColorVision = (): void => {
    const index = COLOR_VISION_MODES.indexOf(settings.colorVision);
    const next = COLOR_VISION_MODES[(index + 1) % COLOR_VISION_MODES.length];
    void updateAccessibility({ colorVision: next });
  };

  const goNext = () => router.push('/onboarding/melc-download');

  return (
    <Screen scroll>
      <ThemedText variant="caption" color={colors.accentPrimary}>
        STEP 4 OF 5
      </ThemedText>
      <ThemedText variant="h1" style={styles.heading}>
        Make it comfortable
      </ThemedText>
      <ThemedText variant="body" color={colors.textSecondary} style={styles.subheading}>
        Optional — you can change these anytime from your Profile.
      </ThemedText>

      <View style={styles.rows}>
        {TOGGLES.map((row) => (
          <View key={row.key} style={styles.row}>
            <View style={styles.rowText}>
              <ThemedText variant="title">{row.label}</ThemedText>
              <ThemedText variant="bodySmall" color={colors.textMuted} style={styles.rowDesc}>
                {row.description}
              </ThemedText>
            </View>
            <Switch
              value={settings[row.key]}
              onValueChange={(value) => setToggle(row.key, value)}
              trackColor={{ false: colors.surfaceAlt, true: colors.accentPrimaryDim }}
              thumbColor={settings[row.key] ? colors.accentPrimary : colors.textMuted}
              ios_backgroundColor={colors.surfaceAlt}
            />
          </View>
        ))}

        <Pressable
          onPress={cycleColorVision}
          accessibilityRole="button"
          accessibilityLabel={`Color Vision: ${COLOR_VISION_LABEL[settings.colorVision]}. Tap to change.`}
          style={styles.row}
        >
          <View style={styles.rowText}>
            <ThemedText variant="title">Color Vision</ThemedText>
            <ThemedText variant="bodySmall" color={colors.textMuted} style={styles.rowDesc}>
              Tune diagram colors for color blindness.
            </ThemedText>
          </View>
          <View style={styles.cycle}>
            <ThemedText variant="label" color={colors.accentPrimary}>
              {COLOR_VISION_LABEL[settings.colorVision]}
            </ThemedText>
            <Ionicons name="swap-horizontal" size={18} color={colors.accentPrimary} />
          </View>
        </Pressable>
      </View>

      <View style={styles.footer}>
        <Button label="Next" icon="arrow-forward" onPress={goNext} fullWidth />
        <Button label="Skip for now" variant="ghost" onPress={goNext} fullWidth />
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  heading: { marginTop: spacing.sm },
  subheading: { marginTop: spacing.xs, marginBottom: spacing.xl },
  rows: { gap: spacing.md },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.lg,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  rowText: { flex: 1, paddingRight: spacing.md },
  rowDesc: { marginTop: spacing.xs },
  cycle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  footer: { marginTop: spacing.xxl, gap: spacing.sm },
});
