// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — grade + optional subject capture (onboarding step 1/5).
import { useRouter } from 'expo-router';
import { useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';

import { Button, Screen, ThemedText } from '@/components/ui';
import { MAX_GRADE_LEVEL, MIN_GRADE_LEVEL } from '@/profile/types';
import { useProfile } from '@/profile/useProfile';
import { colors, radii, spacing } from '@/theme';

/** Subject focus chips (spec 7 onboarding). Selecting again clears the choice. */
const SUBJECTS = ['Math', 'Science', 'English', 'Filipino', 'Araling Panlipunan'] as const;

const GRADES: number[] = Array.from(
  { length: MAX_GRADE_LEVEL - MIN_GRADE_LEVEL + 1 },
  (_, index) => MIN_GRADE_LEVEL + index,
);

export default function GradeLevelScreen() {
  const router = useRouter();
  const { profile, update, isLoading } = useProfile();

  const [grade, setGrade] = useState<number>(profile.gradeLevel);
  const [subject, setSubject] = useState<string | null>(profile.subject);
  const [saving, setSaving] = useState(false);
  const seeded = useRef(false);

  // Seed the controls once from the persisted profile after the first load.
  useEffect(() => {
    if (!isLoading && !seeded.current) {
      setGrade(profile.gradeLevel);
      setSubject(profile.subject);
      seeded.current = true;
    }
  }, [isLoading, profile.gradeLevel, profile.subject]);

  const handleNext = async () => {
    setSaving(true);
    try {
      await update({ gradeLevel: grade, subject });
      router.push('/onboarding/language');
    } finally {
      setSaving(false);
    }
  };

  return (
    <Screen scroll>
      <ThemedText variant="caption" color={colors.accentPrimary}>
        STEP 1 OF 5
      </ThemedText>
      <ThemedText variant="h1" style={styles.heading}>
        What grade are you in?
      </ThemedText>
      <ThemedText variant="body" color={colors.textSecondary} style={styles.subheading}>
        Suri tailors stories and answers to your level.
      </ThemedText>

      <View style={styles.grid}>
        {GRADES.map((value) => {
          const selected = value === grade;
          return (
            <Pressable
              key={value}
              onPress={() => setGrade(value)}
              accessibilityRole="button"
              accessibilityState={{ selected }}
              accessibilityLabel={`Grade ${value}`}
              style={[styles.pill, selected && styles.pillSelected]}
            >
              <ThemedText
                variant="title"
                color={selected ? colors.textOnAccent : colors.textPrimary}
              >
                {value}
              </ThemedText>
            </Pressable>
          );
        })}
      </View>

      <ThemedText variant="title" style={styles.sectionTitle}>
        Focus subject
      </ThemedText>
      <ThemedText variant="bodySmall" color={colors.textMuted} style={styles.sectionHint}>
        Optional — pick one to prioritize, or skip.
      </ThemedText>

      <View style={styles.chips}>
        {SUBJECTS.map((name) => {
          const selected = name === subject;
          return (
            <Pressable
              key={name}
              onPress={() => setSubject(selected ? null : name)}
              accessibilityRole="button"
              accessibilityState={{ selected }}
              style={[styles.chip, selected && styles.chipSelected]}
            >
              <ThemedText
                variant="label"
                color={selected ? colors.textOnAccent : colors.textSecondary}
              >
                {name}
              </ThemedText>
            </Pressable>
          );
        })}
      </View>

      <View style={styles.footer}>
        <Button label="Next" icon="arrow-forward" onPress={handleNext} loading={saving} fullWidth />
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  heading: { marginTop: spacing.sm },
  subheading: { marginTop: spacing.xs, marginBottom: spacing.xl },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  pill: {
    minWidth: 56,
    height: 56,
    paddingHorizontal: spacing.md,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pillSelected: {
    backgroundColor: colors.accentPrimary,
    borderColor: colors.accentPrimary,
  },
  sectionTitle: { marginTop: spacing.xl },
  sectionHint: { marginTop: spacing.xs, marginBottom: spacing.md },
  chips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  chip: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipSelected: {
    backgroundColor: colors.accentPrimary,
    borderColor: colors.accentPrimary,
  },
  footer: { marginTop: spacing.xxl },
});
