// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — language register selection (onboarding step 2/5).
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';

import { Button, Screen, ThemedText } from '@/components/ui';
import { LANGUAGE_PREFERENCES, type LanguagePreference } from '@/profile/types';
import { useProfile } from '@/profile/useProfile';
import { colors, radii, spacing } from '@/theme';

/** Friendly copy for each language register (spec 5.8 / onboarding step 2). */
const LANGUAGE_COPY: Record<LanguagePreference, { title: string; description: string }> = {
  tagalog: { title: 'Tagalog', description: 'Buong Filipino — pure Tagalog explanations.' },
  taglish: { title: 'Taglish', description: 'A natural mix of Filipino and English.' },
  english: { title: 'English', description: 'Full English explanations.' },
};

export default function LanguageScreen() {
  const router = useRouter();
  const { profile, update, isLoading } = useProfile();

  const [language, setLanguage] = useState<LanguagePreference>(profile.languagePreference);
  const [saving, setSaving] = useState(false);
  const seeded = useRef(false);

  // Seed the selection once from the persisted profile after the first load.
  useEffect(() => {
    if (!isLoading && !seeded.current) {
      setLanguage(profile.languagePreference);
      seeded.current = true;
    }
  }, [isLoading, profile.languagePreference]);

  const handleNext = async () => {
    setSaving(true);
    try {
      await update({ languagePreference: language });
      router.push('/onboarding/learning-profile');
    } finally {
      setSaving(false);
    }
  };

  return (
    <Screen scroll>
      <ThemedText variant="caption" color={colors.accentPrimary}>
        STEP 2 OF 5
      </ThemedText>
      <ThemedText variant="h1" style={styles.heading}>
        Pick your language
      </ThemedText>
      <ThemedText variant="body" color={colors.textSecondary} style={styles.subheading}>
        How should Suri talk with you?
      </ThemedText>

      <View style={styles.options}>
        {LANGUAGE_PREFERENCES.map((preference) => {
          const selected = preference === language;
          const copy = LANGUAGE_COPY[preference];
          return (
            <Pressable
              key={preference}
              onPress={() => setLanguage(preference)}
              accessibilityRole="radio"
              accessibilityState={{ selected }}
              style={[styles.option, selected && styles.optionSelected]}
            >
              <View style={styles.optionText}>
                <ThemedText variant="title">{copy.title}</ThemedText>
                <ThemedText
                  variant="bodySmall"
                  color={colors.textSecondary}
                  style={styles.optionDesc}
                >
                  {copy.description}
                </ThemedText>
              </View>
              <Ionicons
                name={selected ? 'radio-button-on' : 'radio-button-off'}
                size={22}
                color={selected ? colors.accentPrimary : colors.textMuted}
              />
            </Pressable>
          );
        })}
      </View>

      <View style={styles.footer}>
        <Button label="Next" icon="arrow-forward" onPress={handleNext} loading={saving} fullWidth />
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  heading: { marginTop: spacing.sm },
  subheading: { marginTop: spacing.xs, marginBottom: spacing.xl },
  options: { gap: spacing.md },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.lg,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  optionSelected: {
    borderColor: colors.accentPrimary,
    backgroundColor: colors.accentPrimaryDim,
  },
  optionText: { flex: 1, paddingRight: spacing.md },
  optionDesc: { marginTop: spacing.xs },
  footer: { marginTop: spacing.xxl },
});
