// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — 5-question learning-style quiz (onboarding step 3/5).
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';

import { Button, Screen, ThemedText } from '@/components/ui';
import { RESPONSE_MODES, type ResponseMode } from '@/profile/types';
import { useProfile } from '@/profile/useProfile';
import { colors, radii, spacing } from '@/theme';

interface QuizOption {
  readonly label: string;
  readonly mode: ResponseMode;
}

interface QuizQuestion {
  readonly prompt: string;
  readonly options: readonly QuizOption[];
}

/** Five plain-language questions; each option maps to a ResponseMode (spec 5.6). */
const QUESTIONS: readonly QuizQuestion[] = [
  {
    prompt: 'When you learn something new, what helps the most?',
    options: [
      { label: 'Seeing pictures, diagrams, or charts', mode: 'visual' },
      { label: 'Listening to someone explain it', mode: 'auditory' },
      { label: 'Reading about it on my own', mode: 'reading' },
      { label: 'Trying it out with my hands', mode: 'kinesthetic' },
      { label: 'A little bit of everything', mode: 'mixed' },
    ],
  },
  {
    prompt: 'You just finished a tricky lesson. What do you do next?',
    options: [
      { label: 'Draw a diagram or map of the idea', mode: 'visual' },
      { label: 'Say it out loud or talk it through', mode: 'auditory' },
      { label: 'Write notes in my own words', mode: 'reading' },
      { label: 'Build or act out an example', mode: 'kinesthetic' },
    ],
  },
  {
    prompt: 'Which kind of homework feels easiest?',
    options: [
      { label: 'Labeling pictures or making charts', mode: 'visual' },
      { label: 'Recording myself and listening back', mode: 'auditory' },
      { label: 'Writing a short summary', mode: 'reading' },
      { label: 'Doing a hands-on activity', mode: 'kinesthetic' },
    ],
  },
  {
    prompt: 'How would you like Suri to explain an answer?',
    options: [
      { label: 'Show me a picture or diagram', mode: 'visual' },
      { label: 'Read it to me out loud', mode: 'auditory' },
      { label: 'Give me clear text to read', mode: 'reading' },
      { label: 'Walk me through steps I can try', mode: 'kinesthetic' },
      { label: 'Mix it up', mode: 'mixed' },
    ],
  },
  {
    prompt: 'Studying for a quiz, what works best for you?',
    options: [
      { label: 'Color-coding and visuals', mode: 'visual' },
      { label: 'Repeating it out loud', mode: 'auditory' },
      { label: 'Re-reading my notes', mode: 'reading' },
      { label: 'Flashcards I flip and sort', mode: 'kinesthetic' },
    ],
  },
];

/** Most-picked mode wins; any tie resolves to 'mixed' (spec default). */
function resolveResponseMode(answers: readonly ResponseMode[]): ResponseMode {
  const counts: Record<ResponseMode, number> = {
    visual: 0,
    auditory: 0,
    reading: 0,
    kinesthetic: 0,
    mixed: 0,
  };
  for (const answer of answers) {
    counts[answer] += 1;
  }
  const max = Math.max(...RESPONSE_MODES.map((mode) => counts[mode]));
  const leaders = RESPONSE_MODES.filter((mode) => counts[mode] === max);
  return leaders.length === 1 ? leaders[0] : 'mixed';
}

export default function LearningProfileScreen() {
  const router = useRouter();
  const { update } = useProfile();

  const [current, setCurrent] = useState(0);
  const [answers, setAnswers] = useState<ResponseMode[]>([]);
  const [saving, setSaving] = useState(false);

  const total = QUESTIONS.length;
  const question = QUESTIONS[current];
  const progress = Math.round(((current + 1) / total) * 100);

  const finish = async (finalAnswers: ResponseMode[]) => {
    setSaving(true);
    try {
      await update({ responseMode: resolveResponseMode(finalAnswers) });
      router.push('/onboarding/accessibility');
    } finally {
      setSaving(false);
    }
  };

  const handleSelect = (mode: ResponseMode) => {
    if (saving) return;
    const next = answers.slice();
    next[current] = mode;
    setAnswers(next);
    if (current < total - 1) {
      setCurrent(current + 1);
    } else {
      void finish(next);
    }
  };

  const handleBack = () => {
    if (current > 0) setCurrent(current - 1);
  };

  return (
    <Screen scroll>
      <ThemedText variant="caption" color={colors.accentPrimary}>
        QUESTION {current + 1} OF {total}
      </ThemedText>

      <View style={styles.track}>
        <View style={[styles.fill, { width: `${progress}%` }]} />
      </View>

      <ThemedText variant="h2" style={styles.prompt}>
        {question.prompt}
      </ThemedText>

      <View style={styles.options}>
        {question.options.map((option) => {
          const selected = answers[current] === option.mode;
          return (
            <Pressable
              key={option.label}
              onPress={() => handleSelect(option.mode)}
              accessibilityRole="button"
              accessibilityState={{ selected }}
              style={[styles.option, selected && styles.optionSelected]}
            >
              <ThemedText
                variant="body"
                color={selected ? colors.textOnAccent : colors.textPrimary}
              >
                {option.label}
              </ThemedText>
            </Pressable>
          );
        })}
      </View>

      {current > 0 ? (
        <View style={styles.footer}>
          <Button
            label="Back"
            variant="ghost"
            icon="chevron-back"
            onPress={handleBack}
            disabled={saving}
          />
        </View>
      ) : null}
    </Screen>
  );
}

const styles = StyleSheet.create({
  track: {
    height: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceAlt,
    marginTop: spacing.sm,
    marginBottom: spacing.xl,
    overflow: 'hidden',
  },
  fill: {
    height: '100%',
    borderRadius: radii.pill,
    backgroundColor: colors.accentPrimary,
  },
  prompt: { marginBottom: spacing.xl },
  options: { gap: spacing.md },
  option: {
    padding: spacing.lg,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  optionSelected: {
    backgroundColor: colors.accentPrimary,
    borderColor: colors.accentPrimary,
  },
  footer: { marginTop: spacing.xl, alignItems: 'flex-start' },
});
