// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — offline-ready confirmation + onboarding completion (step 5/5).
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, View } from 'react-native';

import { Button, Card, Screen, ThemedText } from '@/components/ui';
import { completeOnboarding } from '@/profile/onboardingState';
import { colors, spacing } from '@/theme';

export default function MelcDownloadScreen() {
  const router = useRouter();
  const [ready, setReady] = useState(false);
  const [starting, setStarting] = useState(false);

  useEffect(() => {
    // The MELC corpus is already seeded at app boot (app/_layout.tsx → seedMELCs).
    // This is just a brief, friendly readiness beat — not an actual download.
    const timer = setTimeout(() => setReady(true), 1200);
    return () => clearTimeout(timer);
  }, []);

  const handleStart = async () => {
    setStarting(true);
    try {
      await completeOnboarding();
      router.replace('/(tabs)');
    } catch {
      // Stay on this screen so the student can retry.
      setStarting(false);
    }
  };

  return (
    <Screen center>
      <Card neon style={styles.card}>
        {ready ? (
          <Ionicons name="checkmark-circle" size={56} color={colors.accentSecondary} />
        ) : (
          <ActivityIndicator size="large" color={colors.accentPrimary} />
        )}

        <ThemedText variant="h2" center style={styles.title}>
          {ready ? 'Your curriculum is ready' : 'Preparing your offline curriculum'}
        </ThemedText>
        <ThemedText variant="body" color={colors.textSecondary} center>
          {ready
            ? 'Lessons are saved on your device. Tap below to begin.'
            : 'Setting up DepEd MELC lessons for offline study…'}
        </ThemedText>

        <View style={styles.offlineNote}>
          <Ionicons name="cloud-offline-outline" size={16} color={colors.accentSecondary} />
          <ThemedText variant="caption" color={colors.textMuted}>
            Stories and answers work fully offline.
          </ThemedText>
        </View>
      </Card>

      <View style={styles.footer}>
        <Button
          label="Magsimula"
          icon="rocket"
          onPress={handleStart}
          loading={starting}
          disabled={!ready}
          fullWidth
        />
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  card: {
    alignSelf: 'stretch',
    alignItems: 'center',
    gap: spacing.md,
  },
  title: { marginTop: spacing.sm },
  offlineNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  footer: {
    alignSelf: 'stretch',
    marginTop: spacing.xl,
  },
});
