// AUTO-GENERATED by Kiro Agent — Final Native Wiring & QA
// Status: 100% Completion Target
/**
 * Real background telemetry sync (spec 5.10) via expo-background-fetch +
 * expo-task-manager.
 *
 * The previous sync was an in-app drain only — it ran solely while a screen
 * called it. This module registers an OS-scheduled background task so the
 * anonymized competency queue is drained during periodic Wi-Fi windows even
 * when the app is backgrounded (Android keeps the task across termination and
 * reboot).
 *
 * The task handler MUST be defined in the module's global scope (expo-task-
 * manager requirement: the JS bundle is spun up headless to run the task, with
 * no React tree mounted), so TaskManager/BackgroundFetch are imported
 * statically here rather than lazily — unlike the native seams elsewhere that
 * defer their imports.
 *
 * SECURITY NOTE: only anonymized, competency-level rows are synced. The queue
 * (eventQueue.ts) enforces no-PII at enqueue time, and the drain (syncManager →
 * pushBatch) forwards exactly those rows. The Learning Profile and any raw
 * student content NEVER leave the device — there is no code path from either
 * into this task.
 */
import * as BackgroundFetch from 'expo-background-fetch';
import * as TaskManager from 'expo-task-manager';

import { getNetworkTier } from '@/ai/networkTier';

import { getUnsyncedCount } from './eventQueue';
import { syncPendingEvents } from './syncManager';

/** Unique name the background task is registered + dispatched under. */
export const TELEMETRY_SYNC_TASK = 'suri-telemetry-sync';

/**
 * Register the headless task handler at module load (global scope, as required
 * by expo-task-manager). When woken by the OS it drains the telemetry queue —
 * but only when there is real connectivity, so a student's battery/data is
 * never spent dialing out while offline.
 */
TaskManager.defineTask(TELEMETRY_SYNC_TASK, async () => {
  try {
    // Offline (Tier 3): nothing to push; let the next window try again.
    if ((await getNetworkTier()) === 'offline') {
      return BackgroundFetch.BackgroundFetchResult.NoData;
    }
    const pushed = await syncPendingEvents();
    return pushed > 0
      ? BackgroundFetch.BackgroundFetchResult.NewData
      : BackgroundFetch.BackgroundFetchResult.NoData;
  } catch {
    // Any failure (transient network, DB busy) — report Failed so the platform
    // can reschedule; the unsynced rows stay queued for the next window.
    return BackgroundFetch.BackgroundFetchResult.Failed;
  }
});

/**
 * Register the periodic background telemetry sync. Idempotent: if the task is
 * already registered this is a no-op, so it is safe to call on every app start.
 *
 * @param minimumIntervalSeconds Advisory minimum seconds between runs (the OS
 *   may space them further to save battery). Defaults to 15 minutes.
 */
export async function registerTelemetrySync(minimumIntervalSeconds = 15 * 60): Promise<void> {
  const alreadyRegistered = await TaskManager.isTaskRegisteredAsync(TELEMETRY_SYNC_TASK);
  if (alreadyRegistered) {
    return;
  }
  await BackgroundFetch.registerTaskAsync(TELEMETRY_SYNC_TASK, {
    minimumInterval: minimumIntervalSeconds,
    stopOnTerminate: false,
    startOnBoot: true,
  });
}

/**
 * Unregister the periodic background telemetry sync. Idempotent: a no-op when
 * the task is not currently registered.
 */
export async function unregisterTelemetrySync(): Promise<void> {
  const registered = await TaskManager.isTaskRegisteredAsync(TELEMETRY_SYNC_TASK);
  if (registered) {
    await BackgroundFetch.unregisterTaskAsync(TELEMETRY_SYNC_TASK);
  }
}

/**
 * Manually trigger a sync now (e.g. from a "Sync now" settings action). Returns
 * the number of events pushed. Skips the drain and returns 0 when offline so
 * callers get an immediate, honest result without a doomed network attempt.
 */
export async function syncNow(): Promise<number> {
  if ((await getNetworkTier()) === 'offline') {
    return 0;
  }
  return syncPendingEvents();
}

/**
 * Count of competency events still pending sync. Surfaced for diagnostics and a
 * future "N events pending" telemetry indicator; reads straight from the
 * on-device queue and performs no network I/O.
 */
export async function getPendingTelemetryCount(): Promise<number> {
  return getUnsyncedCount();
}
