// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — added screen-facing buildKasabayPrompt({studentQuestion}); legacy service overload + helpers preserved.
/**
 * Kasabay Mode prompt construction (pure module — no native imports, headlessly
 * verifiable).
 *
 * Two call shapes share the buildKasabayPrompt name via overloads:
 *
 *   1. SCREEN path (presentation layer, spec 5.10): a small, self-contained
 *      persona prompt built from just the student's question + a vibe check +
 *      optional memory. Returns { system, user }, which feeds straight into
 *      generateWithPrompt({ system, user }). This is what the Kasabay Mode tab
 *      calls — it streams a reply directly, without the RAG/misconception
 *      orchestration.
 *
 *   2. SERVICE path (backend, kasabayService.handleInterruption): the richer,
 *      RAG-grounded, misconception-aware prompt that fills the {{PLACEHOLDER}}
 *      tokens in KASABAY_SYSTEM_PROMPT. Returns { systemPrompt, userPrompt }.
 *
 * Keeping both behind one name lets the screen use the simple signature while
 * the existing service + headless verifier keep their behaviour unchanged.
 */
import type { MisconceptionDetectionResponse } from '@/features/misconception/types/misconception.types';

import {
  COGNITIVE_MODIFIER_DESCRIPTIONS,
  KASABAY_OFFLINE_SYSTEM_PROMPT,
  KASABAY_SYSTEM_PROMPT,
  NO_RECENT_TOPIC,
} from '../constants/kasabayDefaults';
import type {
  CognitiveModifier,
  KasabayInterruptionRequest,
} from '../types/kasabay.types';

/** Legacy (service) result: fills the {{PLACEHOLDER}} template. */
export interface BuiltKasabayPrompt {
  systemPrompt: string;
  userPrompt: string;
}

/** Screen-facing input (presentation layer). */
export interface KasabayPromptInput {
  /** What the student typed when they paused the focus timer. */
  studentQuestion: string;
  /** Coarse "vibe check" nudging Suri's tone/length. Default "Neutral / focused". */
  cognitiveModifier?: string;
  /** What you studied together last; the memory line is omitted when absent. */
  lastTopicDiscussed?: string;
}

/** Screen-facing result: feeds straight into generateWithPrompt({ system, user }). */
export interface KasabayPrompt {
  system: string;
  user: string;
}

/** Vibe check used by the screen path when the caller supplies none. */
const DEFAULT_SCREEN_MODIFIER = 'Neutral / focused';

/** Replace EVERY occurrence of each {{KEY}} token (tokens may repeat). */
function fillTemplate(template: string, values: Record<string, string>): string {
  let result = template;
  for (const [key, value] of Object.entries(values)) {
    result = result.split(`{{${key}}}`).join(value);
  }
  return result;
}

/** The human "vibe check" phrasing injected as {{COGNITIVE_MODIFIER}}. */
export function describeCognitiveModifier(modifier: CognitiveModifier): string {
  return COGNITIVE_MODIFIER_DESCRIPTIONS[modifier];
}

/**
 * The rule-#3 note: when a misconception was detected, tell Suri to address that
 * specific wrong belief before the correct answer. Empty string when none.
 */
export function buildMisconceptionNote(
  misconception: MisconceptionDetectionResponse | null,
): string {
  if (!misconception || !misconception.has_misconception) {
    return '';
  }
  const type = misconception.misconception_type ?? 'misconception';
  return (
    `- HEADS UP (Misconception Detection): the student likely believes ` +
    `"${misconception.specific_wrong_belief}" (${type}). Per rule #3, gently address ` +
    `THIS belief first, then explain. Correct understanding: ${misconception.correct_understanding}`
  );
}

function melcBlock(passages: string[] | undefined): string {
  const list = passages ?? [];
  return list.length > 0
    ? list.join('\n\n')
    : '(no passage retrieved \u2014 answer from general knowledge but stay curriculum-appropriate)';
}

/**
 * Build the compact, self-contained persona prompt for the Kasabay Mode screen.
 * Encodes the spec 5.10 rules without the service path's RAG/language tokens.
 */
function buildScreenSystemPrompt(cognitiveModifier: string, lastTopicDiscussed?: string): string {
  const modifier =
    cognitiveModifier.trim().length > 0 ? cognitiveModifier.trim() : DEFAULT_SCREEN_MODIFIER;
  const memory =
    lastTopicDiscussed && lastTopicDiscussed.trim().length > 0
      ? `- Memory: the last thing you studied together was "${lastTopicDiscussed.trim()}". Bring it up only if it genuinely connects to what they're asking now.\n`
      : '';

  return (
    `You are Suri, the student's study companion in "Kasabay Mode". You are sitting at the same virtual desk, studying alongside them, and they just paused their focus timer to ask you something.\n\n` +
    `Who you are right now:\n` +
    `- A peer studying WITH them, never a lecturer. Stay warm, calm, and encouraging.\n` +
    `- Mirror the student's language naturally \u2014 Tagalog, Taglish, or English, whichever they used.\n` +
    `- Vibe check: ${modifier}. Match your energy and length to it.\n` +
    memory +
    `\nHow you reply:\n` +
    `1. Gently acknowledge the interruption first (e.g. "Stuck ka ba? Patingin nga," or "Walang problema, tingnan natin 'to.").\n` +
    `2. Answer their actual question, simply and concretely.\n` +
    `3. If the question shows a wrong belief, gently correct that belief BEFORE giving the right answer.\n` +
    `4. End by checking if they understand it well enough to resume the timer (e.g. "Gets mo na ba? Ready ka nang ituloy?").\n\n` +
    `Talk like you just looked up from your own textbook. No markdown headers, no long intros \u2014 just speak to them directly.`
  );
}

/**
 * Build the Kasabay persona prompt.
 *
 * Overload 1 (screen): from { studentQuestion, cognitiveModifier?, lastTopicDiscussed? }
 * returns { system, user } for generateWithPrompt.
 *
 * Overload 2 (service): from a full KasabayInterruptionRequest (+ optional
 * misconception) returns the RAG/misconception-grounded { systemPrompt, userPrompt }.
 */
export function buildKasabayPrompt(input: KasabayPromptInput): KasabayPrompt;
export function buildKasabayPrompt(
  request: KasabayInterruptionRequest,
  misconception?: MisconceptionDetectionResponse | null,
): BuiltKasabayPrompt;
export function buildKasabayPrompt(
  arg: KasabayPromptInput | KasabayInterruptionRequest,
  misconception: MisconceptionDetectionResponse | null = null,
): KasabayPrompt | BuiltKasabayPrompt {
  // Screen path — discriminated by the presence of `studentQuestion`.
  if ('studentQuestion' in arg) {
    return {
      system: buildScreenSystemPrompt(arg.cognitiveModifier ?? DEFAULT_SCREEN_MODIFIER, arg.lastTopicDiscussed),
      user: arg.studentQuestion,
    };
  }

  // Service path — fill the full {{PLACEHOLDER}} template (unchanged behaviour).
  const request = arg;
  const lastTopic =
    request.lastTopicDiscussed && request.lastTopicDiscussed.trim().length > 0
      ? request.lastTopicDiscussed
      : NO_RECENT_TOPIC;

  const systemPrompt = fillTemplate(KASABAY_SYSTEM_PROMPT, {
    LANGUAGE_PREFERENCE: request.language,
    COGNITIVE_MODIFIER: describeCognitiveModifier(request.cognitiveModifier),
    LAST_TOPIC_DISCUSSED: lastTopic,
    MELC_PASSAGES: melcBlock(request.melcPassages),
    MISCONCEPTION_NOTE: buildMisconceptionNote(misconception),
  });

  const userPrompt =
    `The student looked up from their worksheet and asked:\n\n` +
    `"${request.studentMessage}"\n\n` +
    `Topic: ${request.melcTopic}. Reply as Suri, their study seatmate.`;

  return { systemPrompt, userPrompt };
}

/** Build the compact offline (Tier-3) Kasabay prompt. */
export function buildKasabayOfflinePrompt(
  request: KasabayInterruptionRequest,
): BuiltKasabayPrompt {
  const systemPrompt = fillTemplate(KASABAY_OFFLINE_SYSTEM_PROMPT, {
    LANGUAGE_PREFERENCE: request.language,
    MELC_PASSAGES: melcBlock(request.melcPassages),
  });

  const userPrompt = `"${request.studentMessage}"`;

  return { systemPrompt, userPrompt };
}
