// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — "Stuck ka ba?" interruption CTA (lime secondary + hand icon).
import { Button } from '@/components/ui';

export interface InterruptButtonProps {
  /** Pause the timer and open the "ask Suri" panel. */
  onPress: () => void;
  disabled?: boolean;
}

/**
 * The prominent interruption affordance (spec 5.10). The student taps this to
 * look up from their worksheet and ask Suri for help mid-block.
 */
export function InterruptButton({ onPress, disabled = false }: InterruptButtonProps) {
  return (
    <Button
      label="Stuck ka ba?"
      variant="secondary"
      icon="hand-left"
      onPress={onPress}
      disabled={disabled}
      fullWidth
    />
  );
}
