// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — pure-logic countdown; start/pause is parent-controlled via `running`.
import { useEffect, useRef, useState } from 'react';
import { StyleSheet, View } from 'react-native';

import { ThemedText } from '@/components/ui';
import { spacing } from '@/theme';

import { KASABAY_THEME } from '../constants/kasabayTheme';

export interface StudyTimerProps {
  /** Planned focus block length in minutes. Default 25 (a Pomodoro). */
  durationMinutes?: number;
  /** Whether the countdown is ticking. The parent owns start/pause. */
  running: boolean;
  /** Fired once when the countdown reaches 00:00. */
  onComplete?: () => void;
}

/** Format a whole number of seconds as mm:ss (clamped at zero). */
export function formatSeconds(totalSeconds: number): string {
  const clamped = Math.max(0, Math.floor(totalSeconds));
  const minutes = Math.floor(clamped / 60);
  const seconds = clamped % 60;
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
}

/**
 * A self-contained mm:ss countdown. Pure logic: it counts down while `running`
 * is true and freezes when false (the parent toggles it). The display resets
 * whenever the planned duration changes.
 */
export function StudyTimer({ durationMinutes = 25, running, onComplete }: StudyTimerProps) {
  const [secondsLeft, setSecondsLeft] = useState(() => durationMinutes * 60);
  // Guard so onComplete fires exactly once per block.
  const completedRef = useRef(false);

  // Reset the countdown when the planned duration changes.
  useEffect(() => {
    setSecondsLeft(durationMinutes * 60);
    completedRef.current = false;
  }, [durationMinutes]);

  // Tick once per second while running; clearing the interval pauses it.
  useEffect(() => {
    if (!running) {
      return;
    }
    const id = setInterval(() => {
      setSecondsLeft((prev) => (prev > 0 ? prev - 1 : 0));
    }, 1000);
    return () => clearInterval(id);
  }, [running]);

  // Fire onComplete exactly once when the block hits zero.
  useEffect(() => {
    if (secondsLeft === 0 && !completedRef.current) {
      completedRef.current = true;
      onComplete?.();
    }
  }, [secondsLeft, onComplete]);

  const status = secondsLeft === 0 ? 'Tapos na!' : running ? 'Nag-aaral...' : 'Naka-pause';

  return (
    <View style={styles.container}>
      <ThemedText
        variant="display"
        center
        color={running ? KASABAY_THEME.teal : KASABAY_THEME.textPrimary}
        accessibilityRole="timer"
      >
        {formatSeconds(secondsLeft)}
      </ThemedText>
      <ThemedText variant="caption" color={KASABAY_THEME.textMuted} center>
        {status}
      </ThemedText>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
});
