// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — placeholder avatar; idle bob now driven by react-native-reanimated (worklets babel plugin configured).
import { Ionicons } from '@expo/vector-icons';
import { useEffect } from 'react';
import { StyleSheet, View } from 'react-native';
import Animated, { useSharedValue, useAnimatedStyle, withRepeat, withTiming, withSequence, Easing, cancelAnimation } from 'react-native-reanimated';

import { radii } from '@/theme';

import { KASABAY_THEME } from '../constants/kasabayTheme';

export interface SuriIdleAnimationProps {
  /** When true, render a completely static avatar (spec 5.6 reduce-motion). */
  lowMotion: boolean;
  /** Avatar footprint in px. Default 112. */
  size?: number;
}

/**
 * Placeholder "Suri at her desk" avatar. Pixel-art sprites are pending, so for
 * now Suri is represented by a book over a rounded surface with a coffee accent.
 *
 * Motion uses react-native-reanimated: a shared value drives a gentle vertical
 * "breathing" bob (0 -> -8 -> 0) on a ~1600ms ease-in-out loop, run on the UI
 * thread via withRepeat(withSequence(...), -1). When `lowMotion` is set the
 * avatar is rendered completely static (spec 5.6 reduce-motion) and no animation
 * is ever started.
 */
export function SuriIdleAnimation({ lowMotion, size = 112 }: SuriIdleAnimationProps) {
  const translateY = useSharedValue(0);

  useEffect(() => {
    if (lowMotion) {
      // Reduced motion: keep the avatar perfectly still; never start a loop.
      translateY.value = 0;
      return;
    }
    // Gentle "breathing" bob: 0 -> -8 -> 0, ease-in-out, repeated forever.
    translateY.value = withRepeat(
      withSequence(
        withTiming(-8, { duration: 1600, easing: Easing.inOut(Easing.ease) }),
        withTiming(0, { duration: 1600, easing: Easing.inOut(Easing.ease) }),
      ),
      -1,
    );
    return () => {
      cancelAnimation(translateY);
    };
  }, [lowMotion]);

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [{ translateY: translateY.value }],
  }));

  const deskStyle = {
    width: size,
    height: size,
    borderRadius: radii.lg,
  };

  const avatar = (
    <View style={[styles.desk, deskStyle]}>
      <Ionicons name="cafe" size={size * 0.22} color={KASABAY_THEME.lime} style={styles.accent} />
      <Ionicons name="book" size={size * 0.46} color={KASABAY_THEME.teal} />
    </View>
  );

  // Reduced-motion: a still avatar, no Animated wrapper at all.
  if (lowMotion) {
    return <View style={styles.wrap}>{avatar}</View>;
  }

  return <Animated.View style={[styles.wrap, animatedStyle]}>{avatar}</Animated.View>;
}

const styles = StyleSheet.create({
  wrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  desk: {
    backgroundColor: KASABAY_THEME.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: KASABAY_THEME.teal,
  },
  accent: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
});
