// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — dark "tambayan" canvas with neon teal/lime accent edges.
import { StyleSheet, View } from 'react-native';

import { ThemedText } from '@/components/ui';
import { spacing } from '@/theme';

import { KASABAY_THEME } from '../constants/kasabayTheme';
import { SuriIdleAnimation } from './SuriIdleAnimation';

export interface SuriDeskCanvasProps {
  /** Forwarded to the avatar so it renders static under reduce-motion. */
  lowMotion: boolean;
}

/**
 * The full-bleed "tambayan" study-desk canvas (spec 5.10). A dark OLED surface
 * framed by neon teal (top) and lime (bottom) accents, with Suri centered at her
 * desk. Deliberately minimal chrome — the focus is the shared study space.
 */
export function SuriDeskCanvas({ lowMotion }: SuriDeskCanvasProps) {
  return (
    <View style={styles.canvas}>
      <SuriIdleAnimation lowMotion={lowMotion} />
      <ThemedText variant="caption" color={KASABAY_THEME.textMuted} center>
        Kasabay mo si Suri
      </ThemedText>
    </View>
  );
}

const styles = StyleSheet.create({
  canvas: {
    flex: 1,
    backgroundColor: KASABAY_THEME.canvas,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.lg,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xxl,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderTopColor: KASABAY_THEME.teal,
    borderBottomColor: KASABAY_THEME.lime,
  },
});
