// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — DB-init pipeline preserved; added font load + first-run gate.
import { Redirect, Slot, useSegments } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import { ErrorBoundary } from '@/components/ErrorBoundary';
import { initDB } from '@/db/database';
import { seedMELCs } from '@/db/ragStore';
import { maybeRegisterSLM } from '@/ai/offlineSLM';
import { registerTelemetrySync } from '@/telemetry/backgroundSync';
import { verifyDB } from '@/db/verifyDB';
import { verifyRAG } from '@/db/verifyRAG';
import { colors, spacing, typography, useAppFonts } from '@/theme';
import {
  refreshOnboardingStatus,
  useOnboardingStatus,
} from '@/profile/onboardingState';
import { SettingsProvider } from '@/state/settingsContext';

type InitState =
  | { phase: 'loading' }
  | { phase: 'ready' }
  | { phase: 'error'; error: Error };

/**
 * Root layout. Owns a single, isolated database-initialization pipeline that
 * runs before any route is rendered, so every screen below <Slot /> can safely
 * assume getDB() returns a live, seeded connection.
 *
 * After init it resolves first-run status and, on first run, redirects into the
 * onboarding flow (spec 7). OpenDyslexic is loaded in the background (spec 5.6);
 * loading never blocks rendering.
 */
export default function RootLayout() {
  const [state, setState] = useState<InitState>({ phase: 'loading' });
  const segments = useSegments();
  const onboardingStatus = useOnboardingStatus();

  // Load the dyslexia-friendly font in the background (additive, non-blocking).
  useAppFonts();

  useEffect(() => {
    let mounted = true;

    (async () => {
      try {
        await initDB();
        // Seed the bundled MELC curriculum (idempotent — no-op if present).
        await seedMELCs();
        // If the offline SLM is already downloaded, wire it in as the router's
        // Tier-3 runner. No-op (keeps the extractive fallback) otherwise.
        await maybeRegisterSLM();
        // Schedule the OS-level background telemetry sync (spec 5.10). Best-effort:
        // never block boot if the platform can't register the task (e.g. Expo Go).
        try {
          await registerTelemetrySync();
        } catch {
          // Background fetch unavailable on this platform — telemetry still
          // drains in-app via syncNow(); ignore the registration failure.
        }
        // Headless validation in development only — never ships to students.
        if (__DEV__) {
          await verifyDB();
          await verifyRAG();
        }
        // Resolve whether to send the student into onboarding.
        await refreshOnboardingStatus();
        if (mounted) {
          setState({ phase: 'ready' });
        }
      } catch (error) {
        if (mounted) {
          setState({ phase: 'error', error: error as Error });
        }
      }
    })();

    return () => {
      mounted = false;
    };
  }, []);

  if (state.phase === 'error') {
    return (
      <View style={styles.center}>
        <Text style={styles.title}>Couldn&apos;t prepare local storage</Text>
        <Text style={styles.detail}>{state.error.message}</Text>
      </View>
    );
  }

  if (state.phase === 'loading' || onboardingStatus === 'unknown') {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color={colors.accentPrimary} />
        <Text style={styles.detail}>Preparing your offline study companion…</Text>
      </View>
    );
  }

  // First run → onboarding (unless we are already inside the onboarding group).
  if (onboardingStatus === 'first-run' && segments[0] !== 'onboarding') {
    return (
      <ErrorBoundary>
        <SettingsProvider>
          <SafeAreaProvider>
            <Redirect href="/onboarding/grade-level" />
          </SafeAreaProvider>
        </SettingsProvider>
      </ErrorBoundary>
    );
  }

  return (
    <ErrorBoundary>
      <SettingsProvider>
        <SafeAreaProvider>
          <Slot />
        </SafeAreaProvider>
      </SettingsProvider>
    </ErrorBoundary>
  );
}

const styles = StyleSheet.create({
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.md,
    backgroundColor: colors.background,
  },
  title: {
    ...typography.title,
    color: colors.textPrimary,
    textAlign: 'center',
  },
  detail: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    textAlign: 'center',
  },
});
