// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — DB-init pipeline preserved; added font load + first-run gate.
import { Redirect, Slot, useSegments } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import { ErrorBoundary } from '@/components/ErrorBoundary';
import { initDB } from '@/db/database';
import { seedMELCs } from '@/db/ragStore';
import { maybeRegisterSLM } from '@/ai/offlineSLM';
import { colors, spacing, typography, useAppFonts } from '@/theme';
import {
  refreshOnboardingStatus,
  useOnboardingStatus,
} from '@/profile/onboardingState';
import { SettingsProvider } from '@/state/settingsContext';

type InitState =
  | { phase: 'loading' }
  | { phase: 'ready' }
  | { phase: 'error'; error: Error };

/**
 * Root layout. Owns a single, isolated database-initialization pipeline that
 * runs before any route is rendered, so every screen below <Slot /> can safely
 * assume getDB() returns a live, seeded connection.
 *
 * After init it resolves first-run status and, on first run, redirects into the
 * onboarding flow (spec 7). OpenDyslexic is loaded in the background (spec 5.6);
 * loading never blocks rendering.
 */
export default function RootLayout() {
  const [state, setState] = useState<InitState>({ phase: 'loading' });
  const segments = useSegments();
  const onboardingStatus = useOnboardingStatus();

  // Load the dyslexia-friendly font in the background (additive, non-blocking).
  useAppFonts();

  useEffect(() => {
    let mounted = true;

    // Safety-net timeout: if init hasn't resolved in 8 seconds, proceed
    // anyway so the student isn't stuck on a spinner forever.
    const timeout = setTimeout(() => {
      if (mounted) {
        console.warn('[Suri] Init timed out after 8 s — proceeding with partial init.');
        setState({ phase: 'ready' });
      }
    }, 8000);

    (async () => {
      try {
        await initDB();
      } catch (err) {
        console.warn('[Suri] initDB failed:', err);
        // DB is critical — if it fails, show the error screen.
        if (mounted) {
          setState({ phase: 'error', error: err as Error });
        }
        clearTimeout(timeout);
        return;
      }

      // Seed MELCs — best-effort; don't block on failure.
      try {
        await seedMELCs();
      } catch (err) {
        console.warn('[Suri] seedMELCs failed (non-fatal):', err);
      }

      // SLM registration — best-effort; extractive fallback is the default.
      try {
        await maybeRegisterSLM();
      } catch (err) {
        console.warn('[Suri] maybeRegisterSLM failed (non-fatal):', err);
      }

      // Telemetry — dynamic import to avoid TaskManager.defineTask() crash in
      // Expo Go. Best-effort; never block boot.
      try {
        const { registerTelemetrySync: reg } = await import('@/telemetry/backgroundSync');
        await reg();
      } catch (err) {
        console.warn('[Suri] Telemetry sync registration skipped:', err);
      }

      // Skip __DEV__ verifiers — they are useful but can hang in Expo Go and
      // should never block the student from using the app.

      // Resolve onboarding status.
      try {
        await refreshOnboardingStatus();
      } catch (err) {
        console.warn('[Suri] refreshOnboardingStatus failed (non-fatal):', err);
      }

      if (mounted) {
        clearTimeout(timeout);
        setState({ phase: 'ready' });
      }
    })();

    return () => {
      mounted = false;
      clearTimeout(timeout);
    };
  }, []);

  if (state.phase === 'error') {
    return (
      <View style={styles.center}>
        <Text style={styles.title}>Couldn&apos;t prepare local storage</Text>
        <Text style={styles.detail}>{state.error.message}</Text>
      </View>
    );
  }

  if (state.phase === 'loading' || onboardingStatus === 'unknown') {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color={colors.accentPrimary} />
        <Text style={styles.detail}>Preparing your offline study companion…</Text>
      </View>
    );
  }

  // First run → onboarding (unless we are already inside the onboarding group).
  if (onboardingStatus === 'first-run' && segments[0] !== 'onboarding') {
    return (
      <ErrorBoundary>
        <SettingsProvider>
          <SafeAreaProvider>
            <Redirect href="/onboarding/grade-level" />
          </SafeAreaProvider>
        </SettingsProvider>
      </ErrorBoundary>
    );
  }

  return (
    <ErrorBoundary>
      <SettingsProvider>
        <SafeAreaProvider>
          <Slot />
        </SafeAreaProvider>
      </SettingsProvider>
    </ErrorBoundary>
  );
}

const styles = StyleSheet.create({
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.md,
    backgroundColor: colors.background,
  },
  title: {
    ...typography.title,
    color: colors.textPrimary,
    textAlign: 'center',
  },
  detail: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    textAlign: 'center',
  },
});
