// AUTO-GENERATED by Kiro Agent — Backend Wiring & Dev Tools
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Button, ThemedText } from '@/components/ui';
import { CameraScanner } from '@/features/ocr/components/CameraScanner';
import type { OcrIngestResult } from '@/features/ocr/types/ocr.types';
import { awardBadge } from '@/gamification/streakService';
import { useProfile } from '@/profile/useProfile';
import { colors, radii, spacing } from '@/theme';

/**
 * Full-screen worksheet scanner route (spec 5.5).
 *
 * Mounts {@link CameraScanner}, which captures a photo, runs on-device text
 * recognition, and ingests the result into the student's personal RAG layer so
 * the AI can answer about the scanned worksheet — fully offline. The student's
 * subject + grade level are read from the profile and stamped onto the ingested
 * chunks so they can be filtered during retrieval.
 *
 * Reached via `router.push('/scan')` (e.g. the Aklatan/Review scan FAB). It is a
 * top-level route (not under app/(tabs)), so it renders full-screen with no tab
 * bar and owns its own minimal, theme-aligned styling.
 */
export default function ScanScreen() {
  const { profile } = useProfile();
  const [result, setResult] = useState<OcrIngestResult | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  /** Persist the success state and best-effort unlock the camera badge. */
  const handleIngested = useCallback((ingested: OcrIngestResult) => {
    setErrorMessage(null);
    setResult(ingested);
    // Gamification is non-critical: award the badge once, never block the flow.
    try {
      void awardBadge('first_camera').catch(() => {});
    } catch {
      // Ignore — a failed badge unlock must not interrupt a successful scan.
    }
  }, []);

  /**
   * Light screen-level error note. CameraScanner already surfaces its own inline
   * banner (including the Expo Go "OCR not available" case), so we just keep a
   * friendly message and never crash the screen.
   */
  const handleError = useCallback((error: Error) => {
    setErrorMessage(error.message);
  }, []);

  return (
    <SafeAreaView style={styles.root} edges={['top', 'bottom']}>
      <View style={styles.header}>
        <ThemedText variant="h2" color={colors.textPrimary} style={styles.headerTitle}>
          I-scan ang Worksheet
        </ThemedText>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel="Isara ang scanner"
          hitSlop={8}
          onPress={() => router.back()}
          style={styles.closeButton}
        >
          <Ionicons name="close" size={24} color={colors.textPrimary} />
        </Pressable>
      </View>

      {errorMessage && !result ? (
        <View style={styles.errorBanner} accessibilityLiveRegion="polite">
          <ThemedText variant="bodySmall" color={colors.danger} center>
            {errorMessage}
          </ThemedText>
        </View>
      ) : null}

      <View style={styles.body}>
        {result ? (
          <View style={styles.successCard}>
            <Ionicons name="checkmark-circle" size={64} color={colors.accentSecondary} />
            <ThemedText variant="title" color={colors.textPrimary} center>
              Tagumpay ang pag-scan!
            </ThemedText>
            <ThemedText variant="body" color={colors.textSecondary} center>
              {`Na-save sa iyong reviewer: ${result.chunkCount} bahagi`}
            </ThemedText>
            <Button label="Bumalik" icon="arrow-back" fullWidth onPress={() => router.back()} />
          </View>
        ) : (
          <CameraScanner
            subject={profile.subject}
            gradeLevel={profile.gradeLevel}
            onIngested={handleIngested}
            onError={handleError}
          />
        )}
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  headerTitle: {
    flex: 1,
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceAlt,
  },
  errorBanner: {
    marginHorizontal: spacing.lg,
    marginBottom: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  body: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
  },
  successCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.lg,
    padding: spacing.xl,
  },
});
