// AUTO-GENERATED by Kiro Agent — Final Native Wiring & QA
// Status: 100% Completion Target
import { type ReactElement } from 'react';
import { StyleSheet, View } from 'react-native';
import Svg, { Circle, G, Line, Polyline, Rect, Text as SvgText } from 'react-native-svg';

import { colors, radii, spacing, useAccessibleTheme } from '@/theme';
import {
  paletteFor,
  type BarChartSpec,
  type ColorVisionMode,
  type DiagramSpec,
  type LineChartSpec,
  type MapSpec,
  type NumberLineSpec,
  type VisualSpec,
} from '@/visuals/visualParser';

export interface VisualRendererProps {
  /** The validated spec to draw (produced by `parseVisualSpec`). */
  spec: VisualSpec;
  /** Canvas width in px. Default 320. */
  width?: number;
  /** Canvas height in px. Default 220. */
  height?: number;
  /**
   * Color-vision mode used when the spec carries no explicit palette. When
   * omitted it falls back to the student's saved color-vision setting (spec
   * 5.6), so every chart is colorblind-safe globally without per-call wiring.
   */
  colorVisionMode?: ColorVisionMode;
}

/** Inner gutter around the drawing surface. */
const PADDING = spacing.lg;
/** Vertical space reserved at the top when the spec has a title. */
const TITLE_BAND = 26;
/** Vertical space reserved at the bottom of x-axis charts for labels. */
const AXIS_LABEL_BAND = 18;

/** A resolved rectangle (in svg coordinates) the body is drawn inside. */
interface RenderArea {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * Render a parsed {@link VisualSpec} as an accessible, colorblind-aware SVG
 * (spec 5.4). Every branch is defensive: empty data, mismatched label/value
 * lengths, and a zero maximum are all handled without throwing, so a malformed
 * spec degrades to an empty (but valid) canvas rather than crashing a lesson.
 */
export function VisualRenderer({
  spec,
  width = 320,
  height = 220,
  colorVisionMode,
}: VisualRendererProps) {
  // Fall back to the student's saved color-vision setting when the caller
  // doesn't pin one explicitly (spec 5.6 — global colorblind-safe charts).
  const { colorVision } = useAccessibleTheme();
  const activeColorVision: ColorVisionMode = colorVisionMode ?? colorVision;
  const hasTitle = typeof spec.title === 'string' && spec.title.length > 0;
  const area: RenderArea = {
    x: PADDING,
    y: PADDING + (hasTitle ? TITLE_BAND : 0),
    w: Math.max(0, width - PADDING * 2),
    h: Math.max(0, height - PADDING * 2 - (hasTitle ? TITLE_BAND : 0)),
  };

  return (
    <View
      style={[styles.container, { width, height }]}
      accessible
      accessibilityRole="image"
      accessibilityLabel={describeSpec(spec)}
    >
      <Svg width={width} height={height}>
        <Rect x={0} y={0} width={width} height={height} rx={radii.md} fill={colors.surface} />
        {hasTitle ? (
          <SvgText
            x={width / 2}
            y={PADDING + 14}
            fill={colors.textPrimary}
            fontSize={14}
            fontWeight="bold"
            textAnchor="middle"
          >
            {spec.title}
          </SvgText>
        ) : null}
        {renderBody(spec, area, activeColorVision)}
      </Svg>
    </View>
  );
}

/** Dispatch to the per-type renderer. Exhaustive over every {@link VisualSpec}. */
function renderBody(spec: VisualSpec, area: RenderArea, mode: ColorVisionMode): ReactElement[] | null {
  switch (spec.type) {
    case 'bar_chart':
      return renderBarChart(spec, area, mode);
    case 'line_chart':
      return renderLineChart(spec, area, mode);
    case 'number_line':
      return renderNumberLine(spec, area, mode);
    case 'diagram':
      return renderDiagram(spec, area, mode);
    case 'map':
      return renderMap(spec, area, mode);
    default: {
      // Compile-time exhaustiveness guard: if a new VisualType is added the
      // assignment below fails to type-check until a case is handled here.
      const exhaustiveCheck: never = spec;
      return exhaustiveCheck;
    }
  }
}

/** Resolve the spec's palette, falling back to a color-vision-aware default. */
function resolvePalette(spec: VisualSpec, mode: ColorVisionMode, count: number): string[] {
  if (spec.palette && spec.palette.length > 0) {
    return spec.palette;
  }
  return paletteFor(mode, Math.max(1, count));
}

/** Vertical bars scaled to the max value, with a baseline and x-axis labels. */
function renderBarChart(spec: BarChartSpec, area: RenderArea, mode: ColorVisionMode): ReactElement[] {
  const { labels, values } = spec.data;
  const count = values.length;
  if (count === 0 || area.w <= 0 || area.h <= 0) {
    return [];
  }

  const palette = resolvePalette(spec, mode, count);
  const plotBottom = area.y + area.h - AXIS_LABEL_BAND;
  const plotHeight = Math.max(0, plotBottom - area.y);
  const max = values.reduce((acc, value) => (value > acc ? value : acc), 0);
  const denominator = max <= 0 ? 1 : max; // guard divide-by-zero when max === 0
  const slot = area.w / count;
  const barWidth = Math.max(2, slot * 0.6);

  const elements: ReactElement[] = [
    <Line
      key="bar-baseline"
      x1={area.x}
      y1={plotBottom}
      x2={area.x + area.w}
      y2={plotBottom}
      stroke={colors.border}
      strokeWidth={1}
    />,
  ];

  for (let i = 0; i < count; i += 1) {
    const value = values[i];
    const safeValue = Number.isFinite(value) ? Math.max(0, value) : 0;
    const barHeight = max <= 0 ? 0 : (safeValue / denominator) * plotHeight;
    const x = area.x + slot * i + (slot - barWidth) / 2;
    const centerX = area.x + slot * i + slot / 2;
    const fill = palette[i % palette.length];
    elements.push(
      <G key={`bar-${i}`}>
        <Rect x={x} y={plotBottom - barHeight} width={barWidth} height={barHeight} rx={4} fill={fill} />
        <SvgText x={centerX} y={plotBottom + 13} fill={colors.textSecondary} fontSize={10} textAnchor="middle">
          {labels[i] ?? ''}
        </SvgText>
      </G>,
    );
  }

  return elements;
}

/** A polyline through the scaled points, a baseline axis, and point markers. */
function renderLineChart(spec: LineChartSpec, area: RenderArea, mode: ColorVisionMode): ReactElement[] {
  const { labels, values } = spec.data;
  if (area.w <= 0 || area.h <= 0) {
    return [];
  }

  const count = values.length;
  const palette = resolvePalette(spec, mode, count);
  const stroke = palette[0];
  const plotBottom = area.y + area.h - AXIS_LABEL_BAND;
  const plotHeight = Math.max(0, plotBottom - area.y);
  const max = values.reduce((acc, value) => (value > acc ? value : acc), 0);
  const denominator = max <= 0 ? 1 : max; // guard divide-by-zero when max === 0

  const elements: ReactElement[] = [
    <Line
      key="line-baseline"
      x1={area.x}
      y1={plotBottom}
      x2={area.x + area.w}
      y2={plotBottom}
      stroke={colors.border}
      strokeWidth={1}
    />,
  ];

  if (count === 0) {
    return elements;
  }

  const xFor = (i: number): number =>
    count === 1 ? area.x + area.w / 2 : area.x + (area.w / (count - 1)) * i;
  const yFor = (value: number): number => {
    const safeValue = Number.isFinite(value) ? Math.max(0, value) : 0;
    return max <= 0 ? plotBottom : plotBottom - (safeValue / denominator) * plotHeight;
  };

  if (count >= 2) {
    const points = values.map((value, i) => `${xFor(i)},${yFor(value)}`).join(' ');
    elements.push(
      <Polyline key="line-path" points={points} fill="none" stroke={stroke} strokeWidth={2} />,
    );
  }

  for (let i = 0; i < count; i += 1) {
    const value = values[i];
    elements.push(<Circle key={`line-point-${i}`} cx={xFor(i)} cy={yFor(value)} r={3} fill={stroke} />);
    const label = labels[i];
    if (label) {
      elements.push(
        <SvgText
          key={`line-label-${i}`}
          x={xFor(i)}
          y={plotBottom + 13}
          fill={colors.textSecondary}
          fontSize={10}
          textAnchor="middle"
        >
          {label}
        </SvgText>,
      );
    }
  }

  return elements;
}

/** A horizontal axis from min..max with optional step ticks and emphasized marks. */
function renderNumberLine(spec: NumberLineSpec, area: RenderArea, mode: ColorVisionMode): ReactElement[] {
  if (area.w <= 0 || area.h <= 0) {
    return [];
  }

  const palette = resolvePalette(spec, mode, 1);
  const markColor = palette[0];
  const { min, max } = spec;
  const range = max - min;
  const denominator = range <= 0 ? 1 : range; // guard divide-by-zero on bad specs
  const axisY = area.y + area.h / 2;
  const mapX = (value: number): number => area.x + ((value - min) / denominator) * area.w;

  const elements: ReactElement[] = [
    <Line
      key="nl-axis"
      x1={area.x}
      y1={axisY}
      x2={area.x + area.w}
      y2={axisY}
      stroke={colors.textSecondary}
      strokeWidth={2}
    />,
  ];

  // Step ticks (bounded iteration so a tiny/zero step can never loop forever).
  const ticks: number[] = [];
  if (typeof spec.step === 'number' && spec.step > 0 && range > 0) {
    const maxTicks = 100;
    let value = min;
    let guard = 0;
    while (value <= max + 1e-9 && guard < maxTicks) {
      ticks.push(value);
      value += spec.step;
      guard += 1;
    }
  }

  if (ticks.length > 0) {
    ticks.forEach((value, i) => {
      const x = mapX(value);
      elements.push(
        <Line key={`nl-tick-${i}`} x1={x} y1={axisY - 5} x2={x} y2={axisY + 5} stroke={colors.textSecondary} strokeWidth={1} />,
      );
      elements.push(
        <SvgText key={`nl-tick-label-${i}`} x={x} y={axisY + 18} fill={colors.textMuted} fontSize={9} textAnchor="middle">
          {formatNumber(value)}
        </SvgText>,
      );
    });
  } else {
    // No usable step: label just the endpoints so the scale is still readable.
    elements.push(
      <SvgText key="nl-min" x={area.x} y={axisY + 18} fill={colors.textMuted} fontSize={9} textAnchor="middle">
        {formatNumber(min)}
      </SvgText>,
      <SvgText key="nl-max" x={area.x + area.w} y={axisY + 18} fill={colors.textMuted} fontSize={9} textAnchor="middle">
        {formatNumber(max)}
      </SvgText>,
    );
  }

  // Emphasized marks (only those that actually fall on the axis).
  const marks = (spec.marks ?? []).filter((mark) => Number.isFinite(mark) && mark >= min && mark <= max);
  marks.forEach((mark, i) => {
    const x = mapX(mark);
    elements.push(
      <Circle key={`nl-mark-${i}`} cx={x} cy={axisY} r={6} fill={markColor} stroke={colors.surface} strokeWidth={2} />,
    );
    elements.push(
      <SvgText key={`nl-mark-label-${i}`} x={x} y={axisY - 12} fill={colors.textPrimary} fontSize={10} fontWeight="bold" textAnchor="middle">
        {formatNumber(mark)}
      </SvgText>,
    );
  });

  return elements;
}

/** Each component as a labeled box, stacked vertically under a type heading. */
function renderDiagram(spec: DiagramSpec, area: RenderArea, mode: ColorVisionMode): ReactElement[] {
  const count = spec.components.length;
  if (count === 0 || area.w <= 0 || area.h <= 0) {
    return [];
  }

  const palette = resolvePalette(spec, mode, count);
  const elements: ReactElement[] = [];
  let top = area.y;

  if (spec.diagramType) {
    elements.push(
      <SvgText key="diagram-type" x={area.x} y={area.y + 4} fill={colors.textMuted} fontSize={11} fontWeight="bold" textAnchor="start">
        {spec.diagramType}
      </SvgText>,
    );
    top = area.y + 18;
  }

  const gap = 8;
  const available = Math.max(0, area.y + area.h - top);
  const rowHeight = Math.max(18, (available - gap * (count - 1)) / count);

  for (let i = 0; i < count; i += 1) {
    const component = spec.components[i];
    const y = top + i * (rowHeight + gap);
    const color = palette[i % palette.length];
    const labelY = component.description ? y + rowHeight / 2 - 2 : y + rowHeight / 2 + 4;
    elements.push(
      <G key={`diagram-${i}`}>
        <Rect x={area.x} y={y} width={area.w} height={rowHeight} rx={8} fill={color} fillOpacity={0.18} stroke={color} strokeWidth={1.5} />
        <SvgText x={area.x + 12} y={labelY} fill={colors.textPrimary} fontSize={12} fontWeight="bold" textAnchor="start">
          {component.label}
        </SvgText>
        {component.description ? (
          <SvgText x={area.x + 12} y={y + rowHeight / 2 + 14} fill={colors.textSecondary} fontSize={10} textAnchor="start">
            {component.description}
          </SvgText>
        ) : null}
      </G>,
    );
  }

  return elements;
}

/** Each region as a labeled box with its optional value, stacked vertically. */
function renderMap(spec: MapSpec, area: RenderArea, mode: ColorVisionMode): ReactElement[] {
  const count = spec.regions.length;
  if (count === 0 || area.w <= 0 || area.h <= 0) {
    return [];
  }

  const palette = resolvePalette(spec, mode, count);
  const gap = 8;
  const rowHeight = Math.max(18, (area.h - gap * (count - 1)) / count);

  const elements: ReactElement[] = [];
  for (let i = 0; i < count; i += 1) {
    const region = spec.regions[i];
    const y = area.y + i * (rowHeight + gap);
    const color = palette[i % palette.length];
    elements.push(
      <G key={`map-${i}`}>
        <Rect x={area.x} y={y} width={area.w} height={rowHeight} rx={8} fill={color} fillOpacity={0.2} stroke={color} strokeWidth={1.5} />
        <SvgText x={area.x + 12} y={y + rowHeight / 2 + 4} fill={colors.textPrimary} fontSize={12} fontWeight="bold" textAnchor="start">
          {region.label}
        </SvgText>
        {typeof region.value === 'number' ? (
          <SvgText x={area.x + area.w - 12} y={y + rowHeight / 2 + 4} fill={colors.textSecondary} fontSize={11} textAnchor="end">
            {formatNumber(region.value)}
          </SvgText>
        ) : null}
      </G>,
    );
  }

  return elements;
}

/** Compact numeric label: integers as-is, otherwise trimmed to 2 decimals. */
function formatNumber(value: number): string {
  if (!Number.isFinite(value)) {
    return '';
  }
  return Number.isInteger(value) ? String(value) : value.toFixed(2);
}

/** Build a concise screen-reader description of the spec (spec 5.6 a11y). */
function describeSpec(spec: VisualSpec): string {
  const prefix = typeof spec.title === 'string' && spec.title.length > 0 ? `${spec.title}: ` : '';
  switch (spec.type) {
    case 'bar_chart':
      return `${prefix}bar chart with ${spec.data.values.length} bars`;
    case 'line_chart':
      return `${prefix}line chart with ${spec.data.values.length} points`;
    case 'number_line':
      return `${prefix}number line from ${spec.min} to ${spec.max}`;
    case 'diagram':
      return `${prefix}diagram with ${spec.components.length} parts`;
    case 'map':
      return `${prefix}map with ${spec.regions.length} regions`;
    default:
      return prefix || 'visual';
  }
}

const styles = StyleSheet.create({
  container: {
    borderRadius: radii.md,
    overflow: 'hidden',
  },
});
