// AUTO-GENERATED by Kiro Agent — STRICT UI PORT
// Visual Reference: zip(4).zip | Backend: Existing Suri Services
// Status: Needs review — palette matched 1:1 to zip(4) index.css (Material-3
//   warm terracotta light theme). No neon. Token NAMES are unchanged so every
//   screen recolors automatically.
/**
 * Centralized color system, matched to the zip(4).zip prototype's Material-3
 * @theme tokens (warm terracotta on a cream surface). Components import semantic
 * tokens from here and must NOT hardcode hex.
 *
 * Source tokens (zip(4)/src/index.css):
 *   primary #a03b0e · primary-container #c15326 · on-primary #ffffff
 *   surface #fff8f5 · surface-container-lowest #ffffff · -low #fbf2ed
 *   surface-container #f5ece7 · -high #efe6e2 · -highest #e9e1dc
 *   on-surface #1e1b18 · on-surface-variant #57423b
 *   outline #8b7269 · outline-variant #dec0b6
 *   tertiary #016576 · secondary-container #e4dfd5 · error #ba1a1a
 */
import type { ColorVisionMode } from '@/profile/types';

/** Prototype brand anchors (zip(4) index.css). */
export const PALETTE = {
  /** primary — terracotta. */
  primary: '#a03b0e',
  /** tertiary — deep teal accent (not neon). */
  tertiary: '#016576',
  /** surface/background — warm cream. */
  cream: '#fff8f5',
  white: '#ffffff',
  black: '#000000',
} as const;

/** Semantic, role-based tokens (consumed by screens). Matched to zip(4). */
export const colors = {
  // Surfaces (cream base + Material container ramp).
  background: '#fff8f5',
  surface: '#ffffff', // surface-container-lowest (cards, bubbles)
  surfaceAlt: '#f5ece7', // surface-container (chips, tracks)
  surfaceElevated: '#efe6e2', // surface-container-high

  // Accents.
  accentPrimary: '#a03b0e', // primary (terracotta)
  accentSecondary: '#016576', // tertiary (teal accent for positive/offline)
  accentPrimaryDim: 'rgba(160, 59, 14, 0.12)', // primary-container wash
  accentSecondaryDim: 'rgba(1, 101, 118, 0.12)',

  // Text (dark on light).
  textPrimary: '#1e1b18', // on-surface
  textSecondary: '#57423b', // on-surface-variant
  textMuted: '#8b7269', // outline
  textOnAccent: '#ffffff', // on-primary

  // Lines / borders.
  border: '#dec0b6', // outline-variant
  borderStrong: '#8b7269', // outline
  borderNeon: '#a03b0e', // (legacy key) primary edge — no longer neon
  borderNeonAlt: '#016576', // (legacy key) tertiary edge

  // Status.
  success: '#016576', // tertiary
  warning: '#9a6700', // warm amber (in-palette)
  danger: '#ba1a1a', // error
  info: '#016576', // tertiary

  // Misc.
  overlay: 'rgba(30, 27, 24, 0.45)',
  transparent: 'transparent',
} as const;

export type ThemeColors = Record<keyof typeof colors, string>;

/**
 * High-contrast overrides (spec 5.6) for the LIGHT theme: pure black text on
 * white, heavier borders. The terracotta accent is kept for recognizable CTAs.
 */
export const highContrastColors: ThemeColors = {
  ...colors,
  background: '#ffffff',
  surface: '#ffffff',
  surfaceAlt: '#f2f2f2',
  surfaceElevated: '#eaeaea',
  textPrimary: '#000000',
  textSecondary: '#1a1a1a',
  textMuted: '#333333',
  border: '#000000',
  borderStrong: '#000000',
};

/** Resolve the active color set for the current accessibility settings. */
export function getThemeColors(options: { highContrast?: boolean } = {}): ThemeColors {
  return options.highContrast ? highContrastColors : colors;
}

/**
 * Colorblind-safe diagram/series palettes (spec 5.4 / 5.6). Built on the
 * Okabe-Ito set; "standard" leads with the brand terracotta + teal.
 */
export const COLOR_VISION_PALETTES: Record<ColorVisionMode, readonly string[]> = {
  standard: ['#a03b0e', '#016576', '#9a6700', '#615e56', '#2e7e90', '#8b7269'],
  deuteranopia: ['#0072B2', '#E69F00', '#F0E442', '#56B4E9', '#009E73', '#000000'],
  protanopia: ['#0072B2', '#E69F00', '#F0E442', '#CC79A7', '#56B4E9', '#000000'],
  tritanopia: ['#D55E00', '#009E73', '#CC79A7', '#0072B2', '#E69F00', '#000000'],
} as const;

/** Ordered, colorblind-safe palette for the student's color-vision setting. */
export function getDiagramPalette(mode: ColorVisionMode): readonly string[] {
  return COLOR_VISION_PALETTES[mode] ?? COLOR_VISION_PALETTES.standard;
}
