// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — for true offline-first, bundle the OpenDyslexic .otf
//   into assets/fonts and switch loadDyslexicFont() to a local require().
/**
 * Font loading for Suri (spec 5.6 "Reader Font" = OpenDyslexic across the app).
 *
 * IMPORTANT (robustness): the OpenDyslexic font file is NOT yet bundled in the
 * repo. To avoid crashing the app with an unbundled asset, this loader fetches
 * the open-licensed OTF from a CDN at runtime, wrapped so that a failure (e.g.
 * offline on first run) NEVER blocks rendering — the app simply falls back to
 * the system font until the file is bundled locally. Components must only apply
 * FONT_FAMILY.dyslexic when `dyslexicAvailable` is true.
 */
import { useEffect, useState, useSyncExternalStore } from 'react';
import * as Font from 'expo-font';

/** Logical family names referenced by the typography system. */
export const FONT_FAMILY = {
  dyslexic: 'OpenDyslexic',
} as const;

/** Open-licensed (SIL OFL) OpenDyslexic regular. Replace with a local asset. */
export const OPEN_DYSLEXIC_URL =
  'https://cdn.jsdelivr.net/gh/antijingoist/opendyslexic@master/compiled/OpenDyslexic-Regular.otf';

let loadPromise: Promise<boolean> | null = null;

// --- Shared availability signal -------------------------------------------
// A tiny external store so any component (notably ThemedText) can reactively
// switch to OpenDyslexic the moment the async load settles, without each one
// re-running the loader.
let dyslexicAvailable = false;
const fontListeners = new Set<() => void>();

function setDyslexicAvailable(value: boolean): void {
  if (dyslexicAvailable === value) {
    return;
  }
  dyslexicAvailable = value;
  for (const listener of fontListeners) {
    listener();
  }
}

function subscribeDyslexic(listener: () => void): () => void {
  fontListeners.add(listener);
  return () => {
    fontListeners.delete(listener);
  };
}

function getDyslexicAvailable(): boolean {
  return dyslexicAvailable;
}

/**
 * Reactive flag: true once OpenDyslexic has loaded and is safe to apply as a
 * fontFamily. Components must gate FONT_FAMILY.dyslexic on this so the app
 * never references an unbundled asset before it is ready.
 */
export function useDyslexicFontAvailable(): boolean {
  return useSyncExternalStore(subscribeDyslexic, getDyslexicAvailable, getDyslexicAvailable);
}

/**
 * Load OpenDyslexic once (idempotent). Resolves true on success, false on any
 * failure — never throws, so callers can proceed regardless.
 */
export async function loadDyslexicFont(): Promise<boolean> {
  if (!loadPromise) {
    loadPromise = (async () => {
      try {
        await Font.loadAsync({ [FONT_FAMILY.dyslexic]: OPEN_DYSLEXIC_URL });
        setDyslexicAvailable(true);
        return true;
      } catch {
        return false;
      }
    })();
  }
  return loadPromise;
}

export interface AppFontsState {
  /** Initial load attempt has settled (success or failure). */
  fontsReady: boolean;
  /** OpenDyslexic loaded and safe to apply as a fontFamily. */
  dyslexicAvailable: boolean;
}

/**
 * Background font loader for the root layout. Returns immediately with
 * fontsReady=false then flips to true once the attempt settles. Rendering must
 * NOT be gated on this — it is purely additive.
 */
export function useAppFonts(): AppFontsState {
  const [state, setState] = useState<AppFontsState>({ fontsReady: false, dyslexicAvailable: false });

  useEffect(() => {
    let mounted = true;
    void loadDyslexicFont().then((dyslexicAvailable) => {
      if (mounted) {
        setState({ fontsReady: true, dyslexicAvailable });
      }
    });
    return () => {
      mounted = false;
    };
  }, []);

  return state;
}
