// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — single import surface for the design system.
/**
 * Design-system barrel. Import everything from `@/theme`:
 *   import { colors, spacing, radii, typography, PALETTE } from '@/theme';
 */
export {
  PALETTE,
  colors,
  highContrastColors,
  getThemeColors,
  COLOR_VISION_PALETTES,
  getDiagramPalette,
  type ThemeColors,
} from './colors';
export { spacing, radii, layout, type SpacingKey } from './spacing';
export {
  FONT_WEIGHT,
  FONT_SIZE,
  LARGE_TEXT_SCALE,
  scaleFont,
  createTypography,
  typography,
  type TypographyOptions,
} from './typography';
export {
  FONT_FAMILY,
  OPEN_DYSLEXIC_URL,
  loadDyslexicFont,
  useAppFonts,
  useDyslexicFontAvailable,
  type AppFontsState,
} from './fonts';
export { useAccessibleTheme, type AccessibleTheme } from './useAccessibleTheme';
