// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — spacing scale is a sensible default; tune with design.
/**
 * Spacing + radius scale. A single 4pt-based rhythm so every screen lines up.
 */

export const spacing = {
  none: 0,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  xxxl: 48,
} as const;

export type SpacingKey = keyof typeof spacing;

export const radii = {
  none: 0,
  sm: 8,
  md: 12,
  lg: 20,
  xl: 28,
  pill: 999,
} as const;

/** Standard screen padding so all tabs share identical gutters. */
export const layout = {
  screenPaddingH: spacing.xl,
  screenPaddingV: spacing.lg,
  cardPadding: spacing.lg,
  gap: spacing.md,
} as const;
