// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — Large Text (1.3x) factory provided; wire per screen.
/**
 * Scalable type system (spec 5.6: "Large Text" scales all text 1.3x; "Reader
 * Font" swaps to OpenDyslexic). Base styles are static for consistency; use
 * createTypography({ largeText, readerFont }) where accessibility scaling must
 * apply live.
 */
import type { TextStyle } from 'react-native';

import { FONT_FAMILY } from './fonts';

export const FONT_WEIGHT = {
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
  extrabold: '800',
} as const;

export const FONT_SIZE = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  display: 40,
} as const;

/** Spec 5.6: "Large Text" scales all text 1.3x. */
export const LARGE_TEXT_SCALE = 1.3;

export function scaleFont(size: number, largeText: boolean): number {
  return largeText ? Math.round(size * LARGE_TEXT_SCALE) : size;
}

type TypographyKey =
  | 'display'
  | 'h1'
  | 'h2'
  | 'title'
  | 'body'
  | 'bodySmall'
  | 'caption'
  | 'button'
  | 'label';

export interface TypographyOptions {
  largeText?: boolean;
  /** Apply the OpenDyslexic family only when it has actually loaded. */
  readerFont?: boolean;
}

/**
 * Build the text-style preset map, scaled for Large Text and (optionally)
 * switched to the OpenDyslexic family. Returns plain TextStyle objects safe to
 * spread into StyleSheet entries.
 */
export function createTypography(options: TypographyOptions = {}): Record<TypographyKey, TextStyle> {
  const { largeText = false, readerFont = false } = options;
  const fontFamily = readerFont ? FONT_FAMILY.dyslexic : undefined;
  const f = (size: number) => scaleFont(size, largeText);

  return {
    display: { fontFamily, fontSize: f(FONT_SIZE.display), fontWeight: FONT_WEIGHT.extrabold, lineHeight: f(FONT_SIZE.display) * 1.1 },
    h1: { fontFamily, fontSize: f(FONT_SIZE.xxl), fontWeight: FONT_WEIGHT.bold, lineHeight: f(FONT_SIZE.xxl) * 1.2 },
    h2: { fontFamily, fontSize: f(FONT_SIZE.xl), fontWeight: FONT_WEIGHT.bold, lineHeight: f(FONT_SIZE.xl) * 1.25 },
    title: { fontFamily, fontSize: f(FONT_SIZE.lg), fontWeight: FONT_WEIGHT.semibold, lineHeight: f(FONT_SIZE.lg) * 1.3 },
    body: { fontFamily, fontSize: f(FONT_SIZE.md), fontWeight: FONT_WEIGHT.regular, lineHeight: f(FONT_SIZE.md) * 1.5 },
    bodySmall: { fontFamily, fontSize: f(FONT_SIZE.sm), fontWeight: FONT_WEIGHT.regular, lineHeight: f(FONT_SIZE.sm) * 1.45 },
    caption: { fontFamily, fontSize: f(FONT_SIZE.xs), fontWeight: FONT_WEIGHT.medium, lineHeight: f(FONT_SIZE.xs) * 1.4 },
    button: { fontFamily, fontSize: f(FONT_SIZE.md), fontWeight: FONT_WEIGHT.bold, lineHeight: f(FONT_SIZE.md) * 1.2 },
    label: { fontFamily, fontSize: f(FONT_SIZE.sm), fontWeight: FONT_WEIGHT.semibold, lineHeight: f(FONT_SIZE.sm) * 1.3 },
  };
}

/** Default (un-scaled, system-font) preset map for everyday screen use. */
export const typography = createTypography();
