// AUTO-GENERATED by Kiro Agent — Final Native Wiring & QA
// Status: 100% Completion Target
import { CameraView, useCameraPermissions } from 'expo-camera';
import { useCallback, useRef, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';

import { Button } from '@/components/ui';
import { captureAndIngest } from '@/features/ocr/services/ocrIngestion';
import { OcrNotAvailableError } from '@/features/ocr/services/textRecognition';
import type { OcrIngestResult } from '@/features/ocr/types/ocr.types';
import { colors, radii, spacing, typography } from '@/theme';

export interface CameraScannerProps {
  /** Subject tag stamped onto the ingested OCR chunks (helps RAG filtering). */
  subject?: string | null;
  /** Grade level stamped onto the ingested OCR chunks. */
  gradeLevel?: number | null;
  /** Invoked with the ingestion totals after a successful scan + ingest. */
  onIngested?: (result: OcrIngestResult) => void;
  /** Invoked when capture, recognition, or ingestion fails. */
  onError?: (error: Error) => void;
}

/**
 * Camera worksheet scanner (spec 5.5).
 *
 * Wires the native capture surface (expo-camera's modern `CameraView`) to the
 * OCR ingestion pipeline: take a photo, recognize its text on-device, and add
 * the result to the student's personal RAG layer so it becomes retrievable
 * grounding — fully offline.
 *
 * The component is permission-aware (renders a themed prompt until camera access
 * is granted) and degrades gracefully: if the device has no native OCR engine
 * (e.g. running inside Expo Go), the {@link OcrNotAvailableError} is caught and a
 * friendly message is surfaced instead of crashing.
 */
export function CameraScanner({
  subject = null,
  gradeLevel = null,
  onIngested,
  onError,
}: CameraScannerProps) {
  const [permission, requestPermission] = useCameraPermissions();
  const cameraRef = useRef<CameraView>(null);
  const [isCameraReady, setIsCameraReady] = useState(false);
  const [isRecognizing, setIsRecognizing] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  /** Capture a frame, recognize it, and ingest the text into personal RAG. */
  const handleCapture = useCallback(async () => {
    const camera = cameraRef.current;
    if (!camera || isRecognizing) {
      return;
    }

    setErrorMessage(null);
    setIsRecognizing(true);
    try {
      const photo = await camera.takePictureAsync({ quality: 0.8 });
      if (!photo?.uri) {
        throw new Error('Walang nakuhang larawan mula sa camera.');
      }

      const result = await captureAndIngest(photo.uri, {
        meta: { subject, gradeLevel },
      });
      onIngested?.(result);
    } catch (caught) {
      const error = caught instanceof Error ? caught : new Error(String(caught));
      if (error instanceof OcrNotAvailableError) {
        setErrorMessage(
          'Hindi available ang native OCR engine dito (halimbawa, kapag nasa Expo Go). ' +
            'Kailangan ng development o production build para mabasa ang teksto.',
        );
      } else {
        setErrorMessage('May naganap na problema habang kinikilala ang teksto. Pakisubukan muli.');
      }
      onError?.(error);
    } finally {
      setIsRecognizing(false);
    }
  }, [gradeLevel, isRecognizing, onError, onIngested, subject]);

  // Permission still resolving (null) or not yet granted -> themed prompt.
  if (!permission || !permission.granted) {
    const blocked = permission != null && !permission.canAskAgain;
    return (
      <View style={styles.promptContainer}>
        <Text style={styles.promptTitle}>I-scan ang Worksheet</Text>
        <Text style={styles.promptBody}>
          {blocked
            ? 'Naka-block ang camera. Pumunta sa Settings ng telepono para payagan ang access sa camera.'
            : 'Kailangan ng access sa camera para makunan at mabasa ang teksto ng iyong worksheet.'}
        </Text>
        <Button
          label="Payagan ang Camera"
          icon="camera"
          disabled={blocked}
          onPress={() => {
            void requestPermission();
          }}
        />
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <CameraView
        ref={cameraRef}
        style={StyleSheet.absoluteFill}
        facing="back"
        onCameraReady={() => setIsCameraReady(true)}
      />

      {errorMessage ? (
        <View style={styles.errorBanner} accessibilityLiveRegion="polite">
          <Text style={styles.errorText}>{errorMessage}</Text>
        </View>
      ) : null}

      <View style={styles.controls}>
        <Button
          label="I-scan ang Worksheet"
          icon="scan"
          loading={isRecognizing}
          disabled={!isCameraReady || isRecognizing}
          fullWidth
          onPress={() => {
            void handleCapture();
          }}
        />
      </View>

      {isRecognizing ? (
        <View style={styles.loadingOverlay} accessibilityLiveRegion="polite">
          <ActivityIndicator size="large" color={colors.accentPrimary} />
          <Text style={styles.loadingText}>Kinikilala ang teksto…</Text>
        </View>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    borderRadius: radii.lg,
    overflow: 'hidden',
  },
  promptContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.lg,
    padding: spacing.xl,
    backgroundColor: colors.background,
  },
  promptTitle: {
    ...typography.title,
    color: colors.textPrimary,
    textAlign: 'center',
  },
  promptBody: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  controls: {
    position: 'absolute',
    left: spacing.lg,
    right: spacing.lg,
    bottom: spacing.xl,
  },
  errorBanner: {
    position: 'absolute',
    top: spacing.lg,
    left: spacing.lg,
    right: spacing.lg,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    padding: spacing.md,
  },
  errorText: {
    ...typography.bodySmall,
    color: colors.danger,
    textAlign: 'center',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    backgroundColor: colors.overlay,
  },
  loadingText: {
    ...typography.title,
    color: colors.textPrimary,
  },
});
