// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — temperature is not part of routerCore.ProviderHandle, so cloud calls use streamOpenAICompatible's default
/**
 * Client-side cloud cascade — the ORDERED provider list plus the failover loop,
 * shared by the chat router (aiRouter.getProviders) and the single-shot generate
 * path (generate.generateWithPrompt) so the ordering lives in exactly ONE place.
 *
 * Order (spec 5.2): Gemini → Groq → OpenRouter, each included only when its
 * EXPO_PUBLIC_* key is set. The optional legacy server proxy is appended LAST so
 * existing proxy deployments keep working. With nothing configured the list is
 * empty and callers degrade to cache / the on-device SLM.
 *
 * Pure module (no React/native imports) — loads under headless verification.
 */
import type { ProviderHandle } from './routerCore';
import { createGeminiProvider } from './geminiClient';
import { createGroqProvider } from './groqClient';
import { createOpenRouterProvider } from './openRouterClient';
import { streamProxyResponse } from './cloudClient';
import { isProxyConfigured } from './providerConfig';

/**
 * The ordered cloud cascade for this build: the configured named providers
 * (Gemini → Groq → OpenRouter) followed by the optional server proxy. Returns an
 * empty array when nothing is configured.
 */
export function buildCloudProviders(): ProviderHandle[] {
  const providers = [
    createGeminiProvider(),
    createGroqProvider(),
    createOpenRouterProvider(),
  ].filter((p): p is ProviderHandle => p !== null);

  if (isProxyConfigured()) {
    providers.push(createProxyProvider());
  }
  return providers;
}

/** The legacy server-proxy handle (kept LAST in the cascade). */
function createProxyProvider(): ProviderHandle {
  return {
    id: 'proxy',
    stream: ({ system, user, maxTokens, onToken, signal }) =>
      streamProxyResponse({
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: user },
        ],
        maxTokens,
        onToken,
        signal,
      }),
  };
}

export interface CascadeArgs {
  system: string;
  user: string;
  maxTokens: number;
  onToken?: (token: string) => void;
  signal?: AbortSignal;
}

export interface CascadeResult {
  text: string;
  /** The provider id that served the response (e.g. 'gemini', 'proxy'). */
  source: string;
}

/**
 * Try each provider in order, returning the first success. Mirrors the failover
 * loop in routerCore.executeRoute: a caller-initiated abort stops the cascade and
 * rethrows; any other error fails over to the next provider. Throws when every
 * provider fails (or the list is empty) so the caller can degrade offline.
 */
export async function cascadeStream(
  providers: ProviderHandle[],
  args: CascadeArgs,
): Promise<CascadeResult> {
  let lastError: unknown;
  for (const provider of providers) {
    try {
      const text = await provider.stream(args);
      return { text, source: provider.id };
    } catch (err) {
      // Caller aborted: stop the cascade and surface it.
      if (args.signal?.aborted) {
        throw err;
      }
      // Otherwise fail over to the next provider.
      lastError = err;
    }
  }
  throw lastError instanceof Error
    ? lastError
    : new Error('No cloud provider available.');
}
