// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Reviewed — pinned to the stable 'gemini-2.5-flash' on the OpenAI-compat
//   endpoint ('gemini-3-flash-preview' was a non-served preview id that 404'd and
//   collapsed the whole cascade to the offline fallback).
/**
 * Gemini cloud provider — primary tier of the client-side cascade (spec 5.2).
 *
 * Streams directly from Google's OpenAI-compatible endpoint via the shared
 * streamOpenAICompatible transport and exposes a routerCore ProviderHandle, so
 * both the chat router (executeRoute) and the single-shot generate path fail
 * over to Groq → OpenRouter on any non-2xx (ProviderHttpError) or network error.
 *
 * Returns null when EXPO_PUBLIC_GEMINI_API_KEY is unset, so the cascade simply
 * skips this tier. Pure module — no native imports.
 */
import type { ProviderHandle } from './routerCore';
import { getGeminiKey } from './providerKeys';
import { streamOpenAICompatible } from './openaiStream';

const GEMINI_URL =
  'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions';
const GEMINI_MODEL = 'gemini-2.5-flash';

/** Build the Gemini ProviderHandle, or null when no key is configured. */
export function createGeminiProvider(): ProviderHandle | null {
  const apiKey = getGeminiKey();
  if (!apiKey) {
    return null;
  }

  const handle: ProviderHandle = {
    id: 'gemini',
    stream: ({ system, user, maxTokens, onToken, signal }) =>
      streamOpenAICompatible({
        url: GEMINI_URL,
        apiKey,
        model: GEMINI_MODEL,
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: user },
        ],
        maxTokens,
        onToken,
        signal,
      }),
  };
  return handle;
}
