// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — confirm 'llama-3.1-8b-instant' free-tier availability on Groq
/**
 * Groq cloud provider — fallback 1 of the client-side cascade (spec 5.2).
 *
 * Streams directly from Groq's OpenAI-compatible endpoint via the shared
 * streamOpenAICompatible transport and exposes a routerCore ProviderHandle, so
 * the cascade fails over here when Gemini errors, then on to OpenRouter on any
 * non-2xx (ProviderHttpError) or network error.
 *
 * Returns null when EXPO_PUBLIC_GROQ_API_KEY is unset, so the cascade simply
 * skips this tier. Pure module — no native imports.
 */
import type { ProviderHandle } from './routerCore';
import { getGroqKey } from './providerKeys';
import { streamOpenAICompatible } from './openaiStream';

const GROQ_URL = 'https://api.groq.com/openai/v1/chat/completions';
const GROQ_MODEL = 'llama-3.1-8b-instant';

/** Build the Groq ProviderHandle, or null when no key is configured. */
export function createGroqProvider(): ProviderHandle | null {
  const apiKey = getGroqKey();
  if (!apiKey) {
    return null;
  }

  const handle: ProviderHandle = {
    id: 'groq',
    stream: ({ system, user, maxTokens, onToken, signal }) =>
      streamOpenAICompatible({
        url: GROQ_URL,
        apiKey,
        model: GROQ_MODEL,
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: user },
        ],
        maxTokens,
        onToken,
        signal,
      }),
  };
  return handle;
}
