// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — setLocalModelRunner is re-exported from ./localModel (./offlineSLM only imports it, it does not re-export it)
/**
 * localModelClient — the spec's named handle for the Tier 3 on-device model.
 *
 * A thin named re-export so feature code can reach the offline runner and its
 * registration hooks from one "client" module, matching the named per-tier
 * client convention (geminiClient / groqClient / openRouterClient).
 *
 * Tier 3 is NOT a cloud provider: it stays invoked through routerCore's
 * deps.runLocalModel (wired in aiRouter.ts) and is deliberately ABSENT from the
 * cloud providers array — so nothing here is added to the cascade.
 *
 * Verified export sources (read from the source files):
 *   - runLocalModel, setLocalModelRunner  ←  ./localModel
 *   - maybeRegisterSLM                     ←  ./offlineSLM
 * (offlineSLM imports setLocalModelRunner from localModel; it does not re-export it.)
 */
export { runLocalModel, setLocalModelRunner } from './localModel';
export type { LocalModelParams, LocalModelRunner } from './localModel';
export { maybeRegisterSLM } from './offlineSLM';
