// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — confirm the 0.4 default temperature and 20s stall timeout suit every provider
/**
 * Reusable OpenAI-compatible Server-Sent-Events streamer.
 *
 * Extracted from cloudClient.streamProxyResponse so each named cloud provider
 * (Gemini, Groq, OpenRouter) can stream DIRECTLY with its own key + model while
 * sharing one battle-tested transport: the lazy expo/fetch resolution, the pure
 * SSEStreamParser, the timeout + abort wiring, and a typed ProviderHttpError on
 * any non-2xx — so the client-side cascade (routerCore.executeRoute and
 * generate.generateWithPrompt) fails over to the next provider.
 *
 * Unlike the proxy path, this sends the OpenAI `model` field in the body and a
 * plain `Authorization: Bearer <key>` (plus optional per-provider extraHeaders),
 * since it talks to the upstream provider directly.
 *
 * The fetch implementation is injectable (default: Expo's streaming-capable
 * `expo/fetch`, imported lazily) so this stays a pure module that loads cleanly
 * outside React Native — e.g. headless verification with a mock fetch.
 */
import { SSEStreamParser } from './sse';
import type { ChatMessage, FetchLike, StreamResponseLike } from './cloudClient';

// Re-export the shared transport types so the per-provider clients can depend on
// this module alone.
export type { ChatMessage, FetchLike, StreamResponseLike };

/** HTTP-level error from an upstream provider (carries the status for the cascade). */
export class ProviderHttpError extends Error {
  status: number;

  constructor(status: number, message: string) {
    super(message);
    this.name = 'ProviderHttpError';
    this.status = status;
  }
}

export interface StreamOpenAICompatibleOptions {
  /** Full OpenAI-compatible chat-completions URL. */
  url: string;
  /** Provider API key, sent as `Authorization: Bearer <apiKey>`. */
  apiKey: string;
  /** Provider model id. */
  model: string;
  messages: ChatMessage[];
  maxTokens?: number;
  temperature?: number;
  /** Extra per-provider headers (e.g. OpenRouter attribution). */
  extraHeaders?: Record<string, string>;
  onToken?: (token: string) => void;
  signal?: AbortSignal;
  /** Abort if the request stalls this long (ms). Default 20s. */
  timeoutMs?: number;
  /** Override the fetch implementation (default: expo/fetch). */
  fetchImpl?: FetchLike;
}

/** Suri's house default — matches the proxy + on-device SLM so tone is consistent. */
const DEFAULT_TEMPERATURE = 0.4;
const DEFAULT_TIMEOUT_MS = 20000;

/**
 * Stream a chat completion from an OpenAI-compatible endpoint, invoking onToken
 * for each delta and resolving with the full concatenated text.
 *
 * @throws ProviderHttpError on a non-2xx response (so the cascade fails over).
 */
export async function streamOpenAICompatible(
  opts: StreamOpenAICompatibleOptions,
): Promise<string> {
  const {
    url,
    apiKey,
    model,
    messages,
    maxTokens,
    temperature,
    extraHeaders,
    onToken,
    signal,
    timeoutMs = DEFAULT_TIMEOUT_MS,
  } = opts;

  const fetchImpl = opts.fetchImpl ?? (await resolveDefaultFetch());

  const controller = new AbortController();
  const abortFromCaller = () => controller.abort();
  if (signal) {
    if (signal.aborted) {
      controller.abort();
    } else {
      signal.addEventListener('abort', abortFromCaller);
    }
  }
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetchImpl(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'text/event-stream',
        Authorization: `Bearer ${apiKey}`,
        ...(extraHeaders ?? {}),
      },
      body: JSON.stringify({
        model,
        messages,
        stream: true,
        max_tokens: maxTokens,
        temperature: temperature ?? DEFAULT_TEMPERATURE,
      }),
      signal: controller.signal,
    });

    if (!response.ok) {
      let detail = '';
      try {
        detail = await response.text();
      } catch {
        // ignore secondary failure reading the error body
      }
      throw new ProviderHttpError(
        response.status,
        `Provider HTTP ${response.status} ${response.statusText ?? ''} ${truncate(detail)}`.trim(),
      );
    }
    if (!response.body) {
      throw new Error('Streaming not supported: provider response body is null.');
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    const parser = new SSEStreamParser();
    let full = '';

    for (;;) {
      const { value, done } = await reader.read();
      if (done) {
        break;
      }
      if (!value) {
        continue;
      }
      const text = decoder.decode(value, { stream: true });
      let streamEnded = false;
      for (const event of parser.push(text)) {
        if (event.type === 'done') {
          streamEnded = true;
          break;
        }
        full += event.value;
        onToken?.(event.value);
      }
      if (streamEnded) {
        break;
      }
    }

    for (const event of parser.flush()) {
      if (event.type === 'token') {
        full += event.value;
        onToken?.(event.value);
      }
    }

    return full;
  } finally {
    clearTimeout(timeout);
    if (signal) {
      signal.removeEventListener('abort', abortFromCaller);
    }
  }
}

async function resolveDefaultFetch(): Promise<FetchLike> {
  // Expo's streaming-capable fetch. Lazy import keeps this module loadable
  // outside React Native (verification injects its own fetch).
  const mod = (await import('expo/fetch')) as unknown as { fetch: FetchLike };
  return mod.fetch;
}

function truncate(value: string, max = 200): string {
  return value.length > max ? `${value.slice(0, max)}…` : value;
}
