// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — confirm 'openai/gpt-oss-20b:free' is still a free OpenRouter pool
/**
 * OpenRouter cloud provider — fallback 2 of the client-side cascade (spec 5.2).
 *
 * Streams directly from OpenRouter's OpenAI-compatible endpoint via the shared
 * streamOpenAICompatible transport and exposes a routerCore ProviderHandle, so
 * the cascade fails over here when Gemini and Groq both error. OpenRouter asks
 * free-tier traffic to send attribution headers (HTTP-Referer / X-Title), passed
 * via extraHeaders. A non-2xx (ProviderHttpError) leaves the cascade to degrade
 * to cache / the on-device SLM.
 *
 * Returns null when EXPO_PUBLIC_OPENROUTER_API_KEY is unset, so the cascade
 * simply skips this tier. Pure module — no native imports.
 */
import type { ProviderHandle } from './routerCore';
import { getOpenRouterKey } from './providerKeys';
import { streamOpenAICompatible } from './openaiStream';

const OPENROUTER_URL = 'https://openrouter.ai/api/v1/chat/completions';
const OPENROUTER_MODEL = 'openai/gpt-oss-20b:free';
const OPENROUTER_HEADERS: Record<string, string> = {
  'HTTP-Referer': 'https://suri.app',
  'X-Title': 'Suri',
};

/** Build the OpenRouter ProviderHandle, or null when no key is configured. */
export function createOpenRouterProvider(): ProviderHandle | null {
  const apiKey = getOpenRouterKey();
  if (!apiKey) {
    return null;
  }

  const handle: ProviderHandle = {
    id: 'openrouter',
    stream: ({ system, user, maxTokens, onToken, signal }) =>
      streamOpenAICompatible({
        url: OPENROUTER_URL,
        apiKey,
        model: OPENROUTER_MODEL,
        extraHeaders: OPENROUTER_HEADERS,
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: user },
        ],
        maxTokens,
        onToken,
        signal,
      }),
  };
  return handle;
}
