// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — EXPO_PUBLIC_* keys are inlined into the JS bundle (visible in the APK)
/**
 * Per-provider API key accessors for the client-side cloud cascade.
 *
 * Each key is read through a STATIC `process.env.EXPO_PUBLIC_*` member access so
 * Metro inlines the literal at build time. A dynamic lookup (e.g. bracket access
 * with a computed name) would NOT be replaced and would resolve to undefined
 * on-device, so the accessors below intentionally hard-code each name.
 *
 * ── SECURITY ─────────────────────────────────────────────────────────────────
 * EXPO_PUBLIC_* values are inlined into the JS bundle, so these keys ARE visible
 * in the shipped APK. That is an accepted tradeoff for FREE-tier provider keys
 * per the current project decision; the server proxy (providerConfig.ts) remains
 * the safer path for any billable key. Do NOT place paid/secret keys here.
 *
 * Pure module — no native imports — so the router and its headless verifiers
 * load cleanly. Mirrors the normalize() pattern in providerConfig.ts.
 */

/** Trim and treat empty strings as absent (mirrors providerConfig.normalize). */
function normalize(value: string | undefined): string | null {
  if (typeof value !== 'string') {
    return null;
  }
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

/** Google Gemini (OpenAI-compatible endpoint) key, or null when unset. */
export function getGeminiKey(): string | null {
  return normalize(process.env.EXPO_PUBLIC_GEMINI_API_KEY);
}

/** Groq key, or null when unset. */
export function getGroqKey(): string | null {
  return normalize(process.env.EXPO_PUBLIC_GROQ_API_KEY);
}

/** OpenRouter key, or null when unset. */
export function getOpenRouterKey(): string | null {
  return normalize(process.env.EXPO_PUBLIC_OPENROUTER_API_KEY);
}

/** Whether the Gemini tier is configured in this build. */
export function isGeminiConfigured(): boolean {
  return getGeminiKey() !== null;
}

/** Whether the Groq tier is configured in this build. */
export function isGroqConfigured(): boolean {
  return getGroqKey() !== null;
}

/** Whether the OpenRouter tier is configured in this build. */
export function isOpenRouterConfigured(): boolean {
  return getOpenRouterKey() !== null;
}
