// AUTO-GENERATED by Kiro Agent — Backend Wiring & Dev Tools
/**
 * useNetworkStatus — a React hook exposing the device's live network tier plus
 * the developer force-offline override, so UI (e.g. the chat "Local Mode" badge)
 * can reflect real connectivity immediately rather than only after a request.
 *
 * It seeds the tier with a one-shot getNetworkTier() read on mount, then stays
 * in sync via subscribeNetworkTier (which already honors force-offline) and
 * subscribeForceOffline. All state updates are guarded so nothing fires after
 * the component unmounts, and both subscriptions are torn down on cleanup.
 */
import { useEffect, useState } from 'react';

import {
  getNetworkTier,
  isForceOffline,
  subscribeForceOffline,
  subscribeNetworkTier,
  type NetworkTier,
} from './networkTier';

export function useNetworkStatus(): {
  tier: NetworkTier;
  isOffline: boolean;
  forceOffline: boolean;
} {
  const [tier, setTier] = useState<NetworkTier>('strong');
  const [forceOffline, setForceOffline] = useState<boolean>(isForceOffline());

  useEffect(() => {
    let mounted = true;

    // Seed the tier with a one-shot read, guarding against late resolution.
    void getNetworkTier().then((initialTier) => {
      if (mounted) {
        setTier(initialTier);
      }
    });

    // Live updates: tier (honors force-offline) and the override flag itself.
    const unsubscribeTier = subscribeNetworkTier((nextTier) => {
      if (mounted) {
        setTier(nextTier);
      }
    });
    const unsubscribeForceOffline = subscribeForceOffline((value) => {
      if (mounted) {
        setForceOffline(value);
      }
    });

    return () => {
      mounted = false;
      unsubscribeTier();
      unsubscribeForceOffline();
    };
  }, []);

  return {
    tier,
    isOffline: tier === 'offline',
    forceOffline,
  };
}
