// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — 6-tab bottom navigator per spec 7 (Kasabay is the default tab).
import { Ionicons } from '@expo/vector-icons';
import { Tabs } from 'expo-router';

import { FloatingTabBar } from '@/navigation/FloatingTabBar';
import { TabBarVisibilityProvider } from '@/navigation/tabBarVisibility';
import { colors } from '@/theme';

/**
 * Bottom tab navigator (spec 7): Kasabay | Tanong | Kwento | Review | Quizzes |
 * Profile, in that exact order. Kasabay is the index route so the app opens to
 * the virtual study desk.
 *
 * The flush bar was replaced by a floating, rounded <FloatingTabBar/> that hides
 * on downward scroll (Phase 1). The navigator still owns each tab's icon/title
 * options; the custom bar simply renders them. Wrapping in
 * <TabBarVisibilityProvider/> shares one scroll-driven shared value between the
 * bar and every screen.
 */
export default function TabsLayout() {
  return (
    <TabBarVisibilityProvider>
      <Tabs
        tabBar={(props) => <FloatingTabBar {...props} />}
        screenOptions={{
          headerShown: false,
          sceneStyle: { backgroundColor: colors.background },
        }}
      >
        <Tabs.Screen
          name="index"
          options={{
            title: 'Kasabay',
            tabBarIcon: ({ color, size, focused }) => (
              <Ionicons name={focused ? 'cafe' : 'cafe-outline'} size={size} color={color} />
            ),
          }}
        />
        <Tabs.Screen
          name="tanong"
          options={{
            title: 'Tanong',
            tabBarIcon: ({ color, size, focused }) => (
              <Ionicons
                name={focused ? 'chatbubble-ellipses' : 'chatbubble-ellipses-outline'}
                size={size}
                color={color}
              />
            ),
          }}
        />
        <Tabs.Screen
          name="kwento"
          options={{
            title: 'Kwento',
            tabBarIcon: ({ color, size, focused }) => (
              <Ionicons name={focused ? 'book' : 'book-outline'} size={size} color={color} />
            ),
          }}
        />
        <Tabs.Screen
          name="review"
          options={{
            title: 'Review',
            tabBarIcon: ({ color, size, focused }) => (
              <Ionicons name={focused ? 'documents' : 'documents-outline'} size={size} color={color} />
            ),
          }}
        />
        <Tabs.Screen
          name="quizzes"
          options={{
            title: 'Quizzes',
            tabBarIcon: ({ color, size, focused }) => (
              <Ionicons name={focused ? 'clipboard' : 'clipboard-outline'} size={size} color={color} />
            ),
          }}
        />
        <Tabs.Screen
          name="profile"
          options={{
            title: 'Profile',
            tabBarIcon: ({ color, size, focused }) => (
              <Ionicons
                name={focused ? 'person-circle' : 'person-circle-outline'}
                size={size}
                color={color}
              />
            ),
          }}
        />
      </Tabs>
    </TabBarVisibilityProvider>
  );
}
