// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — Kasabay Mode study desk; streams Suri's reply via generateWithPrompt.
import { useCallback, useEffect, useRef, useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  StyleSheet,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { generateWithPrompt } from '@/ai/generate';
import { Button, Card, ThemedText } from '@/components/ui';
import { InterruptButton } from '@/features/kasabay/components/InterruptButton';
import { StudyTimer } from '@/features/kasabay/components/StudyTimer';
import { SuriDeskCanvas } from '@/features/kasabay/components/SuriDeskCanvas';
import { KASABAY_THEME } from '@/features/kasabay/constants/kasabayTheme';
import { buildKasabayPrompt } from '@/features/kasabay/services/kasabayPromptBuilder';
import { recordStudySession } from '@/gamification/streakService';
import { TAB_BAR_CLEARANCE } from '@/navigation/tabBarVisibility';
import { useProfile } from '@/profile/useProfile';
import { colors, radii, spacing, typography } from '@/theme';

const FOCUS_BLOCK_MINUTES = 25;

/**
 * Kasabay Mode (spec 5.10): the virtual study desk. Suri "studies" alongside the
 * student during a focus block. Tapping "Stuck ka ba?" pauses the timer and opens
 * a quick ask box; Suri's reply streams into a card, after which the student can
 * resume the block. Honours the profile's reduce-motion and focus-mode settings.
 */
export default function KasabayModeScreen() {
  const { profile } = useProfile();
  const lowMotion = profile.accessibilitySettings.lowMotion;
  const focusMode = profile.accessibilitySettings.focusMode;

  const [running, setRunning] = useState(false);
  const [asking, setAsking] = useState(false);
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [loading, setLoading] = useState(false);
  // Last topic studied together — feeds the prompt's memory line on the next ask.
  const [lastTopic, setLastTopic] = useState<string | undefined>(undefined);

  const abortRef = useRef<AbortController | null>(null);

  // Abort any in-flight stream if the screen unmounts.
  useEffect(() => () => abortRef.current?.abort(), []);

  // Focus mode (spec 5.6): hint Suri to keep replies short and direct.
  const cognitiveModifier = focusMode ? 'Focused — keep replies short and direct' : 'Neutral / focused';

  const handleComplete = useCallback(() => {
    setRunning(false);
    // Best-effort streak credit for the completed focus block (spec 5.9).
    void recordStudySession().catch(() => undefined);
  }, []);

  const handleInterrupt = useCallback(() => {
    setRunning(false);
    setAsking(true);
    setAnswer('');
  }, []);

  const handleSend = useCallback(async () => {
    const studentQuestion = question.trim();
    if (studentQuestion.length === 0 || loading) {
      return;
    }

    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    setLoading(true);
    setAnswer('');

    try {
      const { system, user } = buildKasabayPrompt({
        studentQuestion,
        cognitiveModifier,
        lastTopicDiscussed: lastTopic,
      });
      const result = await generateWithPrompt({
        system,
        user,
        signal: controller.signal,
        onToken: (token) => setAnswer((prev) => prev + token),
      });
      if (!controller.signal.aborted) {
        setAnswer(result.text.trim());
      }
    } catch {
      if (!controller.signal.aborted) {
        setAnswer("Pasensya na, hindi ako maka-connect ngayon. Subukan natin ulit mamaya?");
      }
    } finally {
      if (abortRef.current === controller) {
        setLoading(false);
      }
    }
  }, [question, loading, cognitiveModifier, lastTopic]);

  const handleResume = useCallback(() => {
    abortRef.current?.abort();
    const asked = question.trim();
    if (asked.length > 0) {
      setLastTopic(asked);
    }
    setAsking(false);
    setLoading(false);
    setQuestion('');
    setAnswer('');
    setRunning(true);
  }, [question]);

  const showAnswer = loading || answer.length > 0;

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <View style={styles.canvasWrap}>
        <SuriDeskCanvas lowMotion={lowMotion} />
      </View>

      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={styles.panel}
      >
        <StudyTimer
          durationMinutes={FOCUS_BLOCK_MINUTES}
          running={running}
          onComplete={handleComplete}
        />

        {asking ? (
          <View style={styles.stack}>
            <TextInput
              style={styles.input}
              value={question}
              onChangeText={setQuestion}
              placeholder="Itanong mo kay Suri..."
              placeholderTextColor={colors.textMuted}
              multiline
              editable={!loading}
            />
            <Button
              label="Itanong"
              icon="send"
              variant="primary"
              fullWidth
              loading={loading}
              disabled={loading || question.trim().length === 0}
              onPress={handleSend}
            />

            {showAnswer ? (
              <Card neon>
                {loading && answer.length === 0 ? (
                  <View style={styles.answerLoading}>
                    <ActivityIndicator color={colors.accentPrimary} />
                    <ThemedText variant="bodySmall" color={colors.textSecondary}>
                      Iniisip ni Suri...
                    </ThemedText>
                  </View>
                ) : (
                  <ScrollView style={styles.answerScroll}>
                    <ThemedText variant="body">{answer}</ThemedText>
                  </ScrollView>
                )}
              </Card>
            ) : null}

            <Button
              label="Ituloy ang timer"
              icon="play"
              variant="outline"
              fullWidth
              onPress={handleResume}
            />
          </View>
        ) : (
          <View style={styles.stack}>
            <Button
              label={running ? 'I-pause' : 'Simulan ang focus'}
              icon={running ? 'pause' : 'play'}
              variant="primary"
              fullWidth
              onPress={() => setRunning((prev) => !prev)}
            />
            <InterruptButton onPress={handleInterrupt} />
            {focusMode ? (
              <ThemedText variant="caption" color={KASABAY_THEME.textMuted} center>
                Focus mode: panatilihing maikli ang mga sagot ni Suri.
              </ThemedText>
            ) : null}
          </View>
        )}
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: KASABAY_THEME.canvas,
  },
  canvasWrap: {
    flex: 1,
  },
  panel: {
    backgroundColor: KASABAY_THEME.canvas,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
    // Clear the floating tab bar so the focus/interrupt buttons stay tappable.
    paddingBottom: TAB_BAR_CLEARANCE,
    gap: spacing.lg,
  },
  stack: {
    gap: spacing.md,
  },
  input: {
    minHeight: 52,
    maxHeight: 120,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    color: colors.textPrimary,
    ...typography.body,
  },
  answerScroll: {
    maxHeight: 220,
  },
  answerLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
});
