// AUTO-GENERATED by Kiro Agent — STRICT UI PORT
// Visual Reference: zip(4).zip | Backend: Existing Suri Services
// Status: Needs review — NO Kwento screen exists in zip(4).zip; layout derived
//   from the shared design system (not invented freely). Provide a Kwento design
//   (e.g. from hih.zip mockups) to port 1:1. Backend is the complete useKwentoMode.
import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, TextInput, View } from 'react-native';

import { Button, Card, Screen, ThemedText } from '@/components/ui';
import {
  CULTURAL_SETTINGS,
  CULTURAL_SETTING_IDS,
} from '@/features/kwento-mode/constants/culturalSettings';
import { useKwentoMode } from '@/features/kwento-mode/hooks/useKwentoMode';
import type { KwentoCulturalSetting } from '@/features/kwento-mode/types/kwento.types';
import { useTabBarScroll } from '@/navigation/tabBarVisibility';
import { useProfile } from '@/profile/useProfile';
import { colors, radii, spacing } from '@/theme';

/**
 * Kwento Mode tab (spec 5.8). Wires the already-complete useKwentoMode hook:
 * pick a topic + optional cultural setting, generate a Filipino-context story
 * with an embedded problem, then answer/hint/solution with adaptive difficulty.
 *
 * NOTE: zip(4).zip ships no Kwento screen, so this layout uses the shared UI kit
 * for visual consistency rather than a 1:1 prototype port.
 */
export default function KwentoScreen() {
  const { profile } = useProfile();
  const tabBarScroll = useTabBarScroll();
  const [topic, setTopic] = useState(profile.subject ?? '');
  const [setting, setSetting] = useState<KwentoCulturalSetting | undefined>(undefined);

  const kwentoMode = useKwentoMode({
    profile,
    languagePreference: profile.languagePreference,
    melcTopic: topic.trim() || undefined,
  });

  const {
    kwento,
    isLoading,
    phase,
    error,
    hintUsed,
    solutionRevealed,
    misconception,
    generateNew,
    submitAnswer,
    revealHint,
    revealSolution,
    reset,
  } = kwentoMode;

  const [answer, setAnswer] = useState('');

  const canGenerate = topic.trim().length > 0 && !isLoading;

  const handleGenerate = () => {
    setAnswer('');
    void generateNew({ melcTopic: topic.trim(), culturalSetting: setting });
  };

  const handleSubmit = () => {
    if (answer.trim().length === 0) {
      return;
    }
    void submitAnswer(answer.trim());
  };

  return (
    <Screen scroll tabBarClearance onScroll={tabBarScroll.onScroll} scrollEventThrottle={tabBarScroll.scrollEventThrottle}>
      <ThemedText variant="h1">Kwento</ThemedText>
      <ThemedText variant="body" color={colors.textSecondary} style={styles.intro}>
        Mga kwentong Pilipino na may nakatagong aralin.
      </ThemedText>

      {/* Topic + setting picker (shown when idle / before a story exists). */}
      {!kwento || phase === 'idle' ? (
        <Card style={styles.block}>
          <ThemedText variant="label" color={colors.textSecondary}>
            Paksa (MELC topic)
          </ThemedText>
          <TextInput
            style={styles.input}
            value={topic}
            onChangeText={setTopic}
            placeholder="hal. Fractions, Photosynthesis"
            placeholderTextColor={colors.textMuted}
          />

          <ThemedText variant="label" color={colors.textSecondary} style={styles.settingLabel}>
            Lugar (opsyonal)
          </ThemedText>
          <View style={styles.chips}>
            {CULTURAL_SETTING_IDS.map((id) => {
              const selected = id === setting;
              return (
                <Pressable
                  key={id}
                  onPress={() => setSetting(selected ? undefined : id)}
                  accessibilityRole="button"
                  accessibilityState={{ selected }}
                  style={[styles.chip, selected && [styles.chipSelected, { backgroundColor: colors.accentPrimary, borderColor: colors.accentPrimary }]]}
                >
                  <ThemedText
                    variant="caption"
                    color={selected ? colors.textOnAccent : colors.textSecondary}
                  >
                    {CULTURAL_SETTINGS[id].name}
                  </ThemedText>
                </Pressable>
              );
            })}
          </View>

          <Button
            label="Bumuo ng Kwento"
            icon="sparkles"
            onPress={handleGenerate}
            loading={isLoading}
            disabled={!canGenerate}
            fullWidth
            style={styles.generateBtn}
          />
        </Card>
      ) : null}

      {isLoading ? (
        <View style={styles.center}>
          <ActivityIndicator size="large" color={colors.accentPrimary} />
          <ThemedText variant="bodySmall" color={colors.textSecondary} style={styles.loadingText}>
            Gumagawa ng kwento si Suri...
          </ThemedText>
        </View>
      ) : null}

      {error ? (
        <Card style={styles.block}>
          <ThemedText variant="body" color={colors.danger}>
            Hindi makabuo ng kwento. Subukan muli.
          </ThemedText>
        </Card>
      ) : null}

      {/* Story + problem. */}
      {kwento && !isLoading ? (
        <View style={styles.storyStack}>
          {/* StoryCard */}
          <Card neon style={styles.block}>
            <View style={styles.badges}>
              <View style={styles.badge}>
                <Ionicons name="location" size={12} color={colors.accentPrimary} />
                <ThemedText variant="caption" color={colors.accentPrimary}>
                  {CULTURAL_SETTINGS[kwento.setting]?.name ?? kwento.setting}
                </ThemedText>
              </View>
              <View style={styles.badge}>
                <ThemedText variant="caption" color={colors.accentSecondary}>
                  {kwento.difficulty.toUpperCase()}
                </ThemedText>
              </View>
            </View>
            <ThemedText variant="body" style={styles.storyText}>
              {kwento.kwento}
            </ThemedText>
          </Card>

          {/* ProblemBlock */}
          <Card style={styles.block}>
            <ThemedText variant="title">Tanong</ThemedText>
            <ThemedText variant="body" color={colors.textSecondary} style={styles.tanong}>
              {kwento.tanong}
            </ThemedText>
            <TextInput
              style={styles.input}
              value={answer}
              onChangeText={setAnswer}
              placeholder="Isulat ang iyong sagot..."
              placeholderTextColor={colors.textMuted}
              editable={phase !== 'checking'}
            />
            <Button
              label="Isumite"
              icon="checkmark"
              onPress={handleSubmit}
              loading={phase === 'checking'}
              disabled={answer.trim().length === 0 || phase === 'checking'}
              fullWidth
              style={styles.generateBtn}
            />
          </Card>

          {/* HintReveal */}
          <Pressable onPress={revealHint} accessibilityRole="button">
            <Card style={styles.block}>
              <View style={styles.revealHeader}>
                <Ionicons name="bulb-outline" size={18} color={colors.accentSecondary} />
                <ThemedText variant="label" color={colors.accentSecondary}>
                  {hintUsed ? 'Pahiwatig' : 'Ipakita ang pahiwatig'}
                </ThemedText>
              </View>
              {hintUsed ? (
                <ThemedText variant="bodySmall" color={colors.textSecondary} style={styles.tanong}>
                  {kwento.hint}
                </ThemedText>
              ) : null}
            </Card>
          </Pressable>

          {/* Phase feedback */}
          {phase === 'correct' ? (
            <Card style={[styles.block, styles.correct, { borderColor: colors.accentSecondary }]}>
              <ThemedText variant="title" color={colors.accentSecondary}>
                Tama! Magaling! 🎉
              </ThemedText>
              {kwento.follow_up ? (
                <ThemedText variant="bodySmall" color={colors.textSecondary} style={styles.tanong}>
                  {kwento.follow_up}
                </ThemedText>
              ) : null}
              <Button label="Susunod na kwento" icon="arrow-forward" onPress={handleGenerate} fullWidth style={styles.generateBtn} />
            </Card>
          ) : null}

          {phase === 'misconception' && misconception?.explanation ? (
            <Card style={[styles.block, styles.misconception, { borderColor: colors.warning }]}>
              <ThemedText variant="label" color={colors.warning}>
                Tingnan natin muli
              </ThemedText>
              <ThemedText variant="bodySmall" color={colors.textSecondary} style={styles.tanong}>
                {misconception.explanation}
              </ThemedText>
            </Card>
          ) : null}

          {/* SolutionReveal (offered after a wrong attempt or a detected misconception) */}
          {phase === 'wrong' || phase === 'misconception' ? (
            <Pressable onPress={revealSolution} accessibilityRole="button">
              <Card style={styles.block}>
                <View style={styles.revealHeader}>
                  <Ionicons name="school-outline" size={18} color={colors.accentPrimary} />
                  <ThemedText variant="label" color={colors.accentPrimary}>
                    {solutionRevealed ? 'Solusyon' : 'Ipakita ang solusyon'}
                  </ThemedText>
                </View>
                {solutionRevealed ? (
                  <ThemedText variant="bodySmall" color={colors.textSecondary} style={styles.tanong}>
                    {kwento.suliranin_sagot}
                  </ThemedText>
                ) : null}
              </Card>
            </Pressable>
          ) : null}

          <Button label="Bagong paksa" variant="ghost" onPress={reset} fullWidth />
        </View>
      ) : null}
    </Screen>
  );
}

const styles = StyleSheet.create({
  intro: { marginTop: spacing.xs, marginBottom: spacing.lg },
  block: { marginBottom: spacing.lg },
  input: {
    marginTop: spacing.sm,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    color: colors.textPrimary,
    minHeight: 48,
  },
  settingLabel: { marginTop: spacing.lg },
  chips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  chip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipSelected: {
    backgroundColor: colors.accentPrimary,
    borderColor: colors.accentPrimary,
  },
  generateBtn: { marginTop: spacing.lg },
  center: { alignItems: 'center', justifyContent: 'center', paddingVertical: spacing.xxl, gap: spacing.md },
  loadingText: { marginTop: spacing.sm },
  storyStack: { gap: 0 },
  badges: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radii.pill,
  },
  storyText: { lineHeight: 26 },
  tanong: { marginTop: spacing.sm },
  revealHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  correct: { borderColor: colors.accentSecondary, borderWidth: 1.5 },
  misconception: { borderColor: colors.warning, borderWidth: 1.5 },
});
