// AUTO-GENERATED by Kiro Agent — STRICT UI PORT
// Visual Reference: zip(4).zip | Backend: Existing Suri Services
// Status: Needs review
import { Ionicons } from '@expo/vector-icons';
import { Image, Pressable, ScrollView, StyleSheet, Switch, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/ui';
import { DevTools } from '@/features/dev/DevMenu';
import { useStreaks } from '@/gamification/useStreaks';
import { useTabBarScroll } from '@/navigation/tabBarVisibility';
import {
  COLOR_VISION_MODES,
  RESPONSE_MODES,
  type AccessibilitySettings,
  type ColorVisionMode,
  type LanguagePreference,
  type ResponseMode,
} from '@/profile/types';
import { useProfile } from '@/profile/useProfile';
import { colors, FONT_WEIGHT, radii, spacing } from '@/theme';

/** Boolean comfort settings (everything except the colorVision selector). */
type ToggleKey = Exclude<keyof AccessibilitySettings, 'colorVision'>;

interface ToggleRow {
  readonly key: ToggleKey;
  readonly label: string;
  readonly description: string;
}

/**
 * Accessibility list rows, labeled by EFFECT never by condition (spec 5.6).
 * Reuses the prototype's toggle-row template for our six real comfort settings.
 */
const TOGGLES: readonly ToggleRow[] = [
  { key: 'readerFont', label: 'Reader Font', description: 'Gamitin ang OpenDyslexic font' },
  { key: 'highContrast', label: 'High Contrast', description: 'Dagdagan ang kaibahan ng mga kulay' },
  { key: 'largeText', label: 'Larger Text', description: 'Palakihin ang lahat ng teksto' },
  { key: 'focusMode', label: 'Focus Mode', description: 'Bawasan ang mga abala sa screen' },
  { key: 'lowMotion', label: 'Reduce Motion', description: 'Pigilan ang mga animations' },
];

const COLOR_VISION_LABEL: Record<ColorVisionMode, string> = {
  standard: 'Standard',
  deuteranopia: 'Deuteranopia',
  protanopia: 'Protanopia',
  tritanopia: 'Tritanopia',
};

/** "Paraan ng Pagpapaliwanag" segmented control — one segment per response mode. */
const RESPONSE_MODE_LABEL: Record<ResponseMode, string> = {
  visual: 'Visual',
  auditory: 'Boses',
  reading: 'Teksto',
  kinesthetic: 'Galaw',
  mixed: 'Mixed',
};

const LANGUAGE_LABEL: Record<LanguagePreference, string> = {
  tagalog: 'Tagalog',
  taglish: 'Taglish',
  english: 'English',
};

/** Avatar placeholder occupying the same 80x80 circular slot as the prototype mascot. */
const AVATAR_PLACEHOLDER_URI =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBqwqGB5DmpaF6AyNLDmewaRbkTsB776lWri3eWRBHVjfZYQhSBy3jxePTMfwfLRvwDjOZjG-3QPVscbbMEQtneJfuwbJDSykE_PVQSTfApfWWnD9MyyWPaD08BuRNXDh7jP9dln1sA_nbt6VCXhaWcOaTBHL6rIHaGl94ujywV1sn9FNiUcaHcDaJ-j27pZ4Z_Ixy10HpmfSdZCezviiZT26fQ3AFw9vfWa5p2rVmQf4AgD7LzIskedLHAQj5EGqvW8c_FpBVpN_A';

/**
 * Profile tab ("Ako"). Strict 1:1 port of the web prototype's Settings view,
 * recolored to the dark "Tambayan" palette. Wires the live Learning Profile
 * (response mode + the six accessibility comfort settings) and surfaces streak +
 * badge progress in the profile header.
 */
export default function ProfileScreen() {
  const { profile, update, updateAccessibility, reset } = useProfile();
  const { streak, badges } = useStreaks();
  const tabBarScroll = useTabBarScroll();

  const settings = profile.accessibilitySettings;
  const currentStreak = streak?.currentStreak ?? 0;
  const earnedBadges = badges.filter((badge) => badge.earnedAt !== null).length;

  const summaryParts: string[] = [`Grade ${profile.gradeLevel}`];
  if (profile.subject) {
    summaryParts.push(profile.subject);
  }
  summaryParts.push(LANGUAGE_LABEL[profile.languagePreference]);
  const summary = `Mag-aaral: ${summaryParts.join('  •  ')}`;

  const setToggle = <K extends ToggleKey>(key: K, value: boolean): void => {
    void updateAccessibility({ [key]: value } as Pick<AccessibilitySettings, K>);
  };

  const cycleColorVision = (): void => {
    const index = COLOR_VISION_MODES.indexOf(settings.colorVision);
    const next = COLOR_VISION_MODES[(index + 1) % COLOR_VISION_MODES.length];
    void updateAccessibility({ colorVision: next });
  };

  const selectResponseMode = (mode: ResponseMode): void => {
    if (mode !== profile.responseMode) {
      void update({ responseMode: mode });
    }
  };

  return (
    <SafeAreaView edges={['top']} style={styles.safe}>
      {/* TopBar -> in-screen header (back button omitted: this is a tab root). */}
      <View style={styles.header}>
        <View style={styles.headerSpacer} />
        <ThemedText
          variant="title"
          color={colors.accentPrimary}
          center
          style={[styles.headerTitle, styles.bold]}
        >
          Ako
        </ThemedText>
        <View style={styles.headerSpacer} />
      </View>

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        onScroll={tabBarScroll.onScroll}
        scrollEventThrottle={tabBarScroll.scrollEventThrottle}
      >
        {/* Page Header */}
        <View style={styles.pageHeader}>
          <View style={styles.avatarWrap}>
            <Image
              source={{ uri: AVATAR_PLACEHOLDER_URI }}
              style={styles.avatarImage}
              resizeMode="cover"
            />
          </View>
          <View style={styles.pageHeaderInfo}>
            <ThemedText variant="h1" style={styles.extrabold}>
              Mga Setting
            </ThemedText>
            <ThemedText variant="bodySmall" color={colors.textSecondary} style={styles.summary}>
              {summary}
            </ThemedText>
            <View style={styles.statRow}>
              <View style={styles.stat}>
                <Ionicons name="flame" size={16} color={colors.accentPrimary} />
                <ThemedText variant="caption" color={colors.accentPrimary}>
                  {currentStreak}-araw na streak
                </ThemedText>
              </View>
              <View style={styles.stat}>
                <Ionicons name="ribbon" size={16} color={colors.accentPrimary} />
                <ThemedText variant="caption" color={colors.accentPrimary}>
                  {earnedBadges} badge
                </ThemedText>
              </View>
            </View>
          </View>
        </View>

        {/* Sync Action (visual; remote sync is not part of the offline-first MVP). */}
        <Pressable style={styles.syncButton} accessibilityRole="button" onPress={() => {}}>
          <ThemedText variant="button" color={colors.accentPrimary}>
            I-sync ang Progress
          </ThemedText>
          <Ionicons name="chevron-forward" size={20} color={colors.accentPrimary} />
        </Pressable>

        {/* Group 1: Paraan ng Pagpapaliwanag (response mode) */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <ThemedText variant="title" style={styles.bold}>
              Paraan ng Pagpapaliwanag
            </ThemedText>
            <ThemedText variant="caption" color={colors.textSecondary} style={styles.sectionSubtitle}>
              Paano mo gustong matuto?
            </ThemedText>
          </View>
          <View style={styles.sectionBody}>
            <View style={styles.segmented}>
              {RESPONSE_MODES.map((mode) => {
                const active = profile.responseMode === mode;
                return (
                  <Pressable
                    key={mode}
                    accessibilityRole="button"
                    accessibilityState={{ selected: active }}
                    onPress={() => selectResponseMode(mode)}
                    style={[styles.segment, active && styles.segmentActive]}
                  >
                    <ThemedText
                      variant="label"
                      color={active ? colors.textOnAccent : colors.textSecondary}
                    >
                      {RESPONSE_MODE_LABEL[mode]}
                    </ThemedText>
                  </Pressable>
                );
              })}
            </View>
          </View>
        </View>

        {/* Group 2: Accessibility */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <ThemedText variant="title" style={styles.bold}>
              Accessibility
            </ThemedText>
            <ThemedText variant="caption" color={colors.textSecondary} style={styles.sectionSubtitle}>
              Ibagay ang Suri sa iyong pangangailangan
            </ThemedText>
          </View>

          <View style={styles.list}>
            {TOGGLES.map((row, index) => (
              <View key={row.key} style={[styles.row, index > 0 && styles.rowDivided]}>
                <View style={styles.rowText}>
                  <ThemedText variant="title">{row.label}</ThemedText>
                  <ThemedText variant="caption" color={colors.textSecondary} style={styles.rowDesc}>
                    {row.description}
                  </ThemedText>
                </View>
                <Switch
                  value={settings[row.key]}
                  onValueChange={(value) => setToggle(row.key, value)}
                  trackColor={{ false: colors.surfaceAlt, true: colors.accentPrimaryDim }}
                  thumbColor={settings[row.key] ? colors.accentPrimary : colors.textMuted}
                  ios_backgroundColor={colors.surfaceAlt}
                />
              </View>
            ))}

            {/* Color Vision (cycles through the colorblind-safe palettes on tap). */}
            <Pressable
              accessibilityRole="button"
              accessibilityLabel={`Color Vision: ${COLOR_VISION_LABEL[settings.colorVision]}. Tap to change.`}
              onPress={cycleColorVision}
              style={[styles.row, styles.rowDivided]}
            >
              <View style={styles.rowText}>
                <ThemedText variant="title">Color Vision</ThemedText>
                <ThemedText variant="caption" color={colors.textSecondary} style={styles.rowDesc}>
                  Ibagay ang mga kulay para sa color blindness
                </ThemedText>
              </View>
              <View style={styles.rowControl}>
                <View style={styles.pill}>
                  <ThemedText variant="label" color={colors.textPrimary}>
                    {COLOR_VISION_LABEL[settings.colorVision]}
                  </ThemedText>
                </View>
                <Ionicons name="chevron-forward" size={20} color={colors.textSecondary} />
              </View>
            </Pressable>
          </View>
        </View>

        {/* Hidden Dev Tools (renders only in __DEV__) — must be the last child. */}
        <DevTools />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
  },
  // TopBar -> header bar.
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg, // px-4
    paddingVertical: spacing.md, // py-3
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerSpacer: {
    width: 40, // w-10 spacer keeps the title centered
  },
  headerTitle: {
    flex: 1,
  },
  // main: px-5 py-6 space-y-6 pb-32
  scrollContent: {
    paddingHorizontal: 20, // px-5
    paddingTop: spacing.xl, // py-6
    paddingBottom: 128, // pb-32
    gap: spacing.xl, // space-y-6
  },
  // Page header (avatar + info).
  pageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xl, // gap-6
    marginBottom: spacing.sm, // mb-2
  },
  avatarWrap: {
    width: 80, // w-20
    height: 80, // h-20
    borderRadius: radii.pill, // rounded-full
    borderWidth: 1,
    borderColor: colors.border, // outline-variant
    backgroundColor: colors.surfaceAlt, // surface-container-low (placeholder backdrop)
    padding: spacing.xs, // p-1
    overflow: 'hidden',
    elevation: 2, // shadow-sm
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: radii.pill,
  },
  pageHeaderInfo: {
    flex: 1,
  },
  summary: {
    marginTop: spacing.xs, // mb-1 gap below title
  },
  statRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  stat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  // Sync action.
  syncButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.accentPrimaryDim, // primary-container/10
    borderWidth: 1,
    borderColor: colors.accentPrimary, // primary/20
    borderRadius: radii.lg, // rounded-2xl
    padding: spacing.lg, // p-4
  },
  // Section cards.
  section: {
    backgroundColor: colors.surface, // surface-container-lowest
    borderWidth: 1,
    borderColor: colors.border, // outline-variant
    borderRadius: radii.lg, // rounded-2xl
    overflow: 'hidden',
    elevation: 2, // shadow-sm
  },
  sectionHeader: {
    padding: 20, // p-5
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surfaceAlt, // surface-container-low/30
  },
  sectionSubtitle: {
    marginTop: spacing.xs, // mt-1
  },
  sectionBody: {
    padding: 20, // p-5
  },
  // Segmented control.
  segmented: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceAlt, // surface-container
    borderRadius: radii.md, // rounded-xl
    padding: 6, // p-1.5
    gap: spacing.xs, // gap-1
  },
  segment: {
    flex: 1,
    minHeight: 44, // min-h-[44px]
    paddingVertical: 10, // py-2.5
    paddingHorizontal: spacing.sm, // px-2
    borderRadius: radii.md, // rounded-lg
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActive: {
    backgroundColor: colors.accentPrimary, // primary-container
    elevation: 4, // shadow-md
  },
  // Accessibility list.
  list: {
    flexDirection: 'column',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20, // p-5
    minHeight: 72, // min-h-[72px]
  },
  rowDivided: {
    borderTopWidth: 1,
    borderTopColor: colors.border, // divide-outline-variant
  },
  rowText: {
    flex: 1,
    paddingRight: spacing.lg, // pr-4
  },
  rowDesc: {
    marginTop: spacing.xs, // mt-1
  },
  rowControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md, // gap-3
  },
  pill: {
    backgroundColor: colors.surfaceAlt, // secondary-container
    paddingHorizontal: spacing.lg, // px-4
    paddingVertical: 6, // py-1.5
    borderRadius: radii.pill, // rounded-full
  },
  // Text-weight overrides to match the prototype's display weights.
  bold: {
    fontWeight: FONT_WEIGHT.bold,
  },
  extrabold: {
    fontWeight: FONT_WEIGHT.extrabold,
  },
});
