// AUTO-GENERATED by Kiro Agent — STRICT UI PORT
// Visual Reference: zip(4).zip | Backend: Existing Suri Services
// Status: Needs review
//
// 1:1 port of suri-frontend-extracted/src/views/QuizHub.tsx (+ TopBar.tsx),
// recolored from the prototype's light "Tambayan" palette to our dark palette
// via the role mapping in @/theme. Layout (flex / gaps / padding / radii /
// borders / shadows) mirrors the web DOM exactly; <BottomNav> is dropped since
// the tab bar is provided by app/(tabs)/_layout, and <TopBar> becomes an
// in-screen header View whose gear routes to the Profile tab.
import { Ionicons } from '@expo/vector-icons';
import { useRouter, type Href } from 'expo-router';
import {
  Image,
  Pressable,
  ScrollView,
  StyleSheet,
  View,
  type DimensionValue,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/ui';
import { TAB_BAR_CLEARANCE, useTabBarScroll } from '@/navigation/tabBarVisibility';
import { useProfile } from '@/profile/useProfile';
import { PALETTE, colors, radii, spacing } from '@/theme';

type IconName = keyof typeof Ionicons.glyphMap;

/**
 * Profile tab route. It is a planned follow-up and isn't in the generated
 * typed-routes map yet, so we widen the literal through Href to keep typecheck
 * green until app/(tabs)/profile.tsx exists.
 */
const PROFILE_ROUTE = '/(tabs)/profile' as unknown as Href;

/** Mascot artwork from the prototype's header <img>. */
const MASCOT_URI =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuAvUr9s21paiOm0hVPaXQ6Z5lG6_M1nMHEslInZbBf9gxEa_8JFCVwEbchpBsWyaHPr6A3kQezA1eKjRW6szgR1PTlu7hyn_yNNduKN_L5XZZqa-21b3htxota003sCdJYeq9E0DaEpnUaseeeF4NfbradwJ7rdo7jJYOgROiWNCG_1TBk-iY42uVWYg8FO-sh7N94kUEHiEnzty7rUjacjLZ62LTEcaPIfvO4SU0OcSEigbA2O-IZXTthVsbHf8wO0lCTkq3yEYnI';

/** Icon-circle tone. The dark palette has one cool accent (teal), so the
 *  prototype's tertiary/primary cyan icons map to "primary" and its muted
 *  secondary-container icon maps to "muted". */
type IconTone = 'primary' | 'muted';

interface ActiveQuiz {
  category: string;
  /** Embeds the prototype's <br/> as a newline. */
  title: string;
  icon: IconName;
  answered: number;
  total: number;
  /** Completion percent (0-100). */
  progress: number;
}

interface PastResult {
  id: string;
  subject: string;
  topic: string;
  /** Score percent (0-100). */
  score: number;
  icon: IconName;
  tone: IconTone;
}

/** Sample data mirroring QuizHub.tsx (no quiz-engine service exists yet). */
const ACTIVE_QUIZ: ActiveQuiz = {
  category: 'Agham',
  title: 'Science:\nPhotosynthesis',
  icon: 'leaf',
  answered: 2,
  total: 10,
  progress: 20,
};

const PAST_RESULTS: readonly PastResult[] = [
  {
    id: 'araling-panlipunan',
    subject: 'Araling Panlipunan',
    topic: 'Kasaysayan ng Pilipinas',
    score: 85,
    icon: 'globe',
    tone: 'primary',
  },
  {
    id: 'matematika',
    subject: 'Matematika',
    topic: 'Fractions & Decimals',
    score: 92,
    icon: 'calculator',
    tone: 'primary',
  },
  {
    id: 'filipino',
    subject: 'Filipino',
    topic: 'Pandiwa at Pang-uri',
    score: 78,
    icon: 'language',
    tone: 'muted',
  },
];

/** Resolve the icon glyph color for a circle tone. */
function iconColorFor(tone: IconTone): string {
  return tone === 'primary' ? colors.accentPrimary : colors.textSecondary;
}

/**
 * Pagsusulit (Quizzes) hub. Strict UI port of QuizHub. Quiz logic and the
 * QuizQuestion route are a follow-up, so card presses are intentional no-ops.
 */
export default function QuizzesScreen() {
  const router = useRouter();
  const { profile } = useProfile();
  const tabBarScroll = useTabBarScroll();

  // <TopBar onSettings> -> open the Profile tab (settings live there).
  const openSettings = () => router.push(PROFILE_ROUTE);

  // <div onClick={() => navigate('quizQuestion')}> — route not built yet.
  const handleQuizPress = () => {
    /* no-op: QuizQuestion route + quiz engine are a follow-up. */
  };

  const progressWidth = `${ACTIVE_QUIZ.progress}%` as DimensionValue;

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      {/* In-screen header (was <TopBar title="Suri" showBack={false} />). */}
      <View style={styles.header}>
        <View style={styles.headerSpacer} />
        <ThemedText variant="title" color={colors.accentPrimary} style={styles.headerTitle}>
          Suri
        </ThemedText>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel="Mga setting"
          onPress={openSettings}
          style={({ pressed }) => [styles.headerIconButton, pressed && styles.pressed]}
        >
          <Ionicons name="settings-outline" size={24} color={colors.accentPrimary} />
        </Pressable>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        onScroll={tabBarScroll.onScroll}
        scrollEventThrottle={tabBarScroll.scrollEventThrottle}
      >
        {/* Header Section — flex-col-reverse: mascot on top, copy below. */}
        <View style={[styles.heroCard, styles.shadowSm]}>
          <Image source={{ uri: MASCOT_URI }} style={styles.heroImage} resizeMode="contain" />
          <View style={styles.heroTextBlock}>
            <ThemedText variant="display" color={colors.textPrimary} center>
              Pagsusulit
            </ThemedText>
            <ThemedText variant="title" color={colors.textSecondary} center style={styles.heroSubtitle}>
              Subukan ang iyong kaalaman.
            </ThemedText>
          </View>
        </View>

        {/* Active Quiz */}
        <View style={styles.section}>
          <ThemedText variant="h2" color={colors.textPrimary} style={styles.sectionTitle}>
            Aktibong Pagsusulit
          </ThemedText>

          <Pressable
            accessibilityRole="button"
            accessibilityLabel={`Ipagpatuloy ang ${ACTIVE_QUIZ.category} quiz`}
            onPress={handleQuizPress}
            style={({ pressed }) => [styles.activeCard, styles.shadowSm, pressed && styles.pressed]}
          >
            {/* Top row: category + title | subject icon */}
            <View style={styles.activeTopRow}>
              <View style={styles.activeTopLeft}>
                <View style={styles.badge}>
                  <ThemedText variant="caption" color={colors.textSecondary} style={styles.badgeText}>
                    {ACTIVE_QUIZ.category}
                  </ThemedText>
                </View>
                <ThemedText variant="title" color={colors.textPrimary} style={styles.activeTitle}>
                  {ACTIVE_QUIZ.title}
                </ThemedText>
              </View>
              <View style={[styles.iconCircle, styles.iconCirclePrimary]}>
                <Ionicons name={ACTIVE_QUIZ.icon} size={28} color={colors.accentPrimary} />
              </View>
            </View>

            {/* Progress */}
            <View style={styles.progressBlock}>
              <View style={styles.progressRow}>
                <ThemedText variant="bodySmall" color={colors.textSecondary} style={styles.progressLabel}>
                  {ACTIVE_QUIZ.answered}/{ACTIVE_QUIZ.total} na tanong
                </ThemedText>
                <ThemedText variant="bodySmall" color={colors.accentPrimary} style={styles.progressPercent}>
                  {ACTIVE_QUIZ.progress}%
                </ThemedText>
              </View>
              <View style={styles.progressTrack}>
                <View style={[styles.progressFill, { width: progressWidth }]} />
              </View>
            </View>

            {/* Divider + continue button */}
            <View style={styles.buttonDivider}>
              <Pressable
                accessibilityRole="button"
                accessibilityLabel="Ipagpatuloy"
                onPress={handleQuizPress}
                style={({ pressed }) => [styles.continueButton, styles.shadowMd, pressed && styles.pressed]}
              >
                <ThemedText variant="button" color={colors.textOnAccent}>
                  Ipagpatuloy
                </ThemedText>
              </Pressable>
            </View>
          </Pressable>
        </View>

        {/* Past Results */}
        <View style={styles.section}>
          <ThemedText variant="h2" color={colors.textPrimary} style={styles.sectionTitle}>
            Nakaraang Resulta
          </ThemedText>
          <View style={styles.resultsList}>
            {PAST_RESULTS.map((result) => (
              <Pressable
                key={result.id}
                accessibilityRole="button"
                accessibilityLabel={`${result.subject}: ${result.score}%`}
                onPress={handleQuizPress}
                style={({ pressed }) => [styles.resultCard, styles.shadowSm, pressed && styles.pressed]}
              >
                <View
                  style={[
                    styles.iconCircle,
                    result.tone === 'primary' ? styles.iconCirclePrimary : styles.iconCircleMuted,
                  ]}
                >
                  <Ionicons name={result.icon} size={28} color={iconColorFor(result.tone)} />
                </View>
                <View style={styles.resultTextBlock}>
                  <ThemedText variant="body" color={colors.textPrimary} style={styles.resultSubject}>
                    {result.subject}
                  </ThemedText>
                  <ThemedText variant="caption" color={colors.textSecondary}>
                    {result.topic}
                  </ThemedText>
                </View>
                <View style={styles.resultScoreWrap}>
                  <ThemedText variant="title" color={iconColorFor(result.tone)} style={styles.resultScore}>
                    {result.score}%
                  </ThemedText>
                </View>
              </Pressable>
            ))}
          </View>
        </View>

        {/* Backend status note (additive): grade context + follow-up flag. */}
        <View style={styles.statusNote}>
          <Ionicons name="information-circle-outline" size={16} color={colors.textMuted} />
          <ThemedText variant="caption" color={colors.textMuted} style={styles.statusText}>
            Grade {profile.gradeLevel} • Ang quiz logic at QuizQuestion route ay paparating pa
            (follow-up).
          </ThemedText>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
  },

  // --- Header (TopBar) ---
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg, // px-4
    paddingVertical: spacing.md, // py-3
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border, // border-outline-variant/50
  },
  headerSpacer: {
    width: 40, // w-10 spacer (showBack=false)
  },
  headerTitle: {
    fontWeight: '700', // font-bold
    letterSpacing: -0.3, // tracking-tight
  },
  headerIconButton: {
    padding: spacing.sm, // p-2
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // --- Scroll container ---
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.xl, // px-5
    paddingTop: spacing.xxl, // pt-8
    paddingBottom: TAB_BAR_CLEARANCE + spacing.lg, // clears the floating tab bar
    gap: spacing.xxxl, // space-y-12 (48)
  },

  // --- Header Section card ---
  heroCard: {
    alignItems: 'center',
    gap: spacing.xl, // gap-6
    backgroundColor: colors.surface, // surface-container-lowest
    borderWidth: 1,
    borderColor: colors.border, // outline-variant
    borderRadius: radii.xl, // rounded-3xl
    padding: spacing.xxl, // p-8
  },
  heroImage: {
    width: 128, // w-32
    height: 128, // h-32
  },
  heroTextBlock: {
    alignSelf: 'stretch',
    alignItems: 'center',
    gap: spacing.sm, // space-y-2
  },
  heroSubtitle: {
    fontWeight: '400', // text-lg, regular (font-sans)
  },

  // --- Generic section ---
  section: {
    gap: spacing.lg, // space-y-4
  },
  sectionTitle: {
    paddingHorizontal: spacing.sm, // px-2
  },

  // --- Active Quiz card ---
  activeCard: {
    backgroundColor: colors.surface, // surface-container-lowest
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.xl, // rounded-3xl
    padding: spacing.xl, // p-6
    gap: spacing.xl, // space-y-6
  },
  activeTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.lg, // gap-4
  },
  activeTopLeft: {
    flexShrink: 1,
    gap: spacing.sm, // space-y-2
  },
  badge: {
    alignSelf: 'flex-start', // inline-block
    backgroundColor: colors.surfaceAlt, // surface-container
    borderRadius: radii.md, // rounded-lg
    paddingHorizontal: spacing.md, // px-3
    paddingVertical: spacing.xs, // py-1
  },
  badgeText: {
    fontWeight: '700', // font-bold
    textTransform: 'uppercase',
    letterSpacing: 1.5, // tracking-widest
  },
  activeTitle: {
    fontWeight: '700', // font-bold
  },
  iconCircle: {
    width: 56, // w-14
    height: 56, // h-14
    borderRadius: radii.pill, // rounded-full
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  iconCirclePrimary: {
    backgroundColor: colors.accentPrimaryDim, // primary-container/20
  },
  iconCircleMuted: {
    backgroundColor: colors.surfaceAlt, // secondary-container/50
  },
  progressBlock: {
    gap: spacing.md, // space-y-3
    paddingTop: spacing.sm, // pt-2
  },
  progressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressLabel: {
    fontWeight: '500', // font-medium
  },
  progressPercent: {
    fontWeight: '700', // font-bold
  },
  progressTrack: {
    height: 12, // h-3
    width: '100%',
    backgroundColor: colors.surfaceAlt, // surface-container
    borderRadius: radii.pill, // rounded-full
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.accentPrimary, // bg-primary
    borderRadius: radii.pill,
  },
  buttonDivider: {
    paddingTop: spacing.lg, // pt-5
    borderTopWidth: 1,
    borderTopColor: colors.border, // outline-variant/50
  },
  continueButton: {
    alignSelf: 'stretch', // w-full
    backgroundColor: colors.accentPrimary, // bg-primary
    paddingVertical: spacing.lg, // py-4
    borderRadius: radii.pill, // rounded-full
    alignItems: 'center',
    justifyContent: 'center',
  },

  // --- Past Results ---
  resultsList: {
    gap: spacing.lg, // gap-4
  },
  resultCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg, // gap-4
    backgroundColor: colors.surface, // surface-container-lowest
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.lg, // rounded-2xl
    padding: spacing.lg, // p-4
  },
  resultTextBlock: {
    flex: 1, // flex-grow
  },
  resultSubject: {
    fontWeight: '600', // font-semibold
  },
  resultScoreWrap: {
    alignItems: 'flex-end', // text-right
    flexShrink: 0,
  },
  resultScore: {
    fontWeight: '700', // font-bold
  },

  // --- Status note (additive) ---
  statusNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  statusText: {
    flex: 1,
  },

  // --- Shared ---
  pressed: {
    opacity: 0.85,
  },
  shadowSm: {
    elevation: 2,
    shadowColor: PALETTE.black,
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  shadowMd: {
    elevation: 4,
    shadowColor: PALETTE.black,
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
});
