// AUTO-GENERATED by Kiro Agent — STRICT UI PORT
// Visual Reference: zip(4).zip | Backend: Existing Suri Services
// Status: Needs review
import { Ionicons } from '@expo/vector-icons';
import { useRouter, type Href } from 'expo-router';
import type { ComponentProps } from 'react';
import { useEffect, useMemo, useState } from 'react';
import {
  ActivityIndicator,
  Image,
  Pressable,
  ScrollView,
  StyleSheet,
  View,
  type ViewStyle,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/ui';
import { getReviewerItems, type ReviewerItem } from '@/db/ragStore';
import { TAB_BAR_CLEARANCE, useTabBarScroll } from '@/navigation/tabBarVisibility';
import { useProfile } from '@/profile/useProfile';
import { PALETTE, colors, FONT_WEIGHT, radii, spacing } from '@/theme';

type IoniconName = ComponentProps<typeof Ionicons>['name'];

/**
 * Profile tab route. It is registered in the tab navigator but its screen file
 * (and therefore its generated typed-route entry) does not exist yet, so we
 * assert the href for the typed-routes checker. Keeps the literal exact.
 */
const PROFILE_ROUTE = '/(tabs)/profile' as unknown as Href;

/** Remote art carried over from the web prototype (decorative, 1:1 port). */
const PROFILE_AVATAR_URI =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBqwqGB5DmpaF6AyNLDmewaRbkTsB776lWri3eWRBHVjfZYQhSBy3jxePTMfwfLRvwDjOZjG-3QPVscbbMEQtneJfuwbJDSykE_PVQSTfApfWWnD9MyyWPaD08BuRNXDh7jP9dln1sA_nbt6VCXhaWcOaTBHL6rIHaGl94ujywV1sn9FNiUcaHcDaJ-j27pZ4Z_Ixy10HpmfSdZCezviiZT26fQ3AFw9vfWa5p2rVmQf4AgD7LzIskedLHAQj5EGqvW8c_FpBVpN_A';
const MASCOT_URI =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCThRgTmchNhIp9rzYQbYnbVvk_TwFGmNRN2S_S4o6SV2-GMqbgn5Ca9enI_xb9wa9q5d1nF4UxOyfJSRne4P6Q5plMJjtgKhJfPthumEv3jRkoczCJ8dC7fz2EK__JBoTzygCGwbWhIUcvOGtwucbWBfFgo2i2_-ISeFOfmtNyWEIi9FvjC5Rt1mzpg4VLIUx-p3tB_7jkRjUp0sVp6yqxoiwdNMIcXmd3N_CojtZBWGE3PvQAn_86LvwVD-JIN70_dGZ0NtHXvpg';

/**
 * Static fallback for the "Curriculum Content" carousel — shown only when the
 * RAG store returns no items (empty DB). Mirrors the prototype's example tiles.
 */
const FALLBACK_SUBJECTS = [
  { title: 'Grade 6 Science', desc: 'Matter, Living Things, and Environment.', count: 24 },
  { title: 'Grade 6 Math', desc: 'Fractions, Decimals, and Geometry.', count: 18 },
  { title: 'Grade 6 AP', desc: 'Philippine History and Government.', count: 30 },
];

/** Static "Recent AI Cache" rows — no listing service maps to this, kept visually. */
const AI_CACHE = [
  '"Ano ang photosynthesis at paano ito nangyayari sa mga halaman?"',
  '"Explain the steps in dividing fractions with examples."',
];

/** Nearest Ionicons match for a reviewer item's source. */
function iconForSource(source: ReviewerItem['source']): IoniconName {
  return source === 'personal' ? 'document-text-outline' : 'library-outline';
}

/** Subtle card shadow -> Android elevation + iOS shadow (shadow-sm). */
const shadowSm: ViewStyle = {
  elevation: 2,
  shadowColor: PALETTE.black,
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.2,
  shadowRadius: 3,
};

/** Pronounced FAB shadow (shadow-lg). */
const shadowLg: ViewStyle = {
  elevation: 8,
  shadowColor: PALETTE.black,
  shadowOffset: { width: 0, height: 6 },
  shadowOpacity: 0.3,
  shadowRadius: 12,
};

/**
 * Aklatan / Review (1:1 port of the web prototype's Library view, recolored to
 * the dark palette). Loads reviewer items from the local RAG store, derives the
 * curriculum carousel from their subjects, and lists each item as a card.
 */
export default function ReviewScreen() {
  const router = useRouter();
  const { profile } = useProfile();
  const tabBarScroll = useTabBarScroll();

  const [items, setItems] = useState<ReviewerItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    getReviewerItems(profile.gradeLevel)
      .then((result) => {
        if (!cancelled) {
          setItems(result);
          setError(null);
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setError(err as Error);
        }
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });
    return () => {
      cancelled = true;
    };
  }, [profile.gradeLevel]);

  // Group items by subject -> drives the "Curriculum Content" category cards.
  const subjects = useMemo(() => {
    const groups = new Map<string, ReviewerItem[]>();
    for (const item of items) {
      const key = item.subject ?? 'Iba pa';
      const list = groups.get(key) ?? [];
      list.push(item);
      groups.set(key, list);
    }
    return Array.from(groups, ([subject, list]) => ({ subject, items: list }));
  }, [items]);

  const curriculumCards =
    subjects.length > 0
      ? subjects.map((group) => ({
          key: group.subject,
          title: group.subject,
          desc: `${group.items.length} reviewer item${group.items.length === 1 ? '' : 's'} ready offline.`,
          count: group.items.length,
        }))
      : FALLBACK_SUBJECTS.map((s) => ({ key: s.title, title: s.title, desc: s.desc, count: s.count }));

  return (
    <SafeAreaView edges={['top']} style={styles.root}>
      {/* Header — in-screen port of the prototype <header> (menu | title | profile). */}
      <View style={styles.header}>
        <View style={styles.headerRow}>
          <Pressable accessibilityRole="button" accessibilityLabel="Menu" style={styles.headerIconButton}>
            <Ionicons name="menu" size={24} color={colors.accentPrimary} />
          </Pressable>

          <ThemedText variant="h2" color={colors.accentPrimary} style={styles.brandTitle}>
            Suri
          </ThemedText>

          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Settings"
            onPress={() => router.push(PROFILE_ROUTE)}
            style={styles.avatarButton}
          >
            <Image source={{ uri: PROFILE_AVATAR_URI }} style={styles.avatarImage} resizeMode="cover" />
          </Pressable>
        </View>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        onScroll={tabBarScroll.onScroll}
        scrollEventThrottle={tabBarScroll.scrollEventThrottle}
      >
        {/* Hero: mascot + Aklatan title + description + offline-ready pill */}
        <View style={styles.heroSection}>
          <View style={styles.mascotWrap}>
            <Image source={{ uri: MASCOT_URI }} style={styles.mascot} resizeMode="contain" />
          </View>

          <View style={styles.heroText}>
            <ThemedText variant="display" color={colors.textPrimary} center>
              Aklatan
            </ThemedText>
            <ThemedText variant="body" color={colors.textSecondary} center style={styles.heroSubtitle}>
              Your personal library of curriculum materials and uploaded notes, ready for offline review.
            </ThemedText>
          </View>

          <View style={styles.offlinePill}>
            <Ionicons name="cloud-offline-outline" size={20} color={colors.accentSecondary} />
            <View style={styles.offlinePillText}>
              <ThemedText variant="bodySmall" color={colors.textPrimary} style={styles.weightBold}>
                100% Offline Ready
              </ThemedText>
              <ThemedText variant="caption" color={colors.textSecondary} style={styles.weightMedium}>
                • 142MB
              </ThemedText>
            </View>
          </View>
        </View>

        {/* Curriculum Content — horizontal category cards derived from subjects */}
        <View style={styles.section}>
          <View style={styles.sectionHeaderRow}>
            <ThemedText variant="h2" color={colors.textPrimary}>
              Curriculum Content
            </ThemedText>
            <Pressable accessibilityRole="button" hitSlop={8}>
              <ThemedText variant="bodySmall" color={colors.accentPrimary} style={styles.weightBold}>
                View All
              </ThemedText>
            </Pressable>
          </View>

          {loading ? (
            <View style={styles.carouselLoading}>
              <ActivityIndicator color={colors.accentPrimary} />
            </View>
          ) : (
            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              style={styles.carouselScroll}
              contentContainerStyle={styles.carousel}
            >
              {curriculumCards.map((card) => (
                <Pressable key={card.key} accessibilityRole="button" style={styles.subjectCard}>
                  <View style={styles.subjectCardTop}>
                    <View style={styles.subjectIcon}>
                      <Ionicons name="library-outline" size={24} color={colors.textSecondary} />
                    </View>
                    <View style={styles.readyBadge}>
                      <ThemedText variant="caption" color={colors.textSecondary} style={styles.weightBold}>
                        Ready
                      </ThemedText>
                    </View>
                  </View>

                  <View>
                    <ThemedText variant="title" color={colors.textPrimary} style={styles.weightBold}>
                      {card.title}
                    </ThemedText>
                    <ThemedText variant="body" color={colors.textSecondary} style={styles.subjectDesc}>
                      {card.desc}
                    </ThemedText>
                  </View>

                  <View style={styles.subjectCardFooter}>
                    <ThemedText variant="bodySmall" color={colors.textSecondary} style={styles.weightSemibold}>
                      {card.count} MELCs
                    </ThemedText>
                    <Ionicons name="arrow-forward" size={20} color={colors.textSecondary} />
                  </View>
                </Pressable>
              ))}
            </ScrollView>
          )}
        </View>

        {/* Personal Reviewers — each loaded reviewer item as a list card */}
        <View style={styles.section}>
          <ThemedText variant="h2" color={colors.textPrimary} style={styles.sectionTitle}>
            Personal Reviewers
          </ThemedText>

          {loading ? (
            <View style={styles.stateBox}>
              <ActivityIndicator color={colors.accentPrimary} />
              <ThemedText variant="bodySmall" color={colors.textSecondary}>
                Naglo-load ng iyong mga reviewer...
              </ThemedText>
            </View>
          ) : error ? (
            <View style={styles.stateBox}>
              <Ionicons name="alert-circle-outline" size={24} color={colors.danger} />
              <ThemedText variant="bodySmall" color={colors.textSecondary} center>
                Hindi ma-load ang mga reviewer. Subukan ulit mamaya.
              </ThemedText>
            </View>
          ) : items.length === 0 ? (
            <View style={styles.stateBox}>
              <Ionicons name="documents-outline" size={28} color={colors.textMuted} />
              <ThemedText variant="bodySmall" color={colors.textSecondary} center>
                Wala pang reviewer. Mag-scan o magdagdag ng nota para magsimula.
              </ThemedText>
            </View>
          ) : (
            <View style={styles.listCard}>
              {items.map((item, index) => (
                <Pressable
                  key={`${item.source}-${item.id}`}
                  accessibilityRole="button"
                  style={[styles.itemRow, index < items.length - 1 && styles.itemRowDivider]}
                >
                  <View style={styles.itemIcon}>
                    <Ionicons name={iconForSource(item.source)} size={24} color={colors.textSecondary} />
                  </View>
                  <View style={styles.itemBody}>
                    <View style={styles.itemTitleRow}>
                      <ThemedText
                        variant="title"
                        color={colors.textPrimary}
                        numberOfLines={1}
                        style={styles.itemTitle}
                      >
                        {item.title}
                      </ThemedText>
                      <View style={styles.itemBadge}>
                        <ThemedText variant="caption" color={colors.accentPrimary} style={styles.weightBold}>
                          {item.subject ?? (item.source === 'melc' ? 'MELC' : 'Personal')}
                        </ThemedText>
                      </View>
                    </View>
                    <ThemedText
                      variant="bodySmall"
                      color={colors.textSecondary}
                      numberOfLines={2}
                      style={styles.itemPreview}
                    >
                      {item.preview}
                    </ThemedText>
                  </View>
                </Pressable>
              ))}
            </View>
          )}
        </View>

        {/* Recent AI Cache — static, preserved for layout fidelity */}
        <View style={styles.section}>
          <ThemedText variant="h2" color={colors.textPrimary} style={styles.sectionTitle}>
            Recent AI Cache
          </ThemedText>
          <View style={styles.cacheList}>
            {AI_CACHE.map((query, i) => (
              <Pressable key={i} accessibilityRole="button" style={styles.cacheCard}>
                <ThemedText variant="body" color={colors.textPrimary} numberOfLines={3} style={styles.weightMedium}>
                  {query}
                </ThemedText>
                <View style={styles.cacheMeta}>
                  <Ionicons name="flash-outline" size={16} color={colors.accentSecondary} />
                  <ThemedText variant="caption" color={colors.accentSecondary} style={styles.weightBold}>
                    Available Offline
                  </ThemedText>
                </View>
              </Pressable>
            ))}
          </View>
        </View>
      </ScrollView>

      {/* Floating scan FAB — ported from the prototype (no-op until scan route exists) */}
      <Pressable accessibilityRole="button" accessibilityLabel="Scan worksheet" onPress={() => router.push('/scan' as Href)} style={styles.fab}>
        <Ionicons name="scan-outline" size={28} color={colors.textOnAccent} />
      </Pressable>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },

  // Header: bg-surface, border-b border-outline-variant; px-4 py-3 row, space-between.
  header: {
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  headerIconButton: {
    padding: spacing.sm,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandTitle: {
    letterSpacing: -0.6,
  },
  avatarButton: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },

  // Scroll container: main px-6 pt-10 pb-32, items-center.
  scroll: {
    flex: 1,
  },
  scrollContent: {
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl,
    paddingBottom: TAB_BAR_CLEARANCE + spacing.xl,
  },

  // Hero section (mb-10, centered).
  heroSection: {
    width: '100%',
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  mascotWrap: {
    width: '100%',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  mascot: {
    width: 176,
    height: 176,
  },
  heroText: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  heroSubtitle: {
    marginTop: spacing.sm,
    maxWidth: 320,
  },
  offlinePill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    gap: spacing.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    ...shadowSm,
  },
  offlinePillText: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },

  // Generic section wrapper + headers.
  section: {
    width: '100%',
    marginBottom: spacing.xxl,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    marginBottom: spacing.lg,
  },

  // Curriculum carousel (-mx-6 px-6 gap-4 edge-bleed).
  carouselLoading: {
    height: 180,
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselScroll: {
    marginHorizontal: -spacing.xl,
  },
  carousel: {
    gap: spacing.lg,
    paddingHorizontal: spacing.xl,
  },
  subjectCard: {
    minWidth: 280,
    gap: spacing.xl,
    padding: spacing.xl,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    ...shadowSm,
  },
  subjectCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  subjectIcon: {
    padding: spacing.md,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceElevated,
  },
  readyBadge: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceAlt,
  },
  subjectDesc: {
    marginTop: spacing.xs,
  },
  subjectCardFooter: {
    marginTop: 'auto',
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  // Personal reviewers list card + rows.
  listCard: {
    width: '100%',
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    ...shadowSm,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    padding: spacing.lg,
  },
  itemRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  itemIcon: {
    padding: spacing.md,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceElevated,
  },
  itemBody: {
    flex: 1,
  },
  itemTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  itemTitle: {
    flex: 1,
  },
  itemBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radii.pill,
    backgroundColor: colors.accentPrimaryDim,
  },
  itemPreview: {
    marginTop: spacing.xs,
  },

  // Recent AI cache cards.
  cacheList: {
    gap: spacing.lg,
  },
  cacheCard: {
    padding: spacing.xl,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    ...shadowSm,
  },
  cacheMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.md,
  },

  // Empty / loading / error placeholder.
  stateBox: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.xxl,
    paddingHorizontal: spacing.lg,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },

  // Floating scan button (absolute bottom-right, bg-primary, p-4, shadow-lg).
  fab: {
    position: 'absolute',
    right: spacing.xl,
    bottom: TAB_BAR_CLEARANCE + spacing.md,
    padding: spacing.lg,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentPrimary,
    ...shadowLg,
  },

  // Weight overrides (Tailwind font-bold/semibold/medium on sized variants).
  weightBold: { fontWeight: FONT_WEIGHT.bold },
  weightSemibold: { fontWeight: FONT_WEIGHT.semibold },
  weightMedium: { fontWeight: FONT_WEIGHT.medium },
});
