// AUTO-GENERATED by Kiro Agent — STRICT UI PORT
// Visual Reference: zip(4).zip | Backend: Existing Suri Services
// Status: Needs review
import { Ionicons } from '@expo/vector-icons';
import { router, type Href } from 'expo-router';
import { useRef, useState } from 'react';
import {
  Image,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { routeMessage } from '@/ai/aiRouter';
import type { NetworkTier } from '@/ai/networkTier';
import { useNetworkStatus } from '@/ai/useNetworkStatus';
import { ThemedText } from '@/components/ui';
import { useStreaks } from '@/gamification/useStreaks';
import { useProfile } from '@/profile/useProfile';
import { PALETTE, colors, radii, spacing, typography } from '@/theme';
import { useTTS } from '@/voice/useTTS';

/**
 * Tanong (Ask Suri) — strict 1:1 layout port of the web prototype's Chat screen,
 * recolored to the dark "Tambayan" palette and wired to the existing Suri
 * services (profile, AI router, streaks, TTS). The bottom tab bar is provided by
 * app/(tabs)/_layout.tsx, so the prototype's <BottomNav> is intentionally dropped
 * and the input bar sits in-flow above it.
 */

/** Prototype art URLs (zip(4).zip). Real Suri art will come from hih.zip later. */
const SURI_SYSTEM_IMAGE =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuAKgbEKOUSaMBEfeROHN8qOMVMW9XkeOX-kLk02M-L0jJOOI2guQ5zkISiAlP17ATHhFFczR5w8opE66UFDqyPnq6rFti0dK5d2rQtf3_dDOLgOEvZTFvpbWSevE0qtUVaebnJCfX2fMVXaENhlJFT6lvxAVzK68m6cevopDwFgndjQ9SkxgGiBsnYw1dTeWcPJFczysv6vylWpam4bC6kSssp8NfWplmvIJHXAd3W_KtRr2VQ3DfZS_HXJy1ZC8rS93RShKblBq0A';
const SURI_AVATAR_IMAGE =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuD1yH_V9Yof7TBAKAMIqT3qIZPNdwb9vCAJJQ5T7GD-A0qoYiuWRc_KiI1Z3rfwxlc7TzjHQvRcX_5hIk5yKlXvvwasCaVqC3KHeUwz7yYSan-N_9MO604AFagqDkLWN3t8_bi0E8kkq50yAJSfysaPiLaMUwzaZgrTQ_xN8lBrDOkdhZHQBKDnpjX3-Mc3JJyvoJslQavQZc7BY_LsXrM4ghAZc69I56cfj2yxz1kmOrOw51MXl53MbcEM8dnWuna384ivo98Pg50';

type ChatRole = 'user' | 'assistant';

interface ChatMessage {
  id: string;
  role: ChatRole;
  text: string;
  time: string;
}

/** Render a Date as a short "h:mm AM/PM" clock label, matching the prototype. */
function formatTime(date: Date): string {
  let hours = date.getHours();
  const minutes = date.getMinutes();
  const period = hours >= 12 ? 'PM' : 'AM';
  hours %= 12;
  if (hours === 0) {
    hours = 12;
  }
  const mm = minutes < 10 ? `0${minutes}` : String(minutes);
  return `${hours}:${mm} ${period}`;
}

export default function TanongScreen() {
  const { profile } = useProfile();
  const { streak } = useStreaks();
  const { speak, stop, isSpeaking } = useTTS();
  const net = useNetworkStatus();

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [tier, setTier] = useState<NetworkTier>('offline');
  const [isSending, setIsSending] = useState(false);
  const [speakingId, setSpeakingId] = useState<string | null>(null);
  const [inputFocused, setInputFocused] = useState(false);

  const scrollRef = useRef<ScrollView>(null);
  const idCounter = useRef(0);
  const makeId = () => {
    idCounter.current += 1;
    return `m${idCounter.current}`;
  };

  // Badge source of truth: while a request is in flight, trust the tier the
  // router reported via onTierChange; when idle, reflect live connectivity.
  const displayTier = isSending ? tier : net.tier;
  const isOffline = displayTier === 'offline';
  const canSend = input.trim().length > 0 && !isSending;

  /** Append the user bubble + an empty assistant bubble, then stream the reply. */
  const handleSend = () => {
    const text = input.trim();
    if (!text || isSending) {
      return;
    }

    const userMessage: ChatMessage = {
      id: makeId(),
      role: 'user',
      text,
      time: formatTime(new Date()),
    };
    const assistantId = makeId();
    const assistantMessage: ChatMessage = {
      id: assistantId,
      role: 'assistant',
      text: '',
      time: formatTime(new Date()),
    };

    setMessages((prev) => [...prev, userMessage, assistantMessage]);
    setInput('');
    setIsSending(true);

    const appendToken = (token: string) => {
      setMessages((prev) =>
        prev.map((m) => (m.id === assistantId ? { ...m, text: m.text + token } : m)),
      );
    };
    const finalize = (full: string) => {
      setMessages((prev) => prev.map((m) => (m.id === assistantId ? { ...m, text: full } : m)));
      setIsSending(false);
    };

    void routeMessage({
      message: text,
      profile,
      onToken: appendToken,
      onTierChange: setTier,
      onDone: (full) => finalize(full),
    }).catch(() => {
      setMessages((prev) =>
        prev.map((m) =>
          m.id === assistantId && m.text.length === 0
            ? { ...m, text: 'Paumanhin, hindi ako nakasagot ngayon. Subukan muli.' }
            : m,
        ),
      );
      setIsSending(false);
    });
  };

  /** "Makinig" toggle — speak this message's text, or stop if it's already playing. */
  const toggleListen = (message: ChatMessage) => {
    if (isSpeaking && speakingId === message.id) {
      stop();
      setSpeakingId(null);
      return;
    }
    setSpeakingId(message.id);
    speak(message.text, {
      onDone: () => setSpeakingId(null),
      onStopped: () => setSpeakingId(null),
      onError: () => setSpeakingId(null),
    });
  };

  return (
    <SafeAreaView edges={['top']} style={styles.root}>
      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        {/* In-screen header (ported from TopBar, showBack=false). */}
        <View style={styles.header}>
          <View style={styles.headerSpacer} />
          <ThemedText variant="title" color={colors.accentPrimary} style={styles.headerTitle}>
            Suri
          </ThemedText>
          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Mga setting"
            style={styles.iconButton}
            onPress={() => router.push('/(tabs)/profile' as Href)}
          >
            <Ionicons name="settings-outline" size={24} color={colors.accentPrimary} />
          </Pressable>
        </View>

        {/* Session status sub-header. */}
        <View style={styles.subHeader}>
          <View style={styles.statusPill}>
            <Ionicons
              name={isOffline ? 'moon' : 'sparkles'}
              size={16}
              color={colors.textSecondary}
            />
            <ThemedText variant="caption" color={colors.textSecondary} style={styles.statusLabel}>
              {isOffline ? 'Suri Local' : 'Suri Cloud'}
            </ThemedText>
          </View>
          <View style={styles.streakPill}>
            <Ionicons name="flame" size={20} color={colors.accentPrimary} />
            <ThemedText variant="label" color={colors.accentPrimary} style={styles.streakText}>
              {`${streak?.currentStreak ?? 0} Araw`}
            </ThemedText>
          </View>
        </View>

        {/* Chat feed. */}
        <ScrollView
          ref={scrollRef}
          style={styles.feed}
          contentContainerStyle={styles.feedContent}
          keyboardShouldPersistTaps="handled"
          onContentSizeChange={() => scrollRef.current?.scrollToEnd({ animated: true })}
        >
          {/* System intro message. */}
          <View style={styles.systemBlock}>
            <Image
              source={{ uri: SURI_SYSTEM_IMAGE }}
              style={styles.systemImage}
              resizeMode="contain"
            />
            <View style={styles.systemBubble}>
              <ThemedText
                variant="bodySmall"
                color={colors.textSecondary}
                center
                style={styles.systemText}
              >
                Socratic mode is active. Suri will guide you with questions.
              </ThemedText>
            </View>
          </View>

          {messages.map((message) =>
            message.role === 'user' ? (
              <View key={message.id} style={styles.userWrap}>
                <View style={styles.userBubble}>
                  <ThemedText variant="body" color={colors.textPrimary}>
                    {message.text}
                  </ThemedText>
                </View>
                <ThemedText variant="caption" color={colors.textSecondary} style={styles.timeText}>
                  {message.time}
                </ThemedText>
              </View>
            ) : (
              <View key={message.id} style={styles.assistantWrap}>
                <View style={styles.avatarRow}>
                  <View style={styles.avatarContainer}>
                    <Image
                      source={{ uri: SURI_AVATAR_IMAGE }}
                      style={styles.avatarImage}
                      resizeMode="cover"
                    />
                  </View>
                  <ThemedText variant="caption" color={colors.textSecondary} style={styles.avatarName}>
                    {`Suri • ${message.time}`}
                  </ThemedText>
                </View>

                <View style={styles.assistantBubble}>
                  <View style={styles.accentBar} />
                  <ThemedText
                    variant="body"
                    color={colors.textPrimary}
                    style={styles.assistantText}
                  >
                    {message.text}
                  </ThemedText>
                </View>

                {message.text.trim().length > 0 ? (
                  <View style={styles.listenRow}>
                    <Pressable
                      accessibilityRole="button"
                      accessibilityLabel="Makinig"
                      style={styles.listenButton}
                      onPress={() => toggleListen(message)}
                    >
                      <Ionicons
                        name={isSpeaking && speakingId === message.id ? 'stop' : 'volume-high'}
                        size={16}
                        color={colors.textSecondary}
                      />
                      <ThemedText
                        variant="caption"
                        color={colors.textSecondary}
                        style={styles.listenLabel}
                      >
                        {isSpeaking && speakingId === message.id ? 'Itigil' : 'Makinig'}
                      </ThemedText>
                    </Pressable>
                  </View>
                ) : null}
              </View>
            ),
          )}
        </ScrollView>

        {/* Input area — in-flow so it rests above the tab bar. */}
        <View style={styles.inputRow}>
          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Kumuha ng larawan"
            style={styles.cameraButton}
            onPress={() => router.push('/scan' as Href)}
          >
            <Ionicons name="camera" size={24} color={colors.textSecondary} />
          </Pressable>

          <View style={[styles.inputWrapper, inputFocused && styles.inputWrapperFocused]}>
            <TextInput
              style={styles.textInput}
              value={input}
              onChangeText={setInput}
              placeholder="Magtanong kay Suri..."
              placeholderTextColor={colors.textMuted}
              multiline
              onFocus={() => setInputFocused(true)}
              onBlur={() => setInputFocused(false)}
            />
          </View>

          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Ipadala"
            disabled={!canSend}
            style={[styles.sendButton, !canSend && styles.sendButtonDisabled]}
            onPress={handleSend}
          >
            <Ionicons name="mic" size={24} color={colors.textOnAccent} />
          </Pressable>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

/** Approximated soft shadow (shadow-sm) shared by bubbles, pills, and buttons. */
const shadowSm = {
  shadowColor: PALETTE.black,
  shadowOpacity: 0.1,
  shadowRadius: 3,
  shadowOffset: { width: 0, height: 1 },
  elevation: 2,
};

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  flex: {
    flex: 1,
  },

  // Header (TopBar port).
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerSpacer: {
    width: 40,
  },
  headerTitle: {
    fontWeight: '700',
  },
  iconButton: {
    padding: spacing.sm,
    borderRadius: radii.pill,
  },

  // Session status sub-header.
  subHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    ...shadowSm,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statusLabel: {
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  streakPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radii.md,
  },
  streakText: {
    fontWeight: '600',
  },

  // Chat feed.
  feed: {
    flex: 1,
  },
  feedContent: {
    padding: spacing.lg,
    gap: spacing.xl,
  },

  // System intro.
  systemBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.lg,
    gap: spacing.lg,
  },
  systemImage: {
    width: 160,
    height: 120,
  },
  systemBubble: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  systemText: {
    maxWidth: 280,
  },

  // User message.
  userWrap: {
    alignSelf: 'flex-end',
    maxWidth: '85%',
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  userBubble: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    borderTopRightRadius: radii.sm,
    paddingHorizontal: 20,
    paddingVertical: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadowSm,
  },
  timeText: {
    fontSize: 10,
    marginRight: spacing.xs,
  },

  // Suri (assistant) message.
  assistantWrap: {
    alignSelf: 'flex-start',
    maxWidth: '92%',
    gap: spacing.sm,
  },
  avatarRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
  },
  avatarContainer: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    backgroundColor: colors.accentPrimary,
    padding: 2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: radii.pill,
  },
  avatarName: {
    fontSize: 10,
  },
  assistantBubble: {
    position: 'relative',
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderTopLeftRadius: radii.sm,
    paddingHorizontal: 20,
    paddingVertical: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    marginLeft: 40,
    ...shadowSm,
  },
  accentBar: {
    position: 'absolute',
    left: 0,
    top: spacing.lg,
    bottom: spacing.lg,
    width: 4,
    backgroundColor: colors.accentPrimary,
    borderTopRightRadius: radii.pill,
    borderBottomRightRadius: radii.pill,
  },
  assistantText: {
    paddingLeft: spacing.sm,
  },
  listenRow: {
    marginLeft: 40,
    marginTop: spacing.xs,
  },
  listenButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: spacing.sm,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing.lg,
    paddingVertical: 6,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadowSm,
  },
  listenLabel: {
    fontWeight: '600',
  },

  // Input area.
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.md,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  cameraButton: {
    padding: spacing.md,
    borderRadius: radii.pill,
    marginBottom: 2,
  },
  inputWrapper: {
    flex: 1,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    minHeight: 52,
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: colors.transparent,
    ...shadowSm,
  },
  inputWrapperFocused: {
    borderBottomColor: colors.borderStrong,
  },
  textInput: {
    color: colors.textPrimary,
    ...typography.body,
    padding: 0,
    maxHeight: 120,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: radii.pill,
    backgroundColor: colors.accentPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
    ...shadowSm,
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
});
