// AUTO-GENERATED by Kiro Agent — STRICT UI PORT
// Visual Reference: zip(4).zip | Backend: Existing Suri Services
// Status: Reviewed — navbar fix, UI polish, demo-ready
import { Ionicons } from '@expo/vector-icons';
import { router, type Href } from 'expo-router';
import { useRef, useState } from 'react';
import {
  Animated as RNAnimated,
  Image,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  TextInput,
  useWindowDimensions,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { routeMessage } from '@/ai/aiRouter';
import type { NetworkTier } from '@/ai/networkTier';
import { useNetworkStatus } from '@/ai/useNetworkStatus';
import { ThemedText } from '@/components/ui';
import { useStreaks } from '@/gamification/useStreaks';
import { useProfile } from '@/profile/useProfile';
import { PALETTE, colors, radii, spacing, typography } from '@/theme';
import { VisualRenderer } from '@/visuals/VisualRenderer';
import { parseVisualSpec } from '@/visuals/visualParser';
import { useTTS } from '@/voice/useTTS';

/**
 * Tanong (Ask Suri) — strict 1:1 layout port of the web prototype's Chat screen,
 * recolored to the dark "Tambayan" palette and wired to the existing Suri
 * services (profile, AI router, streaks, TTS). The bottom tab bar is provided by
 * app/(tabs)/_layout.tsx, so the prototype's <BottomNav> is intentionally dropped
 * and the input bar sits in-flow above it.
 */

/** Prototype art URLs (zip(4).zip). Real Suri art will come from hih.zip later. */
const SURI_SYSTEM_IMAGE =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuAKgbEKOUSaMBEfeROHN8qOMVMW9XkeOX-kLk02M-L0jJOOI2guQ5zkISiAlP17ATHhFFczR5w8opE66UFDqyPnq6rFti0dK5d2rQtf3_dDOLgOEvZTFvpbWSevE0qtUVaebnJCfX2fMVXaENhlJFT6lvxAVzK68m6cevopDwFgndjQ9SkxgGiBsnYw1dTeWcPJFczysv6vylWpam4bC6kSssp8NfWplmvIJHXAd3W_KtRr2VQ3DfZS_HXJy1ZC8rS93RShKblBq0A';
const SURI_AVATAR_IMAGE =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuD1yH_V9Yof7TBAKAMIqT3qIZPNdwb9vCAJJQ5T7GD-A0qoYiuWRc_KiI1Z3rfwxlc7TzjHQvRcX_5hIk5yKlXvvwasCaVqC3KHeUwz7yYSan-N_9MO604AFagqDkLWN3t8_bi0E8kkq50yAJSfysaPiLaMUwzaZgrTQ_xN8lBrDOkdhZHQBKDnpjX3-Mc3JJyvoJslQavQZc7BY_LsXrM4ghAZc69I56cfj2yxz1kmOrOw51MXl53MbcEM8dnWuna384ivo98Pg50';

type ChatRole = 'user' | 'assistant';

interface ChatMessage {
  id: string;
  role: ChatRole;
  text: string;
  time: string;
}

/** Render a Date as a short "h:mm AM/PM" clock label, matching the prototype. */
function formatTime(date: Date): string {
  let hours = date.getHours();
  const minutes = date.getMinutes();
  const period = hours >= 12 ? 'PM' : 'AM';
  hours %= 12;
  if (hours === 0) {
    hours = 12;
  }
  const mm = minutes < 10 ? `0${minutes}` : String(minutes);
  return `${hours}:${mm} ${period}`;
}

/**
 * Height reserved at the bottom for the floating tab bar so the input area
 * is never obscured. Matches the FloatingTabBar's bar height + bottom inset.
 */
const TAB_BAR_CLEARANCE = 90;

/** Remove the fenced ```json visual-spec block from the prose shown in a bubble. */
function stripVisualBlock(text: string): string {
  return text.replace(/```json\s*[\s\S]*?```/gi, '').trim();
}

export default function TanongScreen() {
  const { profile } = useProfile();
  const { streak } = useStreaks();
  const { speak, stop, isSpeaking } = useTTS();
  const net = useNetworkStatus();
  const { width: screenWidth } = useWindowDimensions();
  // Width for any AI-rendered chart, aligned under the assistant bubble.
  const chartWidth = Math.max(220, Math.min(300, screenWidth - 96));

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [tier, setTier] = useState<NetworkTier>('strong');
  const [isSending, setIsSending] = useState(false);
  const [speakingId, setSpeakingId] = useState<string | null>(null);
  const [inputFocused, setInputFocused] = useState(false);
  // Context lens for the chips above the input. 'local' forces the offline
  // "Suri Local" indicator; 'auto' follows live connectivity.
  const [chatMode, setChatMode] = useState<'auto' | 'local'>('auto');

  // Send button press animation
  const sendScale = useRef(new RNAnimated.Value(1)).current;

  const scrollRef = useRef<ScrollView>(null);
  const idCounter = useRef(0);
  const makeId = () => {
    idCounter.current += 1;
    return `m${idCounter.current}`;
  };

  // Badge source of truth: while a request is in flight, trust the tier the
  // router reported via onTierChange; when idle, reflect live connectivity.
  const displayTier = isSending ? tier : net.tier;
  const isOffline = chatMode === 'local' || displayTier === 'offline';
  const canSend = input.trim().length > 0 && !isSending;

  /** Append the user bubble + an empty assistant bubble, then stream the reply. */
  const handleSend = () => {
    const text = input.trim();
    if (!text || isSending) {
      return;
    }

    // Micro-animation on send
    RNAnimated.sequence([
      RNAnimated.timing(sendScale, { toValue: 0.85, duration: 80, useNativeDriver: true }),
      RNAnimated.timing(sendScale, { toValue: 1, duration: 120, useNativeDriver: true }),
    ]).start();

    const userMessage: ChatMessage = {
      id: makeId(),
      role: 'user',
      text,
      time: formatTime(new Date()),
    };
    const assistantId = makeId();
    const assistantMessage: ChatMessage = {
      id: assistantId,
      role: 'assistant',
      text: '',
      time: formatTime(new Date()),
    };

    setMessages((prev) => [...prev, userMessage, assistantMessage]);
    setInput('');
    setIsSending(true);

    const appendToken = (token: string) => {
      setMessages((prev) =>
        prev.map((m) => (m.id === assistantId ? { ...m, text: m.text + token } : m)),
      );
    };
    const finalize = (full: string) => {
      setMessages((prev) => prev.map((m) => (m.id === assistantId ? { ...m, text: full } : m)));
      setIsSending(false);
    };

    void routeMessage({
      message: text,
      profile,
      onToken: appendToken,
      onTierChange: setTier,
      onDone: (full) => finalize(full),
    }).catch(() => {
      setMessages((prev) =>
        prev.map((m) =>
          m.id === assistantId && m.text.length === 0
            ? { ...m, text: 'Paumanhin, hindi ako nakasagot ngayon. Subukan muli.' }
            : m,
        ),
      );
      setIsSending(false);
    });
  };

  /** "Makinig" toggle — speak this message's text, or stop if it's already playing. */
  const toggleListen = (message: ChatMessage) => {
    if (isSpeaking && speakingId === message.id) {
      stop();
      setSpeakingId(null);
      return;
    }
    setSpeakingId(message.id);
    speak(message.text, {
      onDone: () => setSpeakingId(null),
      onStopped: () => setSpeakingId(null),
      onError: () => setSpeakingId(null),
    });
  };

  return (
    <SafeAreaView edges={['top']} style={styles.root}>
      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        keyboardVerticalOffset={Platform.OS === 'ios' ? 0 : 0}
      >
        {/* In-screen header — warm gradient feel. */}
        <View style={styles.header}>
          <View style={styles.headerSpacer} />
          <ThemedText variant="title" color={colors.accentPrimary} style={styles.headerTitle}>
            Suri
          </ThemedText>
          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Mga setting"
            style={styles.iconButton}
            onPress={() => router.push('/(tabs)/profile' as Href)}
          >
            <Ionicons name="settings-outline" size={24} color={colors.accentPrimary} />
          </Pressable>
        </View>

        {/* Session status sub-header with enhanced pills. */}
        <View style={styles.subHeader}>
          <View style={[styles.statusPill, !isOffline && styles.statusPillOnline]}>
            <Ionicons
              name={isOffline ? 'moon' : 'sparkles'}
              size={14}
              color={isOffline ? colors.textSecondary : colors.accentPrimary}
            />
            <ThemedText
              variant="caption"
              color={isOffline ? colors.textSecondary : colors.accentPrimary}
              style={styles.statusLabel}
            >
              {isOffline ? 'SURI LOCAL' : 'SURI CLOUD'}
            </ThemedText>
          </View>
          <View style={styles.streakPill}>
            <Ionicons name="flame" size={18} color={colors.accentPrimary} />
            <ThemedText variant="label" color={colors.accentPrimary} style={styles.streakText}>
              {`${streak?.currentStreak ?? 0} Araw`}
            </ThemedText>
          </View>
        </View>

        {/* Chat feed. */}
        <ScrollView
          ref={scrollRef}
          style={styles.feed}
          contentContainerStyle={styles.feedContent}
          keyboardShouldPersistTaps="handled"
          onContentSizeChange={() => scrollRef.current?.scrollToEnd({ animated: true })}
        >
          {/* System intro message — enhanced card. */}
          <View style={styles.systemBlock}>
            <Image
              source={{ uri: SURI_SYSTEM_IMAGE }}
              style={styles.systemImage}
              resizeMode="contain"
            />
            <View style={styles.systemBubble}>
              <View style={styles.systemAccent} />
              <ThemedText
                variant="bodySmall"
                color={colors.textSecondary}
                center
                style={styles.systemText}
              >
                Socratic mode is active. Suri will guide you with questions.
              </ThemedText>
            </View>
          </View>

          {messages.map((message) =>
            message.role === 'user' ? (
              <View key={message.id} style={styles.userWrap}>
                <View style={styles.userBubble}>
                  <ThemedText variant="body" color={colors.textPrimary}>
                    {message.text}
                  </ThemedText>
                </View>
                <ThemedText variant="caption" color={colors.textSecondary} style={styles.timeText}>
                  {message.time}
                </ThemedText>
              </View>
            ) : (
              <View key={message.id} style={styles.assistantWrap}>
                <View style={styles.avatarRow}>
                  <View style={styles.avatarContainer}>
                    <Image
                      source={{ uri: SURI_AVATAR_IMAGE }}
                      style={styles.avatarImage}
                      resizeMode="cover"
                    />
                  </View>
                  <ThemedText variant="caption" color={colors.textSecondary} style={styles.avatarName}>
                    {`Suri • ${message.time}`}
                  </ThemedText>
                </View>

                {(() => {
                  // Render any AI diagram spec (spec 5.4) below the prose; it
                  // auto-applies the student's color-vision palette (spec 5.6).
                  const spec = message.text ? parseVisualSpec(message.text) : null;
                  const prose = spec ? stripVisualBlock(message.text) : message.text;
                  return (
                    <>
                      <View style={styles.assistantBubble}>
                        <View style={styles.accentBar} />
                        <ThemedText
                          variant="body"
                          color={colors.textPrimary}
                          style={styles.assistantText}
                        >
                          {prose || (isSending ? '...' : '')}
                        </ThemedText>
                      </View>
                      {spec ? (
                        <View style={styles.chartWrap}>
                          <VisualRenderer spec={spec} width={chartWidth} height={200} />
                        </View>
                      ) : null}
                    </>
                  );
                })()}

                {message.text.trim().length > 0 ? (
                  <View style={styles.listenRow}>
                    <Pressable
                      accessibilityRole="button"
                      accessibilityLabel="Makinig"
                      style={styles.listenButton}
                      onPress={() => toggleListen(message)}
                    >
                      <Ionicons
                        name={isSpeaking && speakingId === message.id ? 'stop' : 'volume-high'}
                        size={16}
                        color={colors.textSecondary}
                      />
                      <ThemedText
                        variant="caption"
                        color={colors.textSecondary}
                        style={styles.listenLabel}
                      >
                        {isSpeaking && speakingId === message.id ? 'Itigil' : 'Makinig'}
                      </ThemedText>
                    </Pressable>
                  </View>
                ) : null}
              </View>
            ),
          )}
        </ScrollView>

        {/* Quick context chips — switch lens or jump to Kwento mode. */}
        <View style={styles.modeChips}>
          <Pressable
            accessibilityRole="button"
            accessibilityState={{ selected: chatMode === 'local' }}
            style={[styles.modeChip, chatMode === 'local' && styles.modeChipActive]}
            onPress={() => setChatMode('local')}
          >
            <Ionicons
              name="moon"
              size={14}
              color={chatMode === 'local' ? colors.textOnAccent : colors.textSecondary}
            />
            <ThemedText
              variant="caption"
              color={chatMode === 'local' ? colors.textOnAccent : colors.textSecondary}
              style={styles.modeChipText}
            >
              Suri Local
            </ThemedText>
          </Pressable>

          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Pumunta sa Kwento mode"
            style={styles.modeChip}
            onPress={() => router.push('/(tabs)/kwento' as Href)}
          >
            <Ionicons name="book-outline" size={14} color={colors.textSecondary} />
            <ThemedText variant="caption" color={colors.textSecondary} style={styles.modeChipText}>
              Kwento
            </ThemedText>
          </Pressable>

          <Pressable
            accessibilityRole="button"
            accessibilityState={{ selected: chatMode === 'auto' }}
            style={[styles.modeChip, chatMode === 'auto' && styles.modeChipActive]}
            onPress={() => setChatMode('auto')}
          >
            <Ionicons
              name="chatbubble-ellipses-outline"
              size={14}
              color={chatMode === 'auto' ? colors.textOnAccent : colors.textSecondary}
            />
            <ThemedText
              variant="caption"
              color={chatMode === 'auto' ? colors.textOnAccent : colors.textSecondary}
              style={styles.modeChipText}
            >
              Tanong
            </ThemedText>
          </Pressable>
        </View>

        {/* Input area — with bottom padding to clear the floating tab bar. */}
        <View style={styles.inputRow}>
          <Pressable
            accessibilityRole="button"
            accessibilityLabel="Kumuha ng larawan"
            style={styles.cameraButton}
            onPress={() => router.push('/scan' as Href)}
          >
            <Ionicons name="camera" size={22} color={colors.textSecondary} />
          </Pressable>

          <View style={[styles.inputWrapper, inputFocused && styles.inputWrapperFocused]}>
            <TextInput
              style={styles.textInput}
              value={input}
              onChangeText={setInput}
              placeholder="Magtanong kay Suri..."
              placeholderTextColor={colors.textMuted}
              multiline
              onFocus={() => setInputFocused(true)}
              onBlur={() => setInputFocused(false)}
              onSubmitEditing={handleSend}
            />
          </View>

          <RNAnimated.View style={{ transform: [{ scale: sendScale }] }}>
            <Pressable
              accessibilityRole="button"
              accessibilityLabel={canSend ? 'Ipadala' : 'Magsalita'}
              disabled={!canSend}
              style={[styles.sendButton, !canSend && styles.sendButtonDisabled]}
              onPress={handleSend}
            >
              <Ionicons name={canSend ? 'send' : 'mic'} size={20} color={colors.textOnAccent} />
            </Pressable>
          </RNAnimated.View>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

/** Approximated soft shadow (shadow-sm) shared by bubbles, pills, and buttons. */
const shadowSm = {
  shadowColor: PALETTE.black,
  shadowOpacity: 0.08,
  shadowRadius: 4,
  shadowOffset: { width: 0, height: 2 },
  elevation: 2,
};

/** Elevated shadow for cards and input area. */
const shadowMd = {
  shadowColor: PALETTE.black,
  shadowOpacity: 0.12,
  shadowRadius: 8,
  shadowOffset: { width: 0, height: 4 },
  elevation: 4,
};

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  flex: {
    flex: 1,
  },

  // Header — warm gradient feel.
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.background,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  headerSpacer: {
    width: 40,
  },
  headerTitle: {
    fontWeight: '700',
    fontSize: 22,
    letterSpacing: 0.5,
  },
  iconButton: {
    padding: spacing.sm,
    borderRadius: radii.pill,
    backgroundColor: colors.accentPrimaryDim,
  },

  // Session status sub-header — enhanced.
  subHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    ...shadowSm,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statusPillOnline: {
    backgroundColor: colors.accentPrimaryDim,
    borderColor: 'rgba(160, 59, 14, 0.25)',
  },
  statusLabel: {
    fontWeight: '700',
    letterSpacing: 1.2,
    fontSize: 11,
  },
  streakPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.accentPrimaryDim,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radii.pill,
  },
  streakText: {
    fontWeight: '700',
    fontSize: 13,
  },

  // Chat feed.
  feed: {
    flex: 1,
  },
  feedContent: {
    padding: spacing.lg,
    paddingBottom: spacing.lg,
    gap: spacing.xl,
  },

  // System intro — enhanced card.
  systemBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.md,
    gap: spacing.md,
  },
  systemImage: {
    width: 160,
    height: 130,
  },
  systemBubble: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    position: 'relative',
    overflow: 'hidden',
    ...shadowSm,
  },
  systemAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: colors.accentPrimary,
    borderTopLeftRadius: radii.lg,
    borderTopRightRadius: radii.lg,
  },
  systemText: {
    maxWidth: 280,
    lineHeight: 20,
  },

  // User message.
  userWrap: {
    alignSelf: 'flex-end',
    maxWidth: '80%',
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  userBubble: {
    backgroundColor: colors.accentPrimaryDim,
    borderRadius: radii.lg,
    borderTopRightRadius: radii.sm,
    paddingHorizontal: 18,
    paddingVertical: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(160, 59, 14, 0.15)',
    ...shadowSm,
  },
  timeText: {
    fontSize: 10,
    marginRight: spacing.xs,
    opacity: 0.7,
  },

  // Suri (assistant) message.
  assistantWrap: {
    alignSelf: 'flex-start',
    maxWidth: '92%',
    gap: spacing.sm,
  },
  avatarRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
  },
  avatarContainer: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    backgroundColor: colors.accentPrimaryDim,
    padding: 2,
    borderWidth: 1.5,
    borderColor: colors.accentPrimary,
    ...shadowSm,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: radii.pill,
  },
  avatarName: {
    fontSize: 10,
    opacity: 0.7,
  },
  assistantBubble: {
    position: 'relative',
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderTopLeftRadius: radii.sm,
    paddingHorizontal: 18,
    paddingVertical: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    marginLeft: 42,
    ...shadowSm,
  },
  accentBar: {
    position: 'absolute',
    left: 0,
    top: spacing.lg,
    bottom: spacing.lg,
    width: 3,
    backgroundColor: colors.accentPrimary,
    borderTopRightRadius: radii.pill,
    borderBottomRightRadius: radii.pill,
  },
  assistantText: {
    paddingLeft: spacing.sm,
    lineHeight: 22,
  },
  chartWrap: {
    marginLeft: 42,
    marginTop: spacing.sm,
    alignItems: 'flex-start',
  },
  listenRow: {
    marginLeft: 42,
    marginTop: spacing.xs,
  },
  listenButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: spacing.sm,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing.md,
    paddingVertical: 5,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadowSm,
  },
  listenLabel: {
    fontWeight: '600',
    fontSize: 11,
  },

  // Quick context chips.
  modeChips: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    backgroundColor: colors.background,
  },
  modeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  modeChipActive: {
    backgroundColor: colors.accentPrimary,
    borderColor: colors.accentPrimary,
  },
  modeChipText: {
    fontWeight: '600',
    fontSize: 11,
  },

  // Input area — with bottom clearance for the floating tab bar.
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: TAB_BAR_CLEARANCE,
    ...shadowMd,
  },
  cameraButton: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  inputWrapper: {
    flex: 1,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: Platform.OS === 'ios' ? spacing.md : spacing.sm,
    minHeight: 44,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    ...shadowSm,
  },
  inputWrapperFocused: {
    borderColor: colors.accentPrimary,
    backgroundColor: colors.surface,
  },
  textInput: {
    color: colors.textPrimary,
    ...typography.body,
    padding: 0,
    maxHeight: 100,
    fontSize: 15,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: radii.pill,
    backgroundColor: colors.accentPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
    ...shadowMd,
  },
  sendButtonDisabled: {
    opacity: 0.45,
  },
});
