// AUTO-GENERATED by Kiro Agent — Final Native Wiring & QA
// Status: 100% Completion Target
import { Component, type ErrorInfo, type ReactNode } from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { Button } from '@/components/ui';
import { colors, spacing, typography } from '@/theme';

/** Props for {@link ErrorBoundary}. */
export interface ErrorBoundaryProps {
  /** The subtree this boundary protects from render-time crashes. */
  children: ReactNode;
  /** Optional custom UI rendered in place of the built-in fallback. */
  fallback?: ReactNode;
}

/** Boundary state: the caught error, or `null` while the subtree is healthy. */
export interface ErrorBoundaryState {
  error: Error | null;
}

/**
 * App-wide render error boundary.
 *
 * An offline study companion must never strand a student on a blank white
 * screen, so this class component catches render-time errors thrown anywhere in
 * its subtree (via {@link getDerivedStateFromError}) and swaps in a themed,
 * recoverable fallback instead of letting React unmount the whole tree.
 *
 * The fallback shows a Tagalog title ("Nagkaproblema"), the underlying error
 * message, and a "Subukan Muli" button that calls {@link reset} to clear the
 * error and re-mount the protected subtree. Callers may override the entire
 * fallback by passing a `fallback` node.
 *
 * Error boundaries only catch errors during render, in lifecycle methods, and
 * in constructors of the components below them — not in async callbacks or event
 * handlers, which must handle their own failures.
 */
export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { error: null };

  /** Derive the error state synchronously when a child throws during render. */
  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { error };
  }

  /** Log the error and its component stack for offline diagnostics. */
  componentDidCatch(error: Error, info: ErrorInfo): void {
    console.error('[ErrorBoundary] Caught a render error:', error, info.componentStack);
  }

  /** Clear the captured error so the protected subtree re-renders from scratch. */
  reset = (): void => {
    this.setState({ error: null });
  };

  render(): ReactNode {
    const { error } = this.state;
    const { children, fallback } = this.props;

    if (error) {
      if (fallback !== undefined) {
        return fallback;
      }

      return (
        <View style={styles.container}>
          <Text accessibilityRole="header" style={styles.title}>
            Nagkaproblema
          </Text>
          <Text style={styles.message}>{error.message}</Text>
          <Button label="Subukan Muli" onPress={this.reset} />
        </View>
      );
    }

    return children;
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.md,
    backgroundColor: colors.background,
  },
  title: {
    ...typography.title,
    color: colors.textPrimary,
    textAlign: 'center',
  },
  message: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
  },
});
