// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — tap-to-reveal hint; reveal is one-way and counts toward hintUsed.
import { Ionicons } from '@expo/vector-icons';
import { StyleSheet, View } from 'react-native';

import { Button, Card, ThemedText } from '@/components/ui';
import { colors, spacing } from '@/theme';

export interface HintRevealProps {
  hint: string;
  revealed: boolean;
  onReveal: () => void;
}

/**
 * Tap-to-reveal hint. Hidden state is a ghost button so it stays unobtrusive;
 * revealing shows the hint in a subtle card. Reveal is one-way (the hook tracks
 * hintUsed for scoring).
 */
export function HintReveal({ hint, revealed, onReveal }: HintRevealProps) {
  if (!revealed) {
    return (
      <Button
        label="Pakita ang hint"
        icon="bulb-outline"
        variant="ghost"
        fullWidth
        onPress={onReveal}
      />
    );
  }

  return (
    <Card style={styles.card}>
      <View style={styles.header}>
        <Ionicons name="bulb" size={16} color={colors.warning} />
        <ThemedText variant="label" color={colors.warning}>
          Hint
        </ThemedText>
      </View>
      <ThemedText variant="body" color={colors.textSecondary}>
        {hint}
      </ThemedText>
    </Card>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surfaceAlt,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
});
