// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — horizontal setting chips; tapping the active chip clears to auto-pick.
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';

import { ThemedText } from '@/components/ui';
import { colors, radii, spacing } from '@/theme';

import { CULTURAL_SETTINGS, CULTURAL_SETTING_IDS } from '../constants/culturalSettings';
import type { KwentoCulturalSetting } from '../types/kwento.types';

export interface KwentoSettingSelectorProps {
  value?: KwentoCulturalSetting;
  onChange: (setting: KwentoCulturalSetting | undefined) => void;
}

/**
 * Horizontal, single-select chip row of cultural settings. Selecting a chip pins
 * the setting; tapping the already-active chip clears the selection (undefined),
 * which lets Suri auto-pick the best-fitting setting for the topic.
 */
export function KwentoSettingSelector({ value, onChange }: KwentoSettingSelectorProps) {
  return (
    <View style={styles.wrap}>
      <ThemedText variant="label" color={colors.textSecondary}>
        Saan ang kwento?
      </ThemedText>
      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        contentContainerStyle={styles.row}
      >
        {CULTURAL_SETTING_IDS.map((id) => {
          const active = value === id;
          return (
            <Pressable
              key={id}
              accessibilityRole="button"
              accessibilityState={{ selected: active }}
              onPress={() => onChange(active ? undefined : id)}
              style={[styles.chip, active && styles.chipActive]}
            >
              <ThemedText
                variant="label"
                color={active ? colors.textOnAccent : colors.textSecondary}
              >
                {CULTURAL_SETTINGS[id].name}
              </ThemedText>
            </Pressable>
          );
        })}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: {
    gap: spacing.sm,
  },
  row: {
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  chip: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipActive: {
    backgroundColor: colors.accentPrimary,
    borderColor: colors.accentPrimary,
  },
});
