// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — free-text answer entry; numeric keypad intentionally not forced.
import { useState } from 'react';
import { StyleSheet, TextInput, View } from 'react-native';

import { Button, Card, ThemedText } from '@/components/ui';
import { colors, radii, spacing, typography } from '@/theme';

export interface ProblemBlockProps {
  tanong: string;
  disabled?: boolean;
  onSubmit: (answer: string) => void;
}

/**
 * The interactive problem: shows the restated question, a free-text input, and a
 * "Sagot" submit button. Owns only its draft answer; submission/grading is the
 * parent's concern (useKwentoMode.submitAnswer).
 */
export function ProblemBlock({ tanong, disabled = false, onSubmit }: ProblemBlockProps) {
  const [answer, setAnswer] = useState('');
  const trimmed = answer.trim();
  const canSubmit = !disabled && trimmed.length > 0;

  const handleSubmit = () => {
    if (!canSubmit) {
      return;
    }
    onSubmit(trimmed);
  };

  return (
    <Card>
      <View style={styles.header}>
        <ThemedText variant="label" color={colors.accentPrimary}>
          Tanong
        </ThemedText>
      </View>
      <ThemedText variant="title">{tanong}</ThemedText>

      <TextInput
        style={styles.input}
        value={answer}
        onChangeText={setAnswer}
        placeholder="Isulat ang iyong sagot..."
        placeholderTextColor={colors.textMuted}
        editable={!disabled}
        multiline
      />

      <Button
        label="Sagot"
        icon="checkmark"
        variant="primary"
        fullWidth
        disabled={!canSubmit}
        onPress={handleSubmit}
      />
    </Card>
  );
}

const styles = StyleSheet.create({
  header: {
    marginBottom: spacing.xs,
  },
  input: {
    minHeight: 52,
    maxHeight: 120,
    marginTop: spacing.md,
    marginBottom: spacing.md,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    color: colors.textPrimary,
    ...typography.body,
  },
});
