// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — reveals step-by-step suliranin_sagot after a wrong/misconception attempt.
import { Ionicons } from '@expo/vector-icons';
import { StyleSheet, View } from 'react-native';

import { Button, Card, ThemedText } from '@/components/ui';
import { colors, spacing } from '@/theme';

export interface SolutionRevealProps {
  solution: string;
  revealed: boolean;
  onReveal: () => void;
}

/**
 * Tap-to-reveal step-by-step solution. Mirrors HintReveal but uses an outline
 * button (a heavier affordance than the hint) since seeing the full solution is
 * a bigger commitment.
 */
export function SolutionReveal({ solution, revealed, onReveal }: SolutionRevealProps) {
  if (!revealed) {
    return (
      <Button
        label="Pakita ang solusyon"
        icon="key-outline"
        variant="outline"
        fullWidth
        onPress={onReveal}
      />
    );
  }

  return (
    <Card style={styles.card}>
      <View style={styles.header}>
        <Ionicons name="key" size={16} color={colors.accentPrimary} />
        <ThemedText variant="label" color={colors.accentPrimary}>
          Solusyon
        </ThemedText>
      </View>
      <ThemedText variant="body">{solution}</ThemedText>
    </Card>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surfaceAlt,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
});
