// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — story renderer; confirm badge tone contrast with design.
import { Ionicons } from '@expo/vector-icons';
import { StyleSheet, View } from 'react-native';

import { Card, ThemedText } from '@/components/ui';
import { colors, radii, spacing } from '@/theme';

import { CULTURAL_SETTINGS } from '../constants/culturalSettings';
import type { KwentoDifficulty, KwentoModeResponse } from '../types/kwento.types';

export interface StoryCardProps {
  kwento: KwentoModeResponse;
}

/** Tagalog difficulty labels for the badge (the model emits the English rung). */
const DIFFICULTY_LABEL: Record<KwentoDifficulty, string> = {
  easy: 'Madali',
  medium: 'Katamtaman',
  hard: 'Mahirap',
};

/**
 * Renders one generated kwento: a row of small badges (setting / difficulty /
 * grade) above the full narrative text. Read-only — the embedded problem is
 * surfaced separately by ProblemBlock.
 */
export function StoryCard({ kwento }: StoryCardProps) {
  return (
    <Card>
      <View style={styles.badgeRow}>
        <View style={[styles.badge, styles.badgePrimary]}>
          <Ionicons name="location" size={12} color={colors.accentPrimary} />
          <ThemedText variant="caption" color={colors.accentPrimary}>
            {CULTURAL_SETTINGS[kwento.setting].name}
          </ThemedText>
        </View>
        <View style={[styles.badge, styles.badgeSecondary]}>
          <ThemedText variant="caption" color={colors.accentSecondary}>
            {DIFFICULTY_LABEL[kwento.difficulty]}
          </ThemedText>
        </View>
        <View style={[styles.badge, styles.badgeMuted]}>
          <ThemedText variant="caption" color={colors.textSecondary}>
            Grade {kwento.grade_level}
          </ThemedText>
        </View>
      </View>

      <ThemedText variant="body">{kwento.kwento}</ThemedText>
    </Card>
  );
}

const styles = StyleSheet.create({
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radii.pill,
  },
  badgePrimary: {
    backgroundColor: colors.accentPrimaryDim,
  },
  badgeSecondary: {
    backgroundColor: colors.accentSecondaryDim,
  },
  badgeMuted: {
    backgroundColor: colors.surfaceAlt,
  },
});
