// AUTO-GENERATED by Kiro Agent — Backend Wiring & Dev Tools
/**
 * Global accessibility/settings provider.
 *
 * Bridges the persisted LearningProfile (profileStore + useProfile) to a single
 * reactive context every screen reads through useSettings(). It subscribes to
 * profileStore writes, so a change saved on ANY screen (Settings, onboarding,
 * the scan flow) reflows the whole tree live — no prop drilling, no manual
 * reload calls.
 *
 * The derived view-model fields (themeColors / typography / diagramPalette) are
 * memoized so consumers like ThemedText receive ready-to-spread style objects.
 */
import { createContext, useContext, useEffect, useMemo, type ReactNode } from 'react';

import { subscribeProfileChange } from '@/profile/profileStore';
import {
  type AccessibilitySettings,
  DEFAULT_PROFILE,
  type LearningProfile,
  cloneProfile,
} from '@/profile/types';
import { useProfile } from '@/profile/useProfile';
import {
  createTypography,
  getDiagramPalette,
  getThemeColors,
  useAppFonts,
  type ThemeColors,
} from '@/theme';

/** Flattened, derived settings the whole app consumes through useSettings(). */
export interface SettingsValue {
  profile: LearningProfile;
  accessibility: AccessibilitySettings;
  /** settings.readerFont AND the OpenDyslexic font actually finished loading. */
  readerFontActive: boolean;
  largeText: boolean;
  highContrast: boolean;
  lowMotion: boolean;
  focusMode: boolean;
  colorVision: AccessibilitySettings['colorVision'];
  themeColors: ThemeColors;
  typography: ReturnType<typeof createTypography>;
  diagramPalette: readonly string[];
}

/**
 * Pure projection: a LearningProfile (+ whether the dyslexic font is available)
 * → the derived SettingsValue. Kept outside the component so the safe default
 * and the live provider value share identical derivation logic.
 */
function deriveSettings(profile: LearningProfile, dyslexicAvailable: boolean): SettingsValue {
  const accessibility = profile.accessibilitySettings;
  // Reader Font only takes visual effect once OpenDyslexic has actually loaded.
  const readerFontActive = accessibility.readerFont && dyslexicAvailable;

  return {
    profile,
    accessibility,
    readerFontActive,
    largeText: accessibility.largeText,
    highContrast: accessibility.highContrast,
    lowMotion: accessibility.lowMotion,
    focusMode: accessibility.focusMode,
    colorVision: accessibility.colorVision,
    themeColors: getThemeColors({
      highContrast: accessibility.highContrast,
      colorVision: accessibility.colorVision,
    }),
    typography: createTypography({ largeText: accessibility.largeText, readerFont: readerFontActive }),
    diagramPalette: getDiagramPalette(accessibility.colorVision),
  };
}

/**
 * Safe default, computed once from DEFAULT_PROFILE with the dyslexic font
 * absent. Lets useSettings() return today's default visuals even when no
 * provider is mounted — it never throws.
 */
const DEFAULT_SETTINGS: SettingsValue = deriveSettings(cloneProfile(DEFAULT_PROFILE), false);

const SettingsContext = createContext<SettingsValue>(DEFAULT_SETTINGS);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const { profile, reload } = useProfile();
  const { dyslexicAvailable } = useAppFonts();

  // Live updates: re-read the profile whenever any screen saves or resets it.
  useEffect(() => subscribeProfileChange(() => { void reload(); }), [reload]);

  const value = useMemo(
    () => deriveSettings(profile, dyslexicAvailable),
    [profile, dyslexicAvailable],
  );

  return <SettingsContext.Provider value={value}>{children}</SettingsContext.Provider>;
}

/** Read the live settings. Safe to call without a provider (returns defaults). */
export function useSettings(): SettingsValue {
  return useContext(SettingsContext);
}
