// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — shared first-run store powering the root onboarding gate.
/**
 * Tiny external store for onboarding/first-run status, shared across the route
 * tree via useSyncExternalStore.
 *
 * WHY: the root layout must redirect first-run users to /onboarding, but it also
 * must NOT bounce a user who just finished onboarding back into it. Caching a
 * one-shot async isFirstRun() read in the root creates a race at the moment the
 * onboarding flow navigates to the tabs. Routing the status through this store —
 * which completeOnboarding() updates synchronously before navigation — makes the
 * gate race-free and decoupled (onboarding screens don't need a context prop).
 */
import { useSyncExternalStore } from 'react';

import { isFirstRun, markFirstRunComplete } from './profileStore';

export type OnboardingStatus = 'unknown' | 'first-run' | 'returning';

let status: OnboardingStatus = 'unknown';
const listeners = new Set<() => void>();

function emit(): void {
  for (const listener of listeners) {
    listener();
  }
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

function getSnapshot(): OnboardingStatus {
  return status;
}

/**
 * Read first-run status from secure storage and publish it. Call once at boot.
 *
 * Resilient by design: the root layout keeps the loading spinner up while the
 * status is still 'unknown', so a thrown read (e.g. expo-secure-store
 * unavailable) must NEVER leave the status unresolved — that would strand the
 * student on the spinner forever. On any failure we default to 'first-run'
 * (safest: a fresh student is guided through onboarding) and still emit.
 */
export async function refreshOnboardingStatus(): Promise<OnboardingStatus> {
  try {
    const first = await isFirstRun();
    status = first ? 'first-run' : 'returning';
  } catch (err) {
    console.warn('[Suri] isFirstRun() failed; defaulting to first-run:', err);
    status = 'first-run';
  }
  emit();
  return status;
}

/**
 * Boot safety-net. Forces the status out of 'unknown' if boot stalled before
 * refreshOnboardingStatus() could resolve it (e.g. an earlier init step hung).
 * Idempotent: a no-op once the status is already resolved. The root layout's
 * init-timeout calls this so the loading gate can always clear.
 */
export function resolveOnboardingFallback(): OnboardingStatus {
  if (status === 'unknown') {
    status = 'first-run';
    emit();
  }
  return status;
}

/**
 * Mark onboarding complete: persist the flag AND flip the in-memory status
 * synchronously so the root gate sees 'returning' before the flow navigates to
 * the tabs (no redirect bounce). Onboarding's final step must call this.
 */
export async function completeOnboarding(): Promise<void> {
  status = 'returning';
  emit();
  await markFirstRunComplete();
}

/** Reactive hook used by the root layout (and anywhere gating is needed). */
export function useOnboardingStatus(): OnboardingStatus {
  return useSyncExternalStore(subscribe, getSnapshot);
}
