// AUTO-GENERATED by Kiro Agent — UI Hotfix Sprint (Kasabay Tambayan)
// Status: Needs review — OLED-dark "tambayan" palette for Kasabay Mode (spec 5.10).
/**
 * Kasabay Mode runs on its own high-contrast OLED-dark canvas (spec 5.10) rather
 * than the app's light surface, both for battery on AMOLED panels and to set a
 * calm, focused "study desk" mood. These neon accents are intentionally local to
 * Kasabay so the rest of the app keeps the standard palette.
 */
export const KASABAY_THEME = {
  /** Full-bleed OLED canvas. */
  canvas: '#1A1A2E',
  /** Raised panel / card surface. */
  surface: '#16213E',
  /** Deepest accent surface (e.g. input fields). */
  surfaceAlt: '#0F3460',
  /** Neon teal — primary accent. */
  teal: '#00CEC9',
  /** Electric lime — reward / "go" accent. */
  lime: '#A8FF3E',
  /** Translucent washes for soft accent fills. */
  tealDim: 'rgba(0, 206, 201, 0.14)',
  limeDim: 'rgba(168, 255, 62, 0.14)',
  /** Text on the dark canvas. */
  textPrimary: '#ECECF5',
  textSecondary: '#B8BEDC',
  textMuted: '#7C82A0',
  /** Dark ink for text sitting on a neon button. */
  ink: '#0A0C18',
  /** Modal scrim. */
  overlay: 'rgba(8, 10, 22, 0.82)',
} as const;
