// AUTO-GENERATED by Kiro Agent — Final Native Wiring & QA
// Status: 100% Completion Target
/**
 * Reward triggers for the two "completion moments" (spec 5.9).
 *
 * This is a thin orchestration layer that fires the gamification side effects
 * when a student finishes a meaningful unit of work. It owns no persistence of
 * its own — it composes the existing services so a single completion event feeds
 * every system that cares about it:
 *
 *   - {@link onFocusBlockCompleted} — a finished Kasabay focus block counts as a
 *     study session, advancing the streak (and unlocking any milestone badges).
 *   - {@link onKwentoCompleted} — a finished Kwento drives BOTH the resource
 *     economy + B2B telemetry funnel (via `completeReview`) AND the streak.
 *
 * `recordStudySession` is idempotent within a calendar day, so calling these
 * triggers repeatedly across a session will not inflate the streak.
 */
import type { FocusTimerState } from '@/features/kasabay/types/kasabay.types';
import { completeReview, type RewardSummary } from '@/gamification/resourceService';
import { recordStudySession, type StreakData } from '@/gamification/streakService';

/** Outcome of completing a Kasabay focus block. */
export interface FocusReward {
  /** The streak snapshot after recording the session (incl. evolution tier). */
  streak: StreakData;
  /** Total study time banked by the block, in milliseconds. */
  studiedMs: number;
}

/**
 * Handle the completion of a Kasabay focus block (spec 5.10): a completed block
 * counts as one study session.
 *
 * The studied time is read from the timer's banked total (`accumulatedMs`) — a
 * completed block has already folded its final running segment into that value.
 * Recording the session advances the streak and unlocks any streak-milestone
 * badges that become eligible; it is idempotent within the day.
 *
 * @param state - The completed focus-timer snapshot.
 * @returns The updated streak plus the study time the block banked.
 */
export async function onFocusBlockCompleted(state: FocusTimerState): Promise<FocusReward> {
  const studiedMs = state.accumulatedMs;
  const streak = await recordStudySession();
  return { streak, studiedMs };
}

/** Outcome of completing a Kwento. */
export interface KwentoReward {
  /** Economy + telemetry result of folding the answer into mastery. */
  reward: RewardSummary;
  /** The streak snapshot after recording the session. */
  streak: StreakData;
}

/**
 * Handle the completion of a Kwento (spec 5.9): finishing a kwento drives BOTH
 * the resource economy / telemetry funnel and the daily streak.
 *
 * `completeReview` runs the single transaction that folds the outcome into
 * mastery, credits resources + XP, and enqueues the anonymized competency event;
 * `recordStudySession` then advances the (idempotent) daily streak.
 *
 * @param params - The finished competency and whether the answer was correct.
 * @returns The economy/telemetry reward summary and the updated streak.
 */
export async function onKwentoCompleted(params: {
  competencyCode: string;
  wasCorrect: boolean;
}): Promise<KwentoReward> {
  const reward = await completeReview(params.competencyCode, params.wasCorrect);
  const streak = await recordStudySession();
  return { reward, streak };
}
