// AUTO-GENERATED by Kiro Agent — UI Hotfix Sprint (Floating Navbar)
// Status: Needs review — floating, rounded, scroll-aware bottom tab bar (spec 7).
/**
 * A floating, rounded bottom tab bar that replaces the default flush bar
 * (Phase 1). It hovers above the content (absolute, inset on all sides, large
 * corner radius, soft shadow) and slides off-screen on downward scroll via the
 * shared value from `tabBarVisibility`. It renders straight from the navigator's
 * descriptors, so the per-screen `tabBarIcon`/`title` options defined in the
 * tabs layout continue to drive it.
 */
import type { BottomTabBarProps } from '@react-navigation/bottom-tabs';
import { Platform, Pressable, StyleSheet, View } from 'react-native';
import Animated, { useAnimatedStyle } from 'react-native-reanimated';

import { ThemedText } from '@/components/ui';
import { radii, spacing, useAccessibleTheme } from '@/theme';

import { useTabBarTranslateY } from './tabBarVisibility';

/**
 * Warm light surface for the floating bar, matched to the screenshot palette
 * (cream canvas, white card, terracotta accent). No neon, no dark canvas.
 */
const BAR_LIGHT = {
  surface: '#ffffff', // surface-container-lowest (white card on cream bg)
  active: '#a03b0e', // primary (terracotta)
  activeWash: 'rgba(160, 59, 14, 0.12)', // primary-container wash
  inactive: '#8b7269', // outline / muted
  border: '#dec0b6', // outline-variant
} as const;

/** High-contrast variant (spec 5.6): pure black/white with a heavy border. */
const BAR_HC = {
  surface: '#ffffff',
  active: '#000000',
  activeWash: '#e0e0e0',
  inactive: '#333333',
  border: '#000000',
} as const;

export function FloatingTabBar({ state, descriptors, navigation, insets }: BottomTabBarProps) {
  const { highContrast } = useAccessibleTheme();
  const translateY = useTabBarTranslateY();
  const palette = highContrast ? BAR_HC : BAR_LIGHT;

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [{ translateY: translateY ? translateY.value : 0 }],
  }));

  const bottom = insets.bottom > 0 ? insets.bottom + spacing.xs : spacing.xl;

  return (
    <Animated.View
      pointerEvents="box-none"
      style={[styles.wrap, { bottom }, animatedStyle]}
    >
      <View
        accessibilityRole="tablist"
        style={[
          styles.bar,
          {
            backgroundColor: palette.surface,
            borderColor: palette.border,
            borderWidth: highContrast ? 2 : StyleSheet.hairlineWidth,
          },
        ]}
      >
        {state.routes.map((route, index) => {
          const { options } = descriptors[route.key];
          const isFocused = state.index === index;
          const label =
            typeof options.title === 'string' && options.title.length > 0
              ? options.title
              : route.name;
          const color = isFocused ? palette.active : palette.inactive;

          const onPress = () => {
            const event = navigation.emit({
              type: 'tabPress',
              target: route.key,
              canPreventDefault: true,
            });
            if (!isFocused && !event.defaultPrevented) {
              navigation.navigate(route.name as never);
            }
          };

          const onLongPress = () => {
            navigation.emit({ type: 'tabLongPress', target: route.key });
          };

          return (
            <Pressable
              key={route.key}
              accessibilityRole="button"
              accessibilityState={isFocused ? { selected: true } : {}}
              accessibilityLabel={label}
              onPress={onPress}
              onLongPress={onLongPress}
              style={styles.item}
            >
              <View style={[styles.iconSlot, isFocused && { backgroundColor: palette.activeWash }]}>
                {options.tabBarIcon
                  ? options.tabBarIcon({ focused: isFocused, color, size: 22 })
                  : null}
              </View>
              <ThemedText variant="caption" color={color} style={styles.label} numberOfLines={1}>
                {label}
              </ThemedText>
            </Pressable>
          );
        })}
      </View>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  wrap: {
    position: 'absolute',
    left: spacing.lg,
    right: spacing.lg,
  },
  bar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: radii.pill,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    // Soft floating shadow (kept light for the cream canvas).
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    ...Platform.select({ android: { elevation: 8 }, default: {} }),
  },
  item: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingVertical: spacing.xs,
  },
  iconSlot: {
    width: 40,
    height: 30,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: {
    fontSize: 10,
  },
});
