// AUTO-GENERATED by Kiro Agent — UI Hotfix Sprint (Floating Navbar)
// Status: Needs review — shared scroll-driven visibility for the floating tab bar.
/**
 * Scroll-driven visibility plumbing for the floating tab bar (Phase 1).
 *
 * A single reanimated shared value (`translateY`) is provided to the whole tab
 * group. The custom <FloatingTabBar/> animates off the value, while any
 * scrollable screen spreads `useTabBarScroll()` onto its ScrollView/FlatList to
 * push the bar off-screen on downward scroll and bring it back on upward scroll.
 * Driving one shared value (instead of per-screen state) keeps the animation on
 * the UI thread and lets every tab reuse the exact same behavior.
 */
import { createContext, useCallback, useContext, useMemo, useRef, type ReactNode } from 'react';
import type { NativeScrollEvent, NativeSyntheticEvent } from 'react-native';
import { useSharedValue, withTiming, type SharedValue } from 'react-native-reanimated';

/** Distance (px) the bar travels to fully clear the screen when hidden. */
export const TAB_BAR_HIDDEN_OFFSET = 140;
/**
 * Vertical space a screen should reserve at the bottom so its last items are
 * not covered by the floating bar (bar height + bottom inset + breathing room).
 */
export const TAB_BAR_CLEARANCE = 108;

interface TabBarVisibilityValue {
  translateY: SharedValue<number>;
}

const TabBarVisibilityContext = createContext<TabBarVisibilityValue | null>(null);

/** Wrap the tab group so the bar and its screens share one visibility value. */
export function TabBarVisibilityProvider({ children }: { children: ReactNode }) {
  const translateY = useSharedValue(0);
  const value = useMemo<TabBarVisibilityValue>(() => ({ translateY }), [translateY]);
  return (
    <TabBarVisibilityContext.Provider value={value}>{children}</TabBarVisibilityContext.Provider>
  );
}

/** Internal: the shared translate value (null outside the provider). */
export function useTabBarTranslateY(): SharedValue<number> | null {
  const ctx = useContext(TabBarVisibilityContext);
  return ctx?.translateY ?? null;
}

export interface TabBarScrollProps {
  onScroll: (event: NativeSyntheticEvent<NativeScrollEvent>) => void;
  scrollEventThrottle: number;
}

/**
 * Spread the return value onto a ScrollView/FlatList to hide the floating tab
 * bar while scrolling down and reveal it while scrolling up. Safe to use
 * outside the provider (it simply no-ops).
 */
export function useTabBarScroll(): TabBarScrollProps {
  const translateY = useTabBarTranslateY();
  const lastY = useRef(0);
  const hidden = useRef(false);

  const onScroll = useCallback(
    (event: NativeSyntheticEvent<NativeScrollEvent>) => {
      if (!translateY) {
        return;
      }
      const y = event.nativeEvent.contentOffset.y;
      const dy = y - lastY.current;
      lastY.current = y;

      // Always show the bar near the very top of the content.
      if (y <= 4) {
        if (hidden.current) {
          hidden.current = false;
          translateY.value = withTiming(0, { duration: 180 });
        }
        return;
      }
      // Ignore tiny jitters; only react to a deliberate scroll gesture.
      if (dy > 8 && !hidden.current) {
        hidden.current = true;
        translateY.value = withTiming(TAB_BAR_HIDDEN_OFFSET, { duration: 220 });
      } else if (dy < -8 && hidden.current) {
        hidden.current = false;
        translateY.value = withTiming(0, { duration: 180 });
      }
    },
    [translateY],
  );

  return { onScroll, scrollEventThrottle: 16 };
}
