/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kwento` | `/kwento`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quizzes` | `/quizzes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/review` | `/review`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tanong` | `/tanong`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/accessibility`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/grade-level`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/language`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/learning-profile`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/melc-download`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/kwento` | `/kwento`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/quizzes` | `/quizzes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/review` | `/review`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tanong` | `/tanong`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/accessibility`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/grade-level`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/language`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/learning-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/melc-download`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/scan${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/kwento${`?${string}` | `#${string}` | ''}` | `/kwento${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/quizzes${`?${string}` | `#${string}` | ''}` | `/quizzes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/review${`?${string}` | `#${string}` | ''}` | `/review${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tanong${`?${string}` | `#${string}` | ''}` | `/tanong${`?${string}` | `#${string}` | ''}` | `/onboarding/accessibility${`?${string}` | `#${string}` | ''}` | `/onboarding/grade-level${`?${string}` | `#${string}` | ''}` | `/onboarding/language${`?${string}` | `#${string}` | ''}` | `/onboarding/learning-profile${`?${string}` | `#${string}` | ''}` | `/onboarding/melc-download${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kwento` | `/kwento`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quizzes` | `/quizzes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/review` | `/review`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tanong` | `/tanong`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/accessibility`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/grade-level`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/language`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/learning-profile`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/melc-download`; params?: Router.UnknownInputParams; };
    }
  }
}
