// AUTO-GENERATED by Kiro Agent — Final Native Wiring & QA
// Status: 100% Completion Target
/** @jest-environment node */
/**
 * 3-tier AI router cascade (spec 5.2), exercised through executeRoute() with
 * fully mocked RouteDeps so the REAL shipping decision logic is verified
 * headlessly (no network, no native modules, no API key).
 *
 * Faithful Jest translation of the proven scenarios in
 * scripts/verify-router.mjs:
 *   - strong  : provider failover + top-3 retrieval
 *   - weak    : condensed payload (top-1, 150 tokens)
 *   - offline : on-device model on cache miss (top-5), never reaching providers
 *   - offline : cache hit short-circuits the local model
 *   - online cascade fully exhausted -> degrade to local/offline
 */
import { executeRoute, type ProviderHandle, type RouteDeps } from '@/ai/routerCore';
import { DEFAULT_PROFILE } from '@/profile/types';

const profile = { ...DEFAULT_PROFILE, gradeLevel: 6 };

/** A full RouteDeps with safe defaults; pass overrides per scenario. */
function makeDeps(overrides: Partial<RouteDeps> = {}): RouteDeps {
  return {
    getNetworkTier: async () => 'strong',
    retrieve: async () => ['chunk'],
    buildPrompt: () => 'SYSTEM',
    getCached: async () => null,
    putCached: async () => {},
    getProviders: async () => [],
    runLocalModel: async () => 'local answer',
    ...overrides,
  };
}

/** Build a provider handle from an id + a stream implementation. */
function provider(id: string, impl: ProviderHandle['stream']): ProviderHandle {
  return { id, stream: impl };
}

describe('AI router 3-tier cascade', () => {
  it('strong tier fails over from first provider to second', async () => {
    let retrieveK: number | null = null;

    const result = await executeRoute(
      { message: 'q', profile },
      makeDeps({
        retrieve: async (_query, _gradeLevel, k) => {
          retrieveK = k;
          return ['chunk'];
        },
        getProviders: async () => [
          provider('gemini', async () => {
            throw new Error('rate limited');
          }),
          provider('groq', async () => 'groq answer'),
        ],
      }),
    );

    expect(result.source).toBe('groq');
    expect(result.tier).toBe('strong');
    expect(retrieveK).toBe(3);
  });

  it('weak tier condenses payload', async () => {
    let retrieveK: number | null = null;
    let sentMaxTokens: number | null = null;

    const result = await executeRoute(
      { message: 'q', profile },
      makeDeps({
        getNetworkTier: async () => 'weak',
        retrieve: async (_query, _gradeLevel, k) => {
          retrieveK = k;
          return ['chunk'];
        },
        getProviders: async () => [
          provider('gemini', async ({ maxTokens }) => {
            sentMaxTokens = maxTokens;
            return 'weak answer';
          }),
        ],
      }),
    );

    expect(sentMaxTokens).toBe(150);
    expect(retrieveK).toBe(1);
    expect(result.tier).toBe('weak');
  });

  it('offline tier serves on-device model on cache miss', async () => {
    let providersCalled = false;
    let retrieveK: number | null = null;

    const result = await executeRoute(
      { message: 'q', profile },
      makeDeps({
        getNetworkTier: async () => 'offline',
        getCached: async () => null,
        retrieve: async (_query, _gradeLevel, k) => {
          retrieveK = k;
          return ['chunk'];
        },
        getProviders: async () => {
          providersCalled = true;
          return [];
        },
        runLocalModel: async () => 'local offline answer',
      }),
    );

    expect(result.source).toBe('local');
    expect(result.tier).toBe('offline');
    expect(retrieveK).toBe(5);
    expect(providersCalled).toBe(false);
  });

  it('offline cache hit short-circuits the local model', async () => {
    let localCalled = false;

    const result = await executeRoute(
      { message: 'q', profile },
      makeDeps({
        getNetworkTier: async () => 'offline',
        getCached: async () => 'cached answer',
        runLocalModel: async () => {
          localCalled = true;
          return 'should not run';
        },
      }),
    );

    expect(result.source).toBe('cache');
    expect(result.text).toBe('cached answer');
    expect(localCalled).toBe(false);
  });

  it('all providers failing degrades to local/offline', async () => {
    const result = await executeRoute(
      { message: 'q', profile },
      makeDeps({
        getNetworkTier: async () => 'strong',
        getProviders: async () => [
          provider('gemini', async () => {
            throw new Error('down');
          }),
          provider('groq', async () => {
            throw new Error('down');
          }),
        ],
        runLocalModel: async () => 'degraded',
      }),
    );

    expect(result.source).toBe('local');
    expect(result.tier).toBe('offline');
  });
});
