// AUTO-GENERATED by Kiro Agent — Final Native Wiring & QA
// Status: 100% Completion Target
/** @jest-environment node */
/**
 * Misconception Detection (spec 5.9), exercised through the PURE pieces that
 * drive correctness: the offline taxonomy lookup, the JSON parser, the
 * confidence threshold downgrade, and record mapping. No AI calls, no native
 * modules, no API key.
 *
 * Faithful Jest translation of the proven scenarios in
 * scripts/verify-misconception.mjs:
 *   - a wrong answer triggers the taxonomy lookup (different beliefs -> entries)
 *   - an unrelated message stays conservative (no false positive)
 *   - clean JSON parses the misconception flag + type
 *   - a low-confidence detection is downgraded to a Socratic check
 *   - a detected misconception maps to a persistable record (type + timestamp)
 */
import { CONFIDENCE_THRESHOLD } from '@/features/misconception/constants/misconceptionDefaults';
import { MISCONCEPTION_TAXONOMY } from '@/features/misconception/constants/misconceptionTaxonomy';
import {
  applyConfidenceThreshold,
  buildOfflineResponseFromTaxonomy,
  parseMisconceptionResponse,
  toMisconceptionRecord,
} from '@/features/misconception/services/misconceptionParser';
import { findTaxonomyMatch } from '@/features/misconception/services/misconceptionTaxonomyLookup';
import type { MisconceptionDetectionRequest } from '@/features/misconception/types/misconception.types';

/** A detection request with sane defaults; pass overrides per scenario. */
function makeRequest(
  overrides: Partial<MisconceptionDetectionRequest> = {},
): MisconceptionDetectionRequest {
  return {
    studentMessage: '',
    melcTopic: 'photosynthesis',
    gradeLevel: 6,
    language: 'taglish',
    isOffline: false,
    ...overrides,
  };
}

describe('Misconception Detection', () => {
  it('detects the photosynthesis-at-night belief', () => {
    const match = findTaxonomyMatch('nagpo-photosynthesis pa rin ba kahit gabi?', 'photosynthesis');
    expect(match?.entry.id).toBe('science_photosynthesis_night');
  });

  it('different wrong beliefs map to different taxonomy entries', () => {
    const night = findTaxonomyMatch('nagpo-photosynthesis pa rin ba kahit gabi?', 'photosynthesis');
    const soil = findTaxonomyMatch('ang halaman ay kumakain ng lupa kaya lumalaki', 'photosynthesis');

    expect(night?.entry.id).toBe('science_photosynthesis_night');
    expect(soil?.entry.id).toBe('science_photosynthesis_soil');
    expect(night?.entry.id).not.toBe(soil?.entry.id);
    expect(night?.entry.targetedExplanation).not.toBe(soil?.entry.targetedExplanation);
  });

  it('an unrelated message yields no match', () => {
    expect(findTaxonomyMatch('Ano ang kabisera ng Pilipinas?', 'araling panlipunan')).toBeNull();
  });

  it('clean JSON parses the misconception flag and type', () => {
    const parsed = parseMisconceptionResponse(
      JSON.stringify({
        has_misconception: true,
        misconception_type: 'WRONG_CAUSATION',
        confidence: 0.88,
        language_detected: 'english',
      }),
      makeRequest(),
    );

    expect(parsed.has_misconception).toBe(true);
    expect(parsed.misconception_type).toBe('WRONG_CAUSATION');
  });

  it('low-confidence detection is downgraded', () => {
    const parsed = parseMisconceptionResponse(
      JSON.stringify({
        has_misconception: true,
        misconception_type: 'WRONG_CAUSATION',
        specific_wrong_belief: 'heavier falls faster',
        targeted_explanation: 'actually they fall together',
        confidence: 0.5,
        language_detected: 'english',
      }),
      makeRequest(),
    );

    const downgraded = applyConfidenceThreshold(parsed, CONFIDENCE_THRESHOLD);
    expect(downgraded.has_misconception).toBe(false);
  });

  it('a detected misconception logs a record with type + timestamp', () => {
    const entry = MISCONCEPTION_TAXONOMY.find((e) => e.id === 'math_fractions_denominator');
    expect(entry).toBeDefined();
    if (!entry) {
      throw new Error('taxonomy entry "math_fractions_denominator" must exist');
    }

    const request = makeRequest({ melcTopic: 'fractions', gradeLevel: 4 });
    const rec = toMisconceptionRecord(buildOfflineResponseFromTaxonomy(entry, request), request);

    expect(rec.topic).toBe('fractions');
    expect(rec.gradeLevel).toBe(4);
    expect(rec.misconceptionType).toBe('WRONG_DEFINITION');
    expect(rec.detectedAt).toBeInstanceOf(Date);
  });
});
