// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — shared surface card with optional neon border.
import { type ReactNode } from 'react';
import { StyleSheet, View, type ViewStyle } from 'react-native';

import { colors, radii, spacing } from '@/theme';

export interface CardProps {
  children: ReactNode;
  /** Highlight with a neon teal border (spec 5.10 "tambayan" accent). */
  neon?: boolean;
  style?: ViewStyle | ViewStyle[];
}

export function Card({ children, neon = false, style }: CardProps) {
  // Read the neon accent inline (not from the frozen StyleSheet) so it follows
  // the live Color Vision palette.
  return (
    <View style={[styles.card, neon && [styles.neon, { borderColor: colors.borderNeon }], style]}>
      {children}
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  neon: {
    borderColor: colors.borderNeon,
    borderWidth: 1.5,
  },
});
