// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — shared UI kit barrel; import from '@/components/ui'.
export { ThemedText, type ThemedTextProps, type TextVariant } from './ThemedText';
export { Button, type ButtonProps, type ButtonVariant } from './Button';
export { Card, type CardProps } from './Card';
export { Screen, type ScreenProps } from './Screen';
