// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — shared screen wrapper (canvas + safe area + gutters).
import { type ReactNode } from 'react';
import {
  ScrollView,
  StyleSheet,
  View,
  type NativeScrollEvent,
  type NativeSyntheticEvent,
  type ViewStyle,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { TAB_BAR_CLEARANCE } from '@/navigation/tabBarVisibility';
import { colors, layout } from '@/theme';

export interface ScreenProps {
  children: ReactNode;
  /** Wrap content in a ScrollView. Default false. */
  scroll?: boolean;
  /** Apply standard horizontal/vertical gutters. Default true. */
  padded?: boolean;
  /** Center content vertically (handy for empty/loading states). */
  center?: boolean;
  /** Reserve bottom space so content clears the floating tab bar. Default false. */
  tabBarClearance?: boolean;
  /** Scroll handler (e.g. from useTabBarScroll) — only used when scroll is true. */
  onScroll?: (event: NativeSyntheticEvent<NativeScrollEvent>) => void;
  scrollEventThrottle?: number;
  contentStyle?: ViewStyle | ViewStyle[];
}

/**
 * Every tab/onboarding screen wraps in this so the canvas, safe-area insets, and
 * gutters are identical app-wide. Optionally reserves bottom clearance for the
 * floating tab bar and forwards a scroll handler so the bar can hide on scroll.
 */
export function Screen({
  children,
  scroll = false,
  padded = true,
  center = false,
  tabBarClearance = false,
  onScroll,
  scrollEventThrottle,
  contentStyle,
}: ScreenProps) {
  const inner: ViewStyle[] = [
    padded ? styles.padded : styles.flush,
    center ? styles.center : null,
    tabBarClearance ? { paddingBottom: TAB_BAR_CLEARANCE } : null,
    Array.isArray(contentStyle) ? Object.assign({}, ...contentStyle) : contentStyle,
  ].filter(Boolean) as ViewStyle[];

  return (
    <SafeAreaView style={styles.safe} edges={['top', 'left', 'right']}>
      {scroll ? (
        <ScrollView
          style={styles.flex}
          contentContainerStyle={[styles.scrollContent, ...inner]}
          keyboardShouldPersistTaps="handled"
          onScroll={onScroll}
          scrollEventThrottle={scrollEventThrottle ?? 16}
        >
          {children}
        </ScrollView>
      ) : (
        <View style={[styles.flex, ...inner]}>{children}</View>
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  padded: {
    paddingHorizontal: layout.screenPaddingH,
    paddingVertical: layout.screenPaddingV,
  },
  flush: {},
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
});
