// AUTO-GENERATED by Kiro Agent — Suri Frontend Integration
// Phase 6 Auto-Fix | Spec: suri-mobile-project-spec-v3.md
// Status: Needs review — shared typed Text; variants map to the type scale.
import { Text, type TextProps } from 'react-native';

import { typography as baseTypography, useAccessibleTheme } from '@/theme';

export type TextVariant = keyof typeof baseTypography;

export interface ThemedTextProps extends TextProps {
  variant?: TextVariant;
  /** Theme color token. Defaults to the active (high-contrast-aware) text color. */
  color?: string;
  center?: boolean;
}

/**
 * The single Text primitive for the app. Bakes in the type scale + palette so
 * screens never hardcode font sizes or hex colors.
 *
 * Accessibility (spec 5.6) is applied here so it is GLOBAL: the type scale is
 * resolved live from the student's settings, so "Larger Text" (1.3x) and
 * "Reader Font" (OpenDyslexic) take effect across every screen at once, and the
 * default text color follows the high-contrast palette.
 */
export function ThemedText({
  variant = 'body',
  color,
  center = false,
  style,
  ...rest
}: ThemedTextProps) {
  const { typography, colors } = useAccessibleTheme();
  const resolvedColor = color ?? colors.textPrimary;
  return (
    <Text
      {...rest}
      style={[typography[variant], { color: resolvedColor }, center && { textAlign: 'center' }, style]}
    />
  );
}
